### ISSUE TITLE
> 获取视频ID失败

### ISSUE THREAD

**Issue by Evil0ctal** [Evil0ctal/Douyin_TikTok_Download_API#100]
> 

还是不行，显示获取视频ID出错

__最初由 @Git1015 在 https://github.com/Evil0ctal/Douyin_TikTok_Download_API/issues/53#issuecomment-1310215638 发布__

**Comment by Evil0ctal** [comment]
请把当时提交的链接发给我。

**Comment by Git1015** [comment]
> 

https://api16-normal-useast5.us.tiktokv.com/aweme/v1/play/?video_id=v12044gd0000cctpltbc77u2530nha00&line=0&is_play_url=1&source=PackSourceEnum_FEED&file_id=bdb1e5a7b8f44c61a5bd630cf030a038&residence=US&device_id=7164007649949648430&os_version=15.4.1&iid=7164008742565316398&app_name=musical_ly&locale=zh-Hans&ac=WIFI&sys_region=CN&js_sdk_version=&version_code=25.8.0&channel=App%20Store&op_region=US&tma_jssdk_version=&os_api=18&idfa=00000000-0000-0000-0000-000000000000&idfv=00000000-0000-0000-0000-000000000000&device_platform=iphone&device_type=iPhone11%2C6&carrier_region1=US&openudid=900d2b41101d3554f8cf47035418a053f1f22efc&account_region=us&tz_name=Asia%2FShanghai&tz_offset=28800&app_language=zh&carrier_region=US&build_number=244302&aid=1233&mcc_mnc=310032&screen_width=1242&content_language=&current_region=US&language=zh&cdid=7F60BEE3-086A-46B1-B7D0-133881F49E63&uoo=1&app_version=25.8.0

**Comment by Evil0ctal** [comment]
需要视频的分享链接

**Comment by Git1015** [comment]
> 需要视频的分享链接

快捷指令都没安装好，安装一半才显示获取视频ID出错，而不是保存视频的时候

**Comment by Git1015** [comment]
> 需要视频的分享链接

快捷指令都没安装好，安装一半才显示获取视频ID出错，而不是保存视频的时候

**Comment by Evil0ctal** [comment]
视频ID获取失败跟快捷指令没有关系，如果没有分享链接或原视频链接的话，就没有办法找出问题。

**Comment by Evil0ctal** [comment]
请检查最新scraper.py是否修复了该问题，如果问题依旧存在请重新开启此issue
