### ISSUE TITLE
Could you add a function to batch parse video urls based on a specific (hash_tag)

### ISSUE THREAD

**Issue by guanyy217** [Evil0ctal/Douyin_TikTok_Download_API#101]
希望增加一个功能：从搜索标签的结果页，批量解析该标签相关的视频网址（或视频ID）
非常感谢！

I want to add the function to batch parse the associated video URLs (or video ids) from the results page of the search tag.
Thank you so much!

**Comment by Evil0ctal** [comment]
好的，我描述一下这个需求。

加入我看到某视频下方有一个hashtag`#fyp`，当我点击该hashtag之后会跳转到包含该hashtag的视频列表页，你需要的是该列表内的视频数据爬取。

请问我的描述符合你想表达的需求吗？

**Comment by kk20180123** [comment]
![image](https://user-images.githubusercontent.com/76581611/201521253-3481a148-d48d-4683-b360-15a2dab4a965.png)

**Comment by ChthollyLee** [comment]
我也很需要这个功能， 感谢。
