### ISSUE TITLE
视频ID获取失败

### ISSUE THREAD

**Issue by Evil0ctal** [Evil0ctal/Douyin_TikTok_Download_API#102]
![image](https://user-images.githubusercontent.com/76581611/201521253-3481a148-d48d-4683-b360-15a2dab4a965.png)

__最初由 @kk20180123 在 https://github.com/Evil0ctal/Douyin_TikTok_Download_API/issues/101#issuecomment-1312716925 发布__

**Comment by Evil0ctal** [comment]
请提供原始分享链接给我

**Comment by kk20180123** [comment]
> 请提供原始分享链接给我

https://vm.tiktok.com/ZMF59AGrF/

**Comment by Evil0ctal** [comment]
已修复

**Comment by kk20180123** [comment]
> 已修复

还不行，还是刚才那个错误。


https://vm.tiktok.com/ZMF54kMmb/

**Comment by Evil0ctal** [comment]
你好，我还没有将代码部署至服务器，但是这个问题已经修复了，晚点我会把仓库的代码部署至服务器上。

**Comment by kk20180123** [comment]
> 你好，我还没有将代码部署至服务器，但是这个问题已经修复了，晚点我会把仓库的代码部署至服务器上。

好的，劳烦您。
