### ISSUE TITLE
[BUG] tiktok有个视频的下载，总是出错。

### ISSUE THREAD

**Issue by wzboyer** [Evil0ctal/Douyin_TikTok_Download_API#107]
***发生错误的平台？***

 TikTok

***发生错误的端点？***
三个都试过，一样的，API-V1/API-V2/Web APP

***提交的输入值？***
 
https://vm.tiktok.com/ZMFHSEp6J/

 
https://www.tiktok.com/@user5875741980434/video/7166974134272970011

这两个网址是同一个视频，视频内容是女生和一条狗。可是解析出来的视频，都不是这个原视频，下载的视频也不是原视频
***是否有再次尝试？***

 是，发生错误后X时间后错误依旧存在。

***你有查看本项目的自述文件或接口文档吗？***

如：有，并且很确定该问题是程序导致的。

**Comment by Evil0ctal** [comment]
你好，该视频已经被删除或被屏蔽。
