### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by minhyeu13** [Evil0ctal/Douyin_TikTok_Download_API#108]
***发生错误的平台？***

如：抖音/TikTok

***发生错误的端点？***

如：API-V1/API-V2/Web APP

***提交的输入值？***

如：短视频链接

***是否有再次尝试？***

如：是，发生错误后X时间后错误依旧存在。

***你有查看本项目的自述文件或接口文档吗？***

如：有，并且很确定该问题是程序导致的。

**Comment by Evil0ctal** [comment]
请勿提交无效issue
