### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by davidleboblai** [Evil0ctal/Douyin_TikTok_Download_API#112]
Tiktok api not working in your code any more
This message appear :

{"function":"webapi()","reason":"Object of type JSONDecodeError is not JSON serializable","status":"failed","time":"1.5905s","value":"https://vm.tiktok.com/ZMFQEuNqE"}

**Comment by Evil0ctal** [comment]
I'm currently working on it, TikTok's API is changed.

**Comment by davidleboblai** [comment]
Thanks man we wait you🥂

**Comment by Evil0ctal** [comment]
Fixed
