### ISSUE TITLE
api 返回错误

### ISSUE THREAD

**Issue by jiujiude** [Evil0ctal/Douyin_TikTok_Download_API#113]
https://api.douyin.wtf/api?url=https://www.tiktok.com/@/video/7167614344241499418

`
{
  "url": "https://www.tiktok.com/@/video/7167614344241499418",
  "endpoint": "/api/",
  "total_time": 0.2007,
  "status": "failed",
  "message": "返回数据为空，无法处理！/Return data is empty and cannot be processed!"
}
`

**Comment by Evil0ctal** [comment]
已经修复了

**Comment by jiujiude** [comment]
目前请求返回还是错误的，貌似没有生效？？
