### ISSUE TITLE
[Feature request] lang in TikTok Videos

### ISSUE THREAD

**Issue by jag-k** [Evil0ctal/Douyin_TikTok_Download_API#117]
Please, add lang (or `region`) field by TikTok videos

**Comment by Evil0ctal** [comment]
Hello, I can add a region request parameter, but what is the practical significance of this?  Also, is your request targeting API-V2?

**Comment by jag-k** [comment]
I'm using this in my telegram bot for more comfortable sending videos to my friends. And I want to add emoji flags based by video/images region. I'm using API-v1 and API-v2 in mini mode

**Comment by Evil0ctal** [comment]
OK, I will add the region in request parameter and try add the region in API response.

Thank you for the feedback!

**Comment by Evil0ctal** [comment]
Use this JSON Path 

`$.author.region`
