### ISSUE TITLE
[BUG] Douyin platform API issue

### ISSUE THREAD

**Issue by cuiweizhao** [Evil0ctal/Douyin_TikTok_Download_API#118]
试了多个抖音视频都是一样
![021C49D2-F6CB-4B57-BB32-3E4751DBF79F](https://user-images.githubusercontent.com/8664569/206532774-ccfb6659-c142-4e0c-8236-7f1561f82825.jpeg)

**Comment by Evil0ctal** [comment]
好的，我晚点去解决，感谢反馈！

**Comment by Evil0ctal** [comment]
你好，刚刚测试了一下，好像没有在我这边复现你的问题，可以提供一下你提交的链接给我吗？

**Comment by Evil0ctal** [comment]
已修复
