### ISSUE TITLE
快捷指令无法下载[BUG] 简短明了的描述问题

### ISSUE THREAD

**Issue by machinewx** [Evil0ctal/Douyin_TikTok_Download_API#119]
- [ ]  @[](url)***发生错误的平台？***
抖音ios
无法下载的视频链接
4.17 OXm:/ 复制打开抖音，看看【小麦日记的作品】她看起来也好下饭 # 赵今麦  https://v.douyin.com/hjbPMsV/
![IMG_8172](https://user-images.githubusercontent.com/15651229/206643349-d3166ca8-e11e-420c-8f59-dd58587894e4.jpg)

**Comment by Evil0ctal** [comment]
已修复
