### ISSUE TITLE
在线坐等docker版

### ISSUE THREAD

**Issue by mayjack0312** [Evil0ctal/Douyin_TikTok_Download_API#12]
在线等大佬开发docker版

**Comment by Evil0ctal** [comment]
> 在线等大佬开发docker版

好的，我最近会制作一个pip包，做完之后会去研究一下docker，同时也欢迎你PR😋

**Comment by Al-Iverson** [comment]
期待pip包 在线等

**Comment by Evil0ctal** [comment]
> 期待pip包 在线等

嗯嗯，目前可以先导入`scraper.py`暂时用一下。

**Comment by jer0y** [comment]
我这边整合了一个docker包
https://hub.docker.com/repository/docker/jre0/tiktokwebdownload

**Comment by Evil0ctal** [comment]
> 我这边整合了一个docker包 https://hub.docker.com/repository/docker/jre0/tiktokwebdownload

谢谢你🥰

**Comment by Al-Iverson** [comment]
哈喽 老哥、我简单看了下代码。有两种方式获取tiktok的链接。1.原生tiktok url请求。解析网页得到的。 2.爬取的这个网站的数据https://ttdownloader.com。 我有2个担心。第一种方案tiktok可能会封ip嘛？ 第二种方案，这个网站是您这边的管理的嘛？万一改了策略，可能就无法用了。我想用到我的项目里，担心稳定性。

**Comment by Evil0ctal** [comment]
> 哈喽 老哥、我简单看了下代码。有两种方式获取tiktok的链接。1.原生tiktok url请求。解析网页得到的。 2.爬取的这个网站的数据[https://ttdownloader.com。](https://ttdownloader.com%E3%80%82) 我有2个担心。第一种方案tiktok可能会封ip嘛？ 第二种方案，这个网站是您这边的管理的嘛？万一改了策略，可能就无法用了。我想用到我的项目里，担心稳定性。

是的，我也考虑到这个了，我马上会对tiktok方法进行重写，然后使用tiktok官方的API进行数据获取，预计2-3天左右会写完。

**Comment by Al-Iverson** [comment]
OK，需要帮忙嘛？可以的话，加我qq哈 1538697392.

**Comment by Evil0ctal** [comment]
> OK，需要帮忙嘛？可以的话，加我qq哈 1538697392.

没事，我已经快写完了，测试完之后我会更新`scraper.py`。

**Comment by younger027** [comment]
嗯嗯呢，我也查了下。找到了些资料。感谢您的回复。

**Comment by Evil0ctal** [comment]
> 嗯嗯呢，我也查了下。找到了些资料。感谢您的回复。

嗯嗯，不客气。

**Comment by joe21244966** [comment]
docker版本跑起来了，但是解析一直报错。看了log是这样的

**Comment by Evil0ctal** [comment]
> docker版本跑起来了，但是解析一直报错。看了log是这样的，2022-08-03 08:08:28:
> 
> Scraper.tiktok(): Expecting value: line 1 column 1 (char 0)
> 
> Input value: https://www.tiktok.com/@arlenmarion6546/video/7117939094176697646
> 
> 

使用代理再试一下

**Comment by joe21244966** [comment]
> 

是指服务器上的请求弄全局代理IP再出去吗？可以通过下wx，太难我就直接赞助你服务算了哈哈哈

**Comment by Evil0ctal** [comment]
> > 
> 
> 
> 
> 是指服务器上的请求弄全局代理IP再出去吗？可以通过下wx，太难我就直接赞助你服务算了哈哈哈

是的，修改config.ini中的代理即可。
