### ISSUE TITLE
评论的功能在代码里面好像没有

### ISSUE THREAD

**Issue by codewithevan** [Evil0ctal/Douyin_TikTok_Download_API#124]
你好，获取评论的功能代码里面好像没有，我看v2文档已经有了

**Comment by Evil0ctal** [comment]
已经计划添加了。

**Comment by codewithevan** [comment]
好的哈，等你

**Comment by Evil0ctal** [comment]
请使用这个包：

https://github.com/TikHubIO/TikHub_API_PyPi

目前：

抖音评论接口不可用

TikTok评论接口可用
