### ISSUE TITLE
抖音链接失效了

### ISSUE THREAD

**Issue by 5wcx** [Evil0ctal/Douyin_TikTok_Download_API#127]
https://www.iesdouyin.com/web/api/v2/aweme/iteminfo/?item_ids=7175083035304398120
这个接口 无法访问了

**Comment by Meridianer** [comment]
获取原视频都无法获取了

**Comment by Meridianer** [comment]
抖音无法获取 tiktok 还是可以获取到

**Comment by GTXT88** [comment]
直接通过浏览器开发者模式查一下现在无水印视频链接是什么样的就知道到底哪里有改动了

**Comment by Meridianer** [comment]
好的 我去看看

**Comment by Evil0ctal** [comment]
是的，我已经发现了，我晚点去修复这个问题。

**Comment by Evil0ctal** [comment]
已修复

**Comment by GTXT88** [comment]
补充一下：
api_post_url = 'https://www.iesdouyin.com/web/api/v2/aweme/%s/sec_uid=%s&count=%s&max_cursor=%s&aid=1128&_signature=PDHVOQAAXMfFyj02QEpGaDwx1S&dytk=' % (self.mode, self.sec, str(self.count), max_cursor)
也要改一下（变成下面的）
api_post_url = 'https://www.iesdouyin.com/aweme/v1/web/aweme/%s/?sec_user_id=%s&count=%s&max_cursor=%s&aid=1128&_signature=PDHVOQAAXMfFyj02QEpGaDwx1S&dytk=' % (self.mode, self.sec, str(self.count), max_cursor)

**Comment by Evil0ctal** [comment]
好的，这个也是单一视频的API吗？

**Comment by Evil0ctal** [comment]
使用目前部署的这个接口，解析某些视频时会反回空数据。

视频链接：

8.99 ATL:/ 复制打开抖音，看看【花垚头像库的图文作品】最后一张，未成年禁止使用。# 优质头像 # 优质男... https://v.douyin.com/hgDMtfN/

**Comment by GTXT88** [comment]
> 好的，这个也是单一视频的API吗？

这个是从用户主页批量下载视频时构建的链接

**Comment by Evil0ctal** [comment]
> > 好的，这个也是单一视频的API吗？
> 
> 这个是从用户主页批量下载视频时构建的链接

好的，我已经修改了，感谢你的反馈！

**Comment by Evil0ctal** [comment]
单一视频的API依旧有问题，图文视频无法进行解析。

**Comment by Evil0ctal** [comment]
今天测试了一下，新接口又失效了。

**Comment by OliverXiao** [comment]
> 补充一下： api_post_url = 'https://www.iesdouyin.com/web/api/v2/aweme/%s/sec_uid=%s&count=%s&max_cursor=%s&aid=1128&_signature=PDHVOQAAXMfFyj02QEpGaDwx1S&dytk=' % (self.mode, self.sec, str(self.count), max_cursor) 也要改一下（变成下面的） api_post_url = 'https://www.iesdouyin.com/aweme/v1/web/aweme/%s/?sec_user_id=%s&count=%s&max_cursor=%s&aid=1128&_signature=PDHVOQAAXMfFyj02QEpGaDwx1S&dytk=' % (self.mode, self.sec, str(self.count), max_cursor)
> 
> 还有 “api_next_post_url” 也要相应的改一下

这个api post url 只能获取视频信息，图文信息获取不了

**Comment by Evil0ctal** [comment]
已经修复了，普通视频和图文视频都可以解析。

**Comment by lionzheng** [comment]
> > 补充一下： api_post_url = 'https://www.iesdouyin.com/web/api/v2/aweme/%s/sec_uid=%s&count=%s&max_cursor=%s&aid=1128&_signature=PDHVOQAAXMfFyj02QEpGaDwx1S&dytk=' % (self.mode, self.sec, str(self.count), max_cursor) 也要改一下（变成下面的） api_post_url = 'https://www.iesdouyin.com/aweme/v1/web/aweme/%s/?sec_user_id=%s&count=%s&max_cursor=%s&aid=1128&_signature=PDHVOQAAXMfFyj02QEpGaDwx1S&dytk=' % (self.mode, self.sec, str(self.count), max_cursor)
> > 还有 “api_next_post_url” 也要相应的改一下
> 
> 这个api post url 只能获取视频信息，图文信息获取不了

这个v1也失效了。。。

**Comment by Evil0ctal** [comment]
请使用TikHub的API

https://api.tikhub.io/docs#/Douyin/get_douyin_user_profile_videos_douyin_profile_videos__get

**Comment by yik7707** [comment]
使用他们家的测试账号仍然获取不了主页
![QQ截图20230207032848](https://user-images.githubusercontent.com/74293458/217066633-2869e73d-d64e-4577-8569-52244d96606a.png)

**Comment by lionzheng** [comment]
大佬们， https://www.iesdouyin.com/aweme/v1/web/aweme/post/ 也失效了。

**Comment by amumuku** [comment]
现在有解析了

**Comment by amumuku** [comment]
现在有解析了吗

**Comment by amumuku** [comment]
现在有解析了吗

**Comment by iicey** [comment]
同问
