### ISSUE TITLE
[Feature request] 添加抖音直播页短链接的支持

### ISSUE THREAD

**Issue by micoe** [Evil0ctal/Douyin_TikTok_Download_API#128]
***发生错误的平台？***

抖音

***发生错误的端点？***

Web APP

***提交的输入值？***

短直播链接

***是否有再次尝试？***

是，发生错误后X时间后错误依旧存在。

***你有查看本项目的自述文件或接口文档吗？***

有，并且很确定该问题是程序导致的。

**Comment by Evil0ctal** [comment]
好的，我去修复这个问题。

**Comment by micoe** [comment]
> 好的，我去修复这个问题。

刚试了一下还是不行，解析失败

**Comment by Evil0ctal** [comment]
你把你提交的链接给我。

**Comment by micoe** [comment]
4- #在抖音，记录美好生活#【肖哥音乐(24小时直播)】正在直播，来和我一起支持Ta吧。复制下方链接，打开【抖音】，直接观看直播！ https://v.douyin.com/h7EVCHJ/




---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月27日(周二) 凌晨3:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Evil0ctal/Douyin_TikTok_Download_API] [BUG] 抖音直播解析失败 (Issue #128)




 
你把你提交的链接给我。

**Comment by Evil0ctal** [comment]
好的，你尝试一下自行部署项目，可能是服务器IP被抖音拉黑了。

**Comment by Evil0ctal** [comment]
提交的链接出问题了，支持这种格式`https://live.douyin.com/966302232687`，不过我可以添加对上面那个链接的支持，我会取消此issue的BUG标签。

**Comment by micoe** [comment]
抖音APP复制出来的都是这种短链接



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月27日(周二) 上午8:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Evil0ctal/Douyin_TikTok_Download_API] [BUG] 抖音直播解析失败 (Issue #128)




 
提交的链接出问题了，支持这种格式https://live.douyin.com/966302232687，不过我可以添加对上面那个链接的支持，我会取消此issue的BUG标签。

**Comment by Evil0ctal** [comment]
是的，我是在浏览器上复制的链接，一开始没想过在手机上获取链接，我会在下一个版本加上这种链接的支持。

**Comment by Evil0ctal** [comment]
看了一下，好像无法从短链接中获取直播间号码，必须是这种格式`https://live.douyin.com/966302232687`才可以，你手动复制短链接到浏览器然后获取正常链接在提交至API解析吧。

我会保持这个issue开启，如果以后有啥好的办法我再update。
