### ISSUE TITLE
[BUG] 获取不到笔记的视频数据

### ISSUE THREAD

**Issue by Nkomol** [Evil0ctal/Douyin_TikTok_Download_API#129]
***发生错误的平台？***

抖音

***发生错误的端点？***

Web APP

***提交的输入值？***

[短视频链接](https://www.douyin.com/note/7179529949714418996)

***是否有再次尝试？***

是，发生错误后我查看了api接口，确实最新版本的接口无法实现对笔记的解析

***你有查看本项目的自述文件或接口文档吗？***

有，并且很确定该问题是程序导致的。

**Comment by Evil0ctal** [comment]
是的，这个问题已经在处理了。
