### ISSUE TITLE
[BUG] WebApp内 视频下载链接接口返回值为空 视频连接可正常访问

### ISSUE THREAD

**Issue by ArnyRen** [Evil0ctal/Douyin_TikTok_Download_API#130]
***发生错误的平台？***

抖音
***发生错误的端点？***

Web APP

***提交的输入值？***

[短视频链接](https://v.douyin.com/hn829dc/)

***是否有再次尝试？***

是，发生错误后至少12小时后错误依旧存在。

***你有查看本项目的自述文件或接口文档吗？***

有，并且很确定该问题是程序导致的。

如标题所述 WebApp内（https://douyin.wtf/ ） 解析抖音视频后 视频下载链接接口返回值为空 无论是带水印和无水印的连接均为如下提示
{"status":"failed","message":"返回数据为空，无法处理！/Return data is empty and cannot be processed!"}
 
有水印和无水印的视频连接可正常打开视频文件
同时 ios的快捷方式解析视频时也失败 提示检测到当前链接解析失败！原因：返回数据为空，无法处理！/Return data is empty and connot be processed

**Comment by ArnyRen** [comment]
问题于今日约18:00后复现 依旧是有水印和无水印的视频连接可正常打开视频文件 视频下载链接接口返回值为空

**Comment by Evil0ctal** [comment]
好的，看起来接口又改变了。

**Comment by quanzhizhao** [comment]
我现在无法下载

**Comment by Evil0ctal** [comment]
尝试一下自行部署本项目，可能是服务器IP被抖音拉黑了。

**Comment by Evil0ctal** [comment]
证实是服务器IP被抖音拉黑了，跟代码没有关系，以及迁移至另外一台服务器了，问题已解决。
