### ISSUE TITLE
[BUG] API Tiktok Cant Access

### ISSUE THREAD

**Issue by azickri** [Evil0ctal/Douyin_TikTok_Download_API#132]
***Platform where the error occurred?***

Such as: TikTok

***The endpoint where the error occurred?***

Such as: API-V1/API-V2/Web APP
https://api16-normal-c-useast1a.tiktokv.com/aweme/v1/feed/?aweme_id={video_id}&aid=1180

***Submitted input value?***

Such as: video link

***Have you tried again?***

Such as: Yes, i tried to hit that API

***Have you checked the readme or interface documentation for this project?***

Such as: Yes, and it is very sure that the problem is caused by the program.

**Comment by Evil0ctal** [comment]
Looks like TikTok API had been updated.

I will fix it later.

If you in rush, try api.tikhub.io

**Comment by azickri** [comment]
That's Great!
But, in Tikhub need username and password.
Where can I get this data from?

**Comment by TheBunnies** [comment]
It seems like API for the TikTok video CDN has been changed as well `https://v16-web-newkey.tiktokcdn.com/`. Since you can't download videos from it anymore, it gives you 403 (Forbidden) HTTP status code everytime you try to get a response. Tried using several proxies, none of them worked.

**Comment by Evil0ctal** [comment]
Yeah, just saw it response empty data.
