### ISSUE TITLE
[ 重要通知 ] 有关抖音接口返回内容为空的问题

### ISSUE THREAD

**Issue by Evil0ctal** [Evil0ctal/Douyin_TikTok_Download_API#135]
# 2022/12/28

抖音在北京时间21号的时候关闭了本项目使用的API，新的API在请求上没有限制，但是经过这几天的使用，抖音似乎对频繁请求该API的IP进行了封锁，如果我发现API失效了，我会尽可能更换IP来解决此问题，后期如果一直被封锁的话可能会使用代理池解决，但是如果你有能力的话，可以自行部署本项目。

部署教程：

https://github.com/Evil0ctal/Douyin_TikTok_Download_API#%E9%83%A8%E7%BD%B2%E6%96%B9%E5%BC%8F%E4%B8%80-linux

旧API: 

https://github.com/Evil0ctal/Douyin_TikTok_Download_API/blob/cb2b01333b82eac37a3429e53d10fcca8506b0bd/scraper.py#L239

新API:

https://github.com/Evil0ctal/Douyin_TikTok_Download_API/blob/cb2b01333b82eac37a3429e53d10fcca8506b0bd/scraper.py#L242

# 2022/12/31

该问题已经得到了很好的解决，目前能保证API具有 > 90%的可用性。

This issue has been well resolved and the API is currently guaranteed to have > 90% availability.

**Comment by cosylxc** [comment]
大佬，你好，请问部署了docker的话，可以解析主页链接然后下载吗，图片呢？

**Comment by Evil0ctal** [comment]
主页暂不支持图文，我去看看能不能解决，很快会写一个简单的下载器。

**Comment by nhantamz** [comment]
Hi,  BTW, the API https://www.iesdouyin.com/aweme/v1/web/aweme/post/?...  will block by IP address if we access it too frequently.

Is any other solution to bypass this firewall blocking?

thanks.

**Comment by Evil0ctal** [comment]
You need to use proxy, otherwise slower you request sending frequency.

**Comment by wo0d** [comment]
大概什么样的访问频率才会被封IP？比如1秒访问多少次被封？

**Comment by Evil0ctal** [comment]
暂时还没测试过，你可以测试一下。

**Comment by hinspath** [comment]
[](url)
![1672478028394](https://user-images.githubusercontent.com/54998533/210133271-7938c405-8fe9-4270-9dff-b5f54c06816d.jpg)
这样就是返回为空的问题吗？

**Comment by Evil0ctal** [comment]
> ![1672478028394](https://user-images.githubusercontent.com/54998533/210133271-7938c405-8fe9-4270-9dff-b5f54c06816d.jpg) 这样就是返回为空的问题吗？

你这个是旧版本的，请使用最新版本。

**Comment by Evil0ctal** [comment]
# 2022/12/31

该问题已经得到了很好的解决，目前能保证API具有 > 90%的可用性。

This issue has been well resolved and the API is currently guaranteed to have > 90% availability.

**Comment by DLspark** [comment]
![image](https://user-images.githubusercontent.com/50164791/211739073-99d9c303-a2ea-450b-b93c-9222022b26be.png)
大佬，现在接口是不是又不能用了？

**Comment by Evil0ctal** [comment]
依旧可用。

**Comment by chenmihe** [comment]
大佬，Tik Tok的是不是用不了？

**Comment by 2857584289** [comment]
您好，这几天我使用v1接口，返回的数据是：blocked，又失效了码

**Comment by 1264967889** [comment]
你是不是发错了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Evil0ctal/Douyin_TikTok_Download_API"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月27日(星期一) 下午4:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Evil0ctal/Douyin_TikTok_Download_API] [ 重要通知 ] 有关抖音接口返回内容为空的问题 (Issue #135)





 
您好，这几天我使用v1接口，返回的数据是：blocked，又失效了码

**Comment by Evil0ctal** [comment]
你的IP被抖音拉黑了，尝试用代理重新获取。

**Comment by darksunnydong** [comment]
大佬，又不能用了，更新一下啊

**Comment by Evil0ctal** [comment]
暂时修复了！

**Comment by Ven-CN** [comment]
大佬可以一起合作吗，我这边需求服务端的解析，有变现路径

**Comment by darksunnydong** [comment]
可以的
&nbsp;


Dark&nbsp;Sunny
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月22日(星期三) 下午3:19
收件人: ***@***.***&gt;; 
抄送: "Dark ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Evil0ctal/Douyin_TikTok_Download_API] [ 重要通知 ] 有关抖音接口返回内容为空的问题 (Issue #135)





 
大佬可以一起合作吗，我这边需求服务端的解析，有变现路径

**Comment by Ven-CN** [comment]
> 可以的 &nbsp; Dark&nbsp;Sunny ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年3月22日(星期三) 下午3:19 收件人: ***@***.***&gt;; 抄送: "Dark ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Evil0ctal/Douyin_TikTok_Download_API] [ 重要通知 ] 有关抖音接口返回内容为空的问题 (Issue #135) 大佬可以一起合作吗，我这边需求服务端的解析，有变现路径 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

为什么回复的是邮件

**Comment by darksunnydong** [comment]
你们的变现方式具体是什么样的&nbsp;


Dark&nbsp;Sunny
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月22日(星期三) 下午3:32
收件人: ***@***.***&gt;; 
抄送: "Dark ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Evil0ctal/Douyin_TikTok_Download_API] [ 重要通知 ] 有关抖音接口返回内容为空的问题 (Issue #135)





  
可以的 &nbsp; Dark&nbsp;Sunny @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年3月22日(星期三) 下午3:19 收件人: @.&gt;; 抄送: "Dark @.&gt;; @.&gt;; 主题: Re: [Evil0ctal/Douyin_TikTok_Download_API] [ 重要通知 ] 有关抖音接口返回内容为空的问题 (Issue #135) 大佬可以一起合作吗，我这边需求服务端的解析，有变现路径 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
为什么回复的是邮件

**Comment by 1735771081** [comment]
作者你好，我第一次使用 旧API 这个接口能返回数据，第二次就返回空了,使用  新API 返回blocked，请问这是什么原因呢？

**Comment by Evil0ctal** [comment]
你好，旧的API已经放弃维护了，请使用最新的代码。

**Comment by LcmBlog** [comment]
使用 新API 返回blocked，请问这是什么原因呢？
