### ISSUE TITLE
网页视频提交出错

### ISSUE THREAD

**Issue by yfchen97** [Evil0ctal/Douyin_TikTok_Download_API#136]
[***发生错误的平台？***

如：抖音/TikTok

***发生错误的端点？***

如：API-V1/API-V2/Web APP

***提交的输入值？***

如：短视频链接

***是否有再次尝试？***

如：是，发生错误后X时间后错误依旧存在。

***你有查看本项目的自述文件或接口文档吗？***

如：有，并且很确定该问题是程序导致的。
https://www.douyin.com/user/MS4wLjABAAAA65JwHUdlT3-RWFxWsir_wQ-SfGKbA8NDUSSnNfT9M_c?modal_id=7184348310482799872

**Comment by Evil0ctal** [comment]
你好，该链接为主页链接，请使用[api.TikHub.io](https://api.tikhub.io/docs#/)进行解析。
