### ISSUE TITLE
Request limit

### ISSUE THREAD

**Issue by libea18** [Evil0ctal/Douyin_TikTok_Download_API#138]
Do we have an Request limit?
If we have 10,000 users per day and 500 video requests per minute
Aren't we faced with the request limit?

**Comment by Evil0ctal** [comment]
Which API service are you talking about?

api.douyin.wtf or api.tikhub.io

**Comment by libea18** [comment]
douyin

**Comment by Evil0ctal** [comment]
You can deploy this project on your own server and changed the request limit by editing the config.ini

**Comment by libea18** [comment]
I found https://github.com/krypton-byte/tiktok-downloader when I realized I might hit a request limit and have to use a proxy server.
On what basis does your project receive videos from TikTok?
We don't face restrictions from Tik Tok for the high requests from a server?

**Comment by Evil0ctal** [comment]
The answer for Douyin is yes, you will need to use proxy to bypass their limit.

You can read the source code of scraper.py for the API base on.

**Comment by libea18** [comment]
you got video directly from tiktok (cdn and .. ) or use other site like [krypton-byte/tiktok-downloader](https://github.com/krypton-byte/tiktok-downloader) ?

**Comment by Evil0ctal** [comment]
This is the official API from TikTok. For the request limit, I recommend you deploy the source code to your own server.

**Comment by libea18** [comment]
I deployed on the server
My question is, doesn't tiktok limit my ip server?
Because I have 10,000 users a day who may send requests.
Does the request go to Tik Tok from my Ip server side or Ip client side?

**Comment by Evil0ctal** [comment]
Currently all of your user's requests are going to send by your server IP, and TikTok may will block your server IP, depends on their WAF rules. All the details you can read the source code to have an answer.

**Comment by libea18** [comment]
Can you estimate the amount of traffic for each request?
I want to buy proxy that has traffic limit
Now I have a question that a request that comes from the user to the server and from the server to Tik Tok and to the client:
How much traffic is consumed?

**Comment by libea18** [comment]
and another question
i run script in my server 
web app 195.154.55.197:90
web api 195.154.55.197:99
limit request set at 2/min
but not effect. check and send request.

and download link in ( Video Download-Watermark ) is https://api.douyin.wtf/download?url=... 
Is this not a bug?
Shouldn't it be my server instead of yours?

**Comment by Evil0ctal** [comment]
You can change the default API domain in config.ini file.

The requests limit only work if the client IP are the same.

Example:

http://195.154.55.197:99/api?url=https%3A%2F%2Fwww.douyin.com%2Fvideo%2F7153585499477757192&minimal=true
