### ISSUE TITLE
tiktok

### ISSUE THREAD

**Issue by pengneal** [Evil0ctal/Douyin_TikTok_Download_API#14]
国内解析没问题。
tiktok就不成功一个。
web端直接百分百不动了。
api无反应。
不知道，是否又更新了。。。。

**Comment by Evil0ctal** [comment]
> 国内解析没问题。
> 
> tiktok就不成功一个。
> 
> web端直接百分百不动了。
> 
> api无反应。
> 
> 不知道，是否又更新了。。。。

api工作正常，web端今天修改了批量下载的代码，应该是CPU跑满程序崩了，晚点我去恢复服务。

**Comment by pengneal** [comment]
测试了您的接口确实没问题，
但是我本地部署提交后确实没有反应，我部署到国外服务器的。
没有用宝塔。

**Comment by pengneal** [comment]
ubuntu 安装了py3.8 运行没有报错。 pip3 也更新了。

**Comment by pengneal** [comment]
还有个问题，为啥页面打开后，什么都没做 一直在发请求？http://****:5000/?app=index

**Comment by Evil0ctal** [comment]
> 还有个问题，为啥页面打开后，什么都没做 一直在发请求？http://****:5000/?app=index

检查一下控制台有没有报错，`http://****:5000/?app=index`这个请求是因为你在与该页面建立链接，前面可以看到你的IP地址，然后请问你部署在哪个国家的服务器上了。

**Comment by pengneal** [comment]
部署在韩国，我调试了一下，发现是在 Web/scraper.py 文件281行：            html = requests.get(url=original_url, headers=tiktok_headers)
这一个请求一直无响应，导致的。

**Comment by pengneal** [comment]
我用的 就是您给的例子测试的，tiktok。

https://www.tiktok.com/@tvamii/video/7045537727743380782

**Comment by Evil0ctal** [comment]
> 我用的 就是您给的例子测试的，tiktok。
> 
> https://www.tiktok.com/@tvamii/video/7045537727743380782

tiktok可能对韩国的请求进行了限制，之前有一个issues是香港的vps也不行，你试一下美国的vps试试。
