### ISSUE TITLE
获取用户的粉丝数等数据

### ISSUE THREAD

**Issue by ludasky** [Evil0ctal/Douyin_TikTok_Download_API#141]
期望提供一个获取用户的粉丝数等数据的接口，谢谢大佬
<img width="499" alt="image" src="https://user-images.githubusercontent.com/16174533/211499289-88218d27-b738-449f-957c-39ea9436c617.png">

**Comment by Evil0ctal** [comment]
可以使用TikHub的API实现。

**Comment by ludasky** [comment]
> 可以使用TikHub的API实现。

返回的值都是0，"following_count": 0,
                "follower_count": 0,

**Comment by Evil0ctal** [comment]
方便提供一个URL链接吗？我去复现一下问题。

**Comment by ludasky** [comment]
> 方便提供一个URL链接吗？我去复现一下问题。

https://api.tikhub.io/tiktok_video_data?tiktok_video_url=https://www.tiktok.com/@cristofor.13/video/7188159591299992837
