### ISSUE TITLE
请问可否出一个相对简单的使用教程？

### ISSUE THREAD

**Issue by chenkongming** [Evil0ctal/Douyin_TikTok_Download_API#143]

**Comment by Evil0ctal** [comment]
请问指的是哪方面的简单呢？

**Comment by nevertoday** [comment]
我也想要简单一点的， 就是如何部署更细节一点， pip 方案可以用在终端中，更简单直白一点的方案， 小白友好...

**Comment by PennyJoly** [comment]
同求

**Comment by Evil0ctal** [comment]
【【开源项目教程】教你一分钟内部署属于你自己的抖音和TikTok数据接口，可以下载视频，做数据分析等。-哔哩哔哩】 https://b23.tv/MTGT71Z
