### ISSUE TITLE
video comments

### ISSUE THREAD

**Issue by shreateh** [Evil0ctal/Douyin_TikTok_Download_API#145]
Hello, 
thanks for this amazing API, its a huge work that you offer it for tiktok community 
my request is there is a way to get video comments? 
thank you

**Comment by Evil0ctal** [comment]
Please check out this link:

https://api.tikhub.io/docs#/TikTok/get_tiktok_video_comments_tiktok_video_comments__get

**Comment by shreateh** [comment]
love this , many thanks <3
