### ISSUE TITLE
[BUG] docker版本无法使用

### ISSUE THREAD

**Issue by YanamiNeko** [Evil0ctal/Douyin_TikTok_Download_API#148]
***发生错误的平台？***

抖音

***发生错误的端点？***

Web APP

***提交的输入值？***

[6914948781100338440](https://www.douyin.com/video/6914948781100338440)

***是否有再次尝试？***

是

***你有查看本项目的自述文件或接口文档吗？***

有

![image](https://user-images.githubusercontent.com/63277113/216773954-daedb9db-2072-43ca-b976-4d4e4b0fdf92.png)

**Comment by Evil0ctal** [comment]
API依旧可用，看起来是你的IP被抖音拉黑了，或者是视频被删除了。
