### ISSUE TITLE
douyin 个人页链接失效

### ISSUE THREAD

**Issue by lionzheng** [Evil0ctal/Douyin_TikTok_Download_API#149]
***发生错误的平台？***

如：抖音

***发生错误的端点？***

如：API-V2

***提交的输入值？***

如：个人页链接

***是否有再次尝试？***

如：是，2023-2-7开始失效

***你有查看本项目的自述文件或接口文档吗？***

如：有

现在V1个人页接口（https://www.iesdouyin.com/aweme/v1/web/aweme/post/）失效了，有其他方法获取么？

**Comment by shawn35** [comment]
hope this can be fix soon. i'm having same issue. Thanks for your help

**Comment by lionzheng** [comment]
> hope this can be fix soon. i'm having same issue. Thanks for your help

I hope too~

**Comment by Evil0ctal** [comment]
Will be fix in few days.

**Comment by Evil0ctal** [comment]
已经修复了

**Comment by VisualSinger** [comment]
> 已经修复了

需要重新安装吗？貌似接口文档打不开了

**Comment by Evil0ctal** [comment]
Docs：

api.tikhub.io

**Comment by panusocom** [comment]
> 已经修复了

这个接口还是不能访问，是我的IP被抖音拉黑了吗？
www.iesdouyin.com/aweme/v1/web/aweme/post/?sec_user_id=

**Comment by Evil0ctal** [comment]
请大家用api.tikhub.io的接口，目前还是免费的。
