### ISSUE TITLE
      html = requests.get(url=original_url, headers=tiktok_headers) 报错 Object of type SSLError is not JSON serializable

### ISSUE THREAD

**Issue by qqiuqingx** [Evil0ctal/Douyin_TikTok_Download_API#15]
http://127.0.0.1:2333/api?url=https://www.tiktok.com/@gabyluvsskz_/video/7075120105608203563?is_from_webapp=1&sender_device=pc  调用API的时候scraper.py 报的错误 请问是我操作的问题还是怎么回事啊

**Comment by Evil0ctal** [comment]
> http://127.0.0.1:2333/api?url=https://www.tiktok.com/@gabyluvsskz_/video/7075120105608203563?is_from_webapp=1&sender_device=pc 调用API的时候scraper.py 报的错误 请问是我操作的问题还是怎么回事啊

请问提交其不同的值也是一样报错吗？这个问题目前我没遇到过，应该是与Flask相关的问题。

**Comment by qqiuqingx** [comment]
用抖音的链接也报错,把 urllib3版本降到1.25.11就可以了  不知道是不是这个原因

**Comment by Evil0ctal** [comment]
> 用抖音的链接也报错,把 urllib3版本降到1.25.11就可以了 不知道是不是这个原因

可能是，我现在去修改一下`requirements.txt`，感谢你的反馈。

**Comment by pengneal** [comment]
看样子 我也是这个问题。

**Comment by Evil0ctal** [comment]
> 看样子 我也是这个问题。

GitHub的机器人说老版本的urllib有安全问题，我明天去试一下看看旧版本的哪个版本可以正常使用。

**Comment by Evil0ctal** [comment]
> 用抖音的链接也报错,把 urllib3版本降到1.25.11就可以了 不知道是不是这个原因

你好，今天测试了urllib3(1.26.9)，没有遇到这个问题，`requirements.txt`内的package都经过测试并且没有问题了。
