### ISSUE TITLE
CloudFlare?

### ISSUE THREAD

**Issue by skintclover** [Evil0ctal/Douyin_TikTok_Download_API#150]
I have problem with your api on my project
My project use axios to get tiktok video but not work
It say.

[AxiosError: Request failed with status code 403] {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function] },
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.27.2'
    },
    method: 'get',
    url: 'https://api.douyin.wtf/download?url=https://vt.tiktok.com/ZS8fSpppD/&prefix=True&watermark=False',
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'api.douyin.wtf',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.douyin.wtf',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 3158,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'GET /download?url=https://vt.tiktok.com/ZS8fSpppD/&prefix=True&watermark=False HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'User-Agent: axios/0.27.2\r\n' +
      'Host: api.douyin.wtf\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 3,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/download?url=https://vt.tiktok.com/ZS8fSpppD/&prefix=True&watermark=False',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 403,
      statusMessage: 'Forbidden',
      client: [TLSSocket],
      _consuming: true,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://api.douyin.wtf/download?url=https://vt.tiktok.com/ZS8fSpppD/&prefix=True&watermark=False',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'api.douyin.wtf',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://api.douyin.wtf/download?url=https://vt.tiktok.com/ZS8fSpppD/&prefix=True&watermark=False',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'user-agent': [Array],
      host: [Array]
    }
  },
  response: {
    status: 403,
    statusText: 'Forbidden',
    headers: {
      date: 'Tue, 07 Feb 2023 15:16:05 GMT',
      'content-type': 'text/html; charset=UTF-8',
      'transfer-encoding': 'chunked',
      connection: 'close',
      'permissions-policy': 'accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),fullscreen=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()',
      'referrer-policy': 'same-origin',
      'x-frame-options': 'SAMEORIGIN',
      'cache-control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
      expires: 'Thu, 01 Jan 1970 00:00:01 GMT',
      'report-to': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=yLaHhLajFgCCrhXJAidnmq0RTxkNFWDBkKwcMLsg0bVhkHIDwYE8KKYa%2F%2FXry06%2BThHD3k62jcI6OBHUTUtBzQiZiME5rrPdU7oFXSZYC3LfHjeD4EDE2arW7KsThh7E%2Bw%3D%3D"}],"group":"cf-nel","max_age":604800}',
      nel: '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}',
      'strict-transport-security': 'max-age=15552000; includeSubDomains',
      'x-content-type-options': 'nosniff',
      server: 'cloudflare',
      'cf-ray': '795d15adbe9dc376-SEA',
      'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'
    },
    config: {
      transitional: [Object],
      adapter: [Function: httpAdapter],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object],
      method: 'get',
      url: 'https://api.douyin.wtf/download?url=https://vt.tiktok.com/ZS8fSpppD/&prefix=True&watermark=False',
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'GET /download?url=https://vt.tiktok.com/ZS8fSpppD/&prefix=True&watermark=False HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.27.2\r\n' +
        'Host: api.douyin.wtf\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/download?url=https://vt.tiktok.com/ZS8fSpppD/&prefix=True&watermark=False',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.douyin.wtf',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: '<!DOCTYPE html>\n' +
      '<html lang="en-US">\n' +
      '<head>\n' +
      '    <title>Just a moment...</title>\n' +
      '    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\n' +
      '    <meta http-equiv="X-UA-Compatible" content="IE=Edge">\n' +
      '    <meta name="robots" content="noindex,nofollow">\n' +
      '    <meta name="viewport" content="width=device-width,initial-scale=1">\n' +
      '    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">\n' +
      '    \n' +
      '\n' +
      '</head>\n' +
      '<body class="no-js">\n' +
      '    <div class="main-wrapper" role="main">\n' +
      '    <div class="main-content">\n' +
      '        <h1 class="zone-name-title h1">\n' +
      '            <img class="heading-favicon" src="/favicon.ico" alt="Icon for api.douyin.wtf"\n' +
      '                 onerror="this.onerror=null;this.parentNode.removeChild(this)">\n' +
      '            api.douyin.wtf\n' +
      '        </h1>\n' +
      '        <h2 class="h2" id="challenge-running">\n' +
      '            Checking if the site connection is secure\n' +
      '        </h2>\n' +
      '        <noscript>\n' +
      '            <div id="challenge-error-title">\n' +
      '                <div class="h2">\n' +
      '                    <span class="icon-wrapper">\n' +
      '                        <div class="heading-icon warning-icon"></div>\n' +
      '                    </span>\n' +
      '                    <span id="challenge-error-text">\n' +
      '                        Enable JavaScript and cookies to continue\n' +
      '                    </span>\n' +
      '                </div>\n' +
      '            </div>\n' +
      '        </noscript>\n' +
      `        <div id="trk_jschal_js" style="display:none;background-image:url('/cdn-cgi/images/trace/managed/nojs/transparent.gif?ray=795d15adbe9dc376')"></div>\n` +
      '        <div id="challenge-body-text" class="core-msg spacer">\n' +
      '            api.douyin.wtf needs to review the security of your connection before proceeding.\n' +
      '        </div>\n' +
      '        <form id="challenge-form" action="/download?url=https://vt.tiktok.com/ZS8fSpppD/&amp;prefix=True&amp;watermark=False&amp;__cf_chl_f_tk=dUVHOkkC1sGWobjVKFzoVVCag5H0M_BS.ZcGIBMEIVs-1675782965-0-gaNycGzNCWU" method="POST" enctype="application/x-www-form-urlencoded">\n' +
      '            <input type="hidden" name="md" value="YpvTcJd9Zhn_2k8wQwRvaVADSaC3XW7JP07rmeJf0ZA-1675782965-0-AdG34t7qB8V3NdGi1SAT6cil2uIx7GVfz7hUJPyyT5HAc93yRT2rXMgi_n5FZ8MpBZpk991QokN2vz7q9BHLwUSAUc_r-T8ViaPSc06q0tzzHEhESJwlz1lWLtjRkgpUKuZDs8sVHh2HuzFH0k4_np3BfK0zDmLK9AyTIMM_6KukfsPzZFg5fLdXc4MfgNGNGSMENATWf31lo7smtWiE2CN8AJWJQgh3Nkg3xr1R9dnprFh7pF0DV5Nn02oLwinCI9OyN6N9vySD7qIjPnVdxSyYehWKRAX7Z6Ya8CF8cNmCI3vkpMEpDKsQvQrt06wH4ZbcFgqNK_Wtha6UCk_54_mnOg1aBfLTklvGC63IbnCg8aWJYYDhlu12XrxGg8SW-gG5MCUBNKkrK8z4UQMnowEsOhnM-eNZABi5IelkueNtRNIUGoVL3KDMEg1waJHyVGV98gR0wNelX1Yj6UPPRPifKk6hCcknhRz6zq2WsL-IJNwt4QY6LfVXD7UxcVfwDSKLRUlr3Awi3bE9EbKwOgNwqhWOjizKDI9WJC2RpYcSl4dxuxLYDXlK31X1k2Ay4c3Y1Sedx0Uhe8ahyyr9uZ_IAYly-q2N0n8O2DWKqdNoBcizeu3a_pxCKAI8S4RCLg1j2zPIyJWl4mb4_H31klBoMeyWUqcmFVeIc_bVSTQ98GlqA_tvFygmkGo7rvSspYxL46cNsYNNIiF7QVG-D3g_WjUrUMvi2kg-UyXSP_Ymln7YMstleKSNJYdrdskslOiBS_YfrOyghKGIFJP--2172jUChCCX4xL9mfcJuTxL_qszNbb5UQ1rVpJfqoeqQ8JZcCcELv_iUZn5A0W56op4XgPFonxaN1gqz3-gCa9ZEvBe27fMYT40s7XaCYqEGvgftsZBc01BuVHdLtvf6cAYfsE2uyXeAItuQjXnCYtuM6RPzsmJdElCbR7ccFh6SkSP7wQa9mz0Z2ZjWvFhgdGGzM7O-EI0mV3qPPcqH-kaWz-SmSl47GkC2Ce3NfKP1JwSa2L3RWG-ISEliKbZocNfjnlIXwgIsZagMjqDBaSPcda6vA1uJJOZXq12FfTHIeVGQGVf6Aa5Lgf4zzKWpetvjKuNZdH48z7AKIMwYi3eMGAmF8W6NCUfkbn4e-24t5fleI-w4YL07wf5VPFqpDLopfWEDDxfHFu7RLqmjMoZRRwmO2w8_PnMFhK8CnnEEsEj7C7hv1g-6Lnlnxwy_EHNDZxa44VS-SDcREBNIyLoEfKM_tGLTHBYMe56TG3R3UHUb7LPfSZf4WNjC9EsWqlGy5VDta9ZtTN8gnpYpNcruGpMyR7w7Dri7_ZW_tjsgmopY3PeAH0s8h850XxnAUcxW2pyFT96Sr_VLUEGKE0zcP9c1axB1Scvxoaxk3qI618vVcp8OYNFuNZTHalWP6obLaIC1twf9PERrbzjBZoR1cR3bUQwskZPx9pG5jieM9Jbyuir2QvM2Crgv9U5fzq3et898gaKxv7w1R5BRE3q8XA5DELrj4alwpFtBy7pJ-scNGHHFnfEPL1QQ1QqYTsTKORH0EbC_Y6ovbtyDaJV2AJ0RjFJo0kiymzYhaA-tdmgJqyxLdG7kBJRm18IYXwvNCXJVsGgLYOfmL1Z1SO4WuaCtvNMvdqjiLwvp_Qi_caEZTfs75jEJe3xVLSC_Rv5-fSvn2PpMV_X_2BgrQTmd9r0mYh6WK_-pB7Hx9Zfk8qGNQbDte9dMnPV1lb1oQK23ufmJfVQB5eb5zc_XRkNY_ohKVxuSaGQ32fJyVjhXYt8mPv4Vawv31W7q1o1upSM50Gww9pSVeRfdZhZMUa71FdNAQkfjTyUift-jPBufM7JU7hRqg1NKFLgy3V8gb6bSfp5E5rQzdgHh40RGuHD-mRrCP4qoymcMG0xm9MU9c5hP_vXuXnK2RTcAYcOqkbDKHq8XjMUFsaLmkcNouKS1XVHIpyi8sJ6SsDgJ3lRUaDqVNfPmWFhdzXuIGb6lhMPMtrQ_ZyJWsI7U799b_CIflgUSPHj5zS5wDZ0zBSZfrouCzElmlYRTxJ75uC_Us4s2NTg3f7G-zhdEEi00fctgtYgT_zFgcmajW0-GrOsqo_v0arePXYBkpV72SbO2vVafe4tPz9uS0NJ3oKQU0Gv6Fq_9zlMl1ZzdYkMD7tgzXDb7ihchpcfnQfqBOHVn5tkpBxGN3huduJd6vsLLZEU0NXnnBHvAKNS_E5GWcydksTvt4Qb0a4UKg_WqIhhyg5AlImA-JFdDMHbjfUyJgvL7ez5_taSRlaz48Oc-TOjefByUcTlwZj1KxjENyVmhEq_m5TskRbnD6LSwOuYUuPK">\n' +
      '        </form>\n' +
      '    </div>\n' +
      '</div>\n' +
      '<script>\n' +
      '    (function(){\n' +
      '        window._cf_chl_opt={\n' +
      "            cvId: '2',\n" +
      "            cZone: 'api.douyin.wtf',\n" +
      "            cType: 'managed',\n" +
      "            cNounce: '21288',\n" +
      "            cRay: '795d15adbe9dc376',\n" +
      "            cHash: 'ee1809a92f206b9',\n" +
      '            cUPMDTk: "\\/download?url=https:\\/\\/vt.tiktok.com\\/ZS8fSpppD\\/&prefix=True&watermark=False&__cf_chl_tk=dUVHOkkC1sGWobjVKFzoVVCag5H0M_BS.ZcGIBMEIVs-1675782965-0-gaNycGzNCWU",\n' +
      "            cFPWv: 'g',\n" +
      "            cTTimeMs: '1000',\n" +
      "            cMTimeMs: '0',\n" +
      '            cTplV: 4,\n' +
      "            cTplB: 'cf',\n" +
      '            cRq: {\n' +
      "                ru: 'aHR0cHM6Ly9hcGkuZG91eWluLnd0Zi9kb3dubG9hZD91cmw9aHR0cHM6Ly92dC50aWt0b2suY29tL1pTOGZTcHBwRC8mcHJlZml4PVRydWUmd2F0ZXJtYXJrPUZhbHNl',\n" +
      "                ra: 'YXhpb3MvMC4yNy4y',\n" +
      "                rm: 'R0VU',\n" +
      "                d: 'XxqUEwc1X0bdnv16vaaBcyGhlKCNv7JOsQEp4qWLlxcfoYOdFZ/KxUD+mLuI4TOWoTkZ1q+RYCkl5s/a//SMSgsRBbEHXSSOzgj0MRUIpXogU54vTHPW53AB3Z5jncwxaoaq2FYpYeaDEVvnLi4j0dVKEqgQzXxIwkz6clNNLcBnsQlRbhNnHqbR1HdTV00zAH0GDF1sLi/X5JhPl05Kiy1zKxs4I8J7orb7FElQ3t/KtY5ob47I/LTYErNf/Uf1nUwa/4W7gfRI0qqGV0AVwXYXkIgfnlKN78HdPv97zb2oVDgY6uE08XFnYpfk7FJqE61FeMcaBwcRqi8do1dr5GofIfEVdjCZ9io4n1PilRaF09Il3QQjt+FTGPZMEQhIG1yiY2/y8LJ3jle2WfxDA0iYE1szzaxmJrg5DMOZuIlDDEwhKIjeBc99nhcZr462LTyyivNv/4METlsCrEHeiBDW5HHHWGogXcn28PMP4uhc9ofs4TdtlPf3AE+uLSRH7iHbOjxeY0EtIkS3p63Hx6HmMpkDWZE36OZE5yNi7WBBRsI01em2qJa39WXSVWKZrPmHDUNnZN/gZxiV1eXYAPLk0S5OIuYdJN0N2BbjP+oZp1yqt+Nz2YunJ12wDJdkvwQ6ktWEVBolk1juDLVYlc5Zj6QWbG9luWbGLHx7n+EJXncUs3ruN+LhO2bd3kMq',\n" +
      "                t: 'MTY3NTc4Mjk2NS4zOTEwMDA=',\n" +
      "                m: 'cFCi1nzL+tebXtRfvWQZDzduiEe2+FyjdiF/9zVsfxY=',\n" +
      "                i1: 'oxzCDlLomgEDXij9he9aQQ==',\n" +
      "                i2: 'xu/CzY4tB79/4C157/pokQ==',\n" +
      "                zh: 'u2cpszwQ8HL2ntWh08B3bRouk5CBfzCiRyrqPmAlr28=',\n" +
      "                uh: 'WIFn/maPG6jYGG12dVce7eo0wyX7m2D8aR+58ajaP8Y=',\n" +
      "                hh: '05COndHv534w+iWqeMPE/ZwfTUtNS5EgzSRf/m5ytFQ=',\n" +
      '            }\n' +
      '        };\n' +
      "        var trkjs = document.createElement('img');\n" +
      "        trkjs.setAttribute('src', '/cdn-cgi/images/trace/managed/js/transparent.gif?ray=795d15adbe9dc376');\n" +
      "        trkjs.setAttribute('alt', '');\n" +
      "        trkjs.setAttribute('style', 'display: none');\n" +
      '        document.body.appendChild(trkjs);\n' +
      "        var cpo = document.createElement('script');\n" +
      "        cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/managed/v1?ray=795d15adbe9dc376';\n" +
      "        window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;\n" +
      "        window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;\n" +
      '        if (window.history && window.history.replaceState) {\n' +
      '            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;\n' +
      '            history.replaceState(null, null, "\\/download?url=https:\\/\\/vt.tiktok.com\\/ZS8fSpppD\\/&prefix=True&watermark=False&__cf_chl_rt_tk=dUVHOkkC1sGWobjVKFzoVVCag5H0M_BS.ZcGIBMEIVs-1675782965-0-gaNycGzNCWU" + window._cf_chl_opt.cOgUHash);\n' +
      '            cpo.onload = function() {\n' +
      '                history.replaceState(null, null, ogU);\n' +
      '            };\n' +
      '        }\n' +
      "        document.getElementsByTagName('head')[0].appendChild(cpo);\n" +
      '    }());\n' +
      '</script>\n' +
      '\n' +
      '\n' +
      '    <div class="footer" role="contentinfo">\n' +
      '        <div class="footer-inner">\n' +
      '            <div class="clearfix diagnostic-wrapper">\n' +
      '                <div class="ray-id">Ray ID: <code>795d15adbe9dc376</code></div>\n' +
      '            </div>\n' +
      '            <div class="text-center" id="footer-text">Performance &amp; security by <a rel="noopener noreferrer" href="https://www.cloudflare.com?utm_source=challenge&utm_campaign=m" target="_blank">Cloudflare</a></div>\n' +
      '        </div>\n' +
      '    </div>\n' +
      '</body>\n' +
      '</html>\n'
  }
}

I think they have blocked by cloudflare uam make my project not working
Can you remove or make they another way to get tiktok video?
I you can thank you very much !!!

**Comment by Evil0ctal** [comment]
Please get the video file by using the link in API response, if you send too many requests in this endpoint will take down the server.
