### ISSUE TITLE
下载视频会被定向到douyin.wtf上

### ISSUE THREAD

**Issue by c-or** [Evil0ctal/Douyin_TikTok_Download_API#151]
使用docker将项目部署到自己服务器后使用下载功能会被定向到douyin.wtf而不是部署服务器本身，如果手动将douyin.wtf替换为部署服务器地址则可正常下载

***发生错误的平台？***
TikTok
如：抖音/TikTok

***发生错误的端点？***
Web APP
如：API-V1/API-V2/Web APP

***提交的输入值？***
https://www.douyin.com/discover?modal_id=7069543727328398622
如：短视频链接

***是否有再次尝试？***
是
如：是，发生错误后X时间后错误依旧存在。

***你有查看本项目的自述文件或接口文档吗？***
有，并且很确定该问题是程序导致的
如：有，并且很确定该问题是程序导致的。

**Comment by VankPL** [comment]
Hi sir
Why i cant download it from shortcut 
![Uploading 217564319...]

**Comment by c-or** [comment]
抱歉，是我的问题，配置文件没配好
