### ISSUE TITLE
能增加对app或网页直播地址能解析吗

### ISSUE THREAD

**Issue by HeroPoter** [Evil0ctal/Douyin_TikTok_Download_API#153]
直播分享链接
网页 https://live.douyin.com/80017709309
app https://v.douyin.com/BxAh8gC/

这些能解析到m3u8或flv直播流吗

**Comment by lanyuer** [comment]
+1

**Comment by lanyuer** [comment]
直播链接报错：

当前链接平台为:douyin
正在获取视频ID...
该链接为原始链接,无需转换,原始链接为: https://live.douyin.com/824751466605
获取到的抖音直播ID为: 824751466605
获取视频ID成功,视频ID为:824751466605
正在获取视频数据...
正在获取抖音视频数据...
正在获取视频数据API: https://www.iesdouyin.com/aweme/v1/web/aweme/detail/?aweme_id=824751466605&aid=1128&version_name=23.5.0&device_platform=android&os_version=2333&Github=Evil0ctal&words=FXXK_U_ByteDance
获取抖音视频数据失败！原因:0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://www.iesdouyin.com/aweme/v1/web/aweme/detail/?aweme_id=824751466605&aid=1128&version_name=23.5.0&device_platform=android&os_version=2333&Github=Evil0ctal&words=FXXK_U_ByteDance')
[抖音|TikTok方法]返回数据为空，无法处理！
2023-02-16 09:04:15: 正在记录错误信息...

**Comment by Evil0ctal** [comment]
此接口无法解析直播数据。
