### ISSUE TITLE
[Feature request] 访问频繁403的问题

### ISSUE THREAD

**Issue by jw-star** [Evil0ctal/Douyin_TikTok_Download_API#157]
**您的功能请求是否与问题相关？ 如有，请描述。**

最近发现访问抖音api太频繁403错误，有思路吗，代理ip似乎作用不大

**Comment by jw-star** [comment]
连续 解析3个之后，就会遇到403了

**Comment by jw-star** [comment]
@retry(stop=stop_after_attempt(4), wait=wait_fixed(7))

经过测试，改为这个参数正好

**Comment by Evil0ctal** [comment]
好的 我晚点就行修改。
