### ISSUE TITLE
/detail/?aweme_id= 限制ip

### ISSUE THREAD

**Issue by 5wcx** [Evil0ctal/Douyin_TikTok_Download_API#159]
https://www.iesdouyin.com/aweme/v1/web/aweme/detail/?aweme_id=
这个接口会限制ip   请求多了  就一直返回为空了   请问老哥有啥好办法吗？

**Comment by Evil0ctal** [comment]
使用代理池。

**Comment by kkkkkk-10086** [comment]
我直接一直请求，直到返回有用数据才停，半个月了一直如此，就是有时候可能会请求十几次才有结果

**Comment by Evil0ctal** [comment]
这也是一种办法，但是可能会被拉黑IP。

**Comment by Evil0ctal** [comment]
暂时修复了
