### ISSUE TITLE
感谢作者开源，提一个小建议

### ISSUE THREAD

**Issue by moo611** [Evil0ctal/Douyin_TikTok_Download_API#162]
（1）建议模仿国外半开源付费项目，自建一个网站，行程界面化管理，包括各种套餐价格，以及我购买的套餐还剩多少点数，或者订阅什么时候到期，每天用量多少一目了然。
例子：https://scrape.do/，https://lamadava.com/
（2）建议明确购买方式，特别是文档里面有个https://tikhub.io/，我以为这个是你的网站，结果点进去，貌似和这个库没什么关系，是一个帮我建造网站的网站？其实我觉得没必要链这么多地方，只要链一个上面的那种自建网站就够了。
开源不易，感谢作者的无私奉献。希望作者能越办越好。

**Comment by Evil0ctal** [comment]
感谢你的建议，目前那个网站即将被废弃，目前正在准备实现半开源半商业化的模式。

我们很快会完成首页的编写。
