### ISSUE TITLE
发现一个挺搞笑的东西

### ISSUE THREAD

**Issue by xyfacai** [Evil0ctal/Douyin_TikTok_Download_API#164]
words=FXXK_U_ByteDance

 # 从安卓apk中提取到的新API，目前可用，支持视频，图集，笔记的解析(2022年12月25日)
api_url = f"https://www.iesdouyin.com/aweme/v1/web/aweme/detail/?aweme_id={video_id}&aid=1128&version_name=23.5.0&device_platform=android&os_version=2333&Github=Evil0ctal&words=FXXK_U_ByteDance"

**Comment by Evil0ctal** [comment]
![-_-](https://github.com/Evil0ctal/Evil0ctal/blob/main/images/006qOO1Xly1gxv1zgfh07g30jj0jvaec.gif?raw=true)
