### ISSUE TITLE
[BUG] Tiktok接口是挂了吗？

### ISSUE THREAD

**Issue by juedi998** [Evil0ctal/Douyin_TikTok_Download_API#166]
最近发现接口频繁返回：{"status_code":0,"status_msg":"","block_code":2018}，貌似现在强制性需要提供X-Argus、X-Ladon两个算参数才能返回了，但我发现douyin.wtf的接口是可以正常拿到数据的，有点疑惑，难道是因为ip的问题？

**Comment by Evil0ctal** [comment]
依旧可用，可能是你请求太频繁了。

**Comment by juedi998** [comment]
> 依旧可用，可能是你请求太频繁了。

好吧，但是我切换了代理也是得到一样的结果，域名也换了几个了，就是很奇怪

**Comment by Evil0ctal** [comment]
TikTok在某些国家不可用，用美国的代理试一下。

**Comment by juedi998** [comment]
> TikTok在某些国家不可用，用美国的代理试一下。

的确可以了，感谢老哥！

**Comment by Evil0ctal** [comment]
不客气
