### ISSUE TITLE
使用1.2.0，获取抖音视频数据失败

### ISSUE THREAD

**Issue by Cestb0n** [Evil0ctal/Douyin_TikTok_Download_API#167]
正在获取抖音视频数据...
生成的X-Bogus签名为: DFSzswSLjsxANJ96taHVaU9WcBnW
正在获取视频数据API: https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=webapp&aid=6383&channel=channel_pc_web&aweme_id=7207983870262791483&pc_client_type=1&version_code=190500&version_name=19.5.0&cookie_enabled=true&screen_width=1344&screen_height=756&browser_language=zh-CN&browser_platform=Win32&browser_name=Evil0ctal&browser_version=110.0&browser_online=true&engine_name=Gecko&engine_version=109.0&os_name=Windows&os_version=10&cpu_core_num=128&device_memory=2333&platform=PC&webid=7158288523463362079&X-Bogus=DFSzswSLjsxANJ96taHVaU9WcBnW
获取抖音视频数据失败！原因:0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=webapp&aid=6383&channel=channel_pc_web&aweme_id=7207983870262791483&pc_client_type=1&version_code=190500&version_name=19.5.0&cookie_enabled=true&screen_width=1344&screen_height=756&browser_language=zh-CN&browser_platform=Win32&browser_name=Evil0ctal&browser_version=110.0&browser_online=true&engine_name=Gecko&engine_version=109.0&os_name=Windows&os_version=10&cpu_core_num=128&device_memory=2333&platform=PC&webid=7158288523463362079&X-Bogus=DFSzswSLjsxANJ96taHVaU9WcBnW')

**Comment by Evil0ctal** [comment]
手动修改`scraper.py`文件中的`self.douyin_api_headers['cookie']`字段，使用抓包从cookie中获得的新`s_v_web_id`替换旧的即可。

**Comment by Cestb0n** [comment]
谢谢，可以了
