### ISSUE TITLE
[BUG] X-Bogus.js 不存在

### ISSUE THREAD

**Issue by a13cde** [Evil0ctal/Douyin_TikTok_Download_API#168]
获取抖音视频数据失败！原因:[Errno 2] No such file or directory: './X-Bogus.js'
scraper.py", line 223, in generate_x_bogus_url
    xbogus = execjs.compile(open('./X-Bogus.js').read()).call('sign', query, self.headers['User-Agent'])
FileNotFoundError: [Errno 2] No such file or directory: './X-Bogus.js'

**Comment by Evil0ctal** [comment]
确保js文件跟scraper.py处于同级目录。

**Comment by a13cde** [comment]
X-Bogus.js  没有这个文件

**Comment by a13cde** [comment]
我找到了，Douyin_TikTok_Download_API 有
