### ISSUE TITLE
[BUG] 抖音视频链接无法解析，报错

### ISSUE THREAD

**Issue by wuhaoyupku** [Evil0ctal/Douyin_TikTok_Download_API#177]
***发生错误的平台？***

如：抖音

***发生错误的端点？***

如：API-V1

***提交的输入值？***

如：短视频链接：http://10.11.111.12:8080/api?url=https://www.douyin.com/video/7154051876768484616&minimal=false

***是否有再次尝试？***

如：是，发生错误后两个小时时间后错误依旧存在。

***你有查看本项目的自述文件或接口文档吗？***

如：有，并且很确定该问题是程序导致的。

<img width="1317" alt="企业微信截图_ed60af4e-f559-4ff8-a473-40b1a2d1fb07" src="https://user-images.githubusercontent.com/10151600/224926451-1c4df64c-0616-4cd7-be03-b8f50411c567.png">

**Comment by Evil0ctal** [comment]
已经修复了，无需修改代码。

**Comment by wuhaoyupku** [comment]
昨天下午有段时间可以了，今天试了下又不行了

**Comment by Evil0ctal** [comment]
已修复，可以自己手动修改scraper.py的cookie修复。

**Comment by wuhaoyupku** [comment]
不好意思这里没有搞懂，是说需要自己去配置 scraper.py 里面的cookie 么？ 这个可以自动获取或者更新么？


谢谢






&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Evil0ctal/Douyin_TikTok_Download_API"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月15日(星期三) 晚上6:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Evil0ctal/Douyin_TikTok_Download_API] [BUG] 抖音视频链接无法解析，报错 (Issue #177)





 
已修复，可以自己手动修改scraper.py的cookie修复。
