### ISSUE TITLE
[Feature Request] PC接口返回的图片压缩质量为q75，移动设备网页端返回的图片压缩质量为q86，希望方便的话可以研究一下。

### ISSUE THREAD

**Issue by YUDONGLING** [Evil0ctal/Douyin_TikTok_Download_API#178]
移动设备网页端会访问 https://m.douyin.com/web/api/v2/aweme/iteminfo/?reflow_source=reflow_page&item_ids=xxx&msToken=xxx&X-Bogus=xxx&_signature=xxx 接口，其中返回的图片质量相对目前使用的PC网页版？接口更加清晰。希望作者方便的话可以研究一下。

**Comment by 2857584289** [comment]
确实，但是这个v2接口加上x-bogus怎么用不了

**Comment by Evil0ctal** [comment]
好的，我晚点去研究一下。
