### ISSUE TITLE
bypass liverecord video

### ISSUE THREAD

**Issue by wanghaisheng** [Evil0ctal/Douyin_TikTok_Download_API#18]
```
        if len(js['item_list']) == 0:
            print('this video is not supported yet',js['filter_list'][0]['filter_reason'])
```
for test purpose
https://www.douyin.com/video/7068253884954791182
https://www.iesdouyin.com/web/api/v2/aweme/iteminfo/?item_ids=7068253884954791182

**Comment by Evil0ctal** [comment]
> ```
> 
>         if len(js['item_list']) == 0:
> 
>             print('this video is not supported yet',js['filter_list'][0]['filter_reason'])
> 
> ```
> 
> for test purpose
> 
> https://www.douyin.com/video/7068253884954791182
> 
> https://www.iesdouyin.com/web/api/v2/aweme/iteminfo/?item_ids=7068253884954791182    
> 
> 
> 
> 

感谢反馈: )

**Comment by wanghaisheng** [comment]
html里面倒是有video src

            # https://v26-web.douyinvod.com/d7cbc2bb8e1c99f754a99a9550435470/62678e38/video/tos/cn/tos-cn-ve-15-alinc2/74cfb5f241284d8385ffa0dabb59de08/?a=6383&br=1717&bt=1717&cd=1%7C0%7C0%7C0&ch=26&cr=0&cs=0&cv=1&dr=0&ds=3&er=&ft=iDIGbiNN6VQ9wUHpmBlW.CDJ-XtmbhdxwiP8_4kag36&l=021650944742163fdbddc0300fff0010a81ecd80000007a10e237&lr=all&mime_type=video_mp4&net=0&pl=0&qs=0&rc=M3doNjw6ZjRxOzMzNGkzM0ApOWhoOWg1OmRlNzhlNmg0NGcxZmNecjQwa19gLS1kLS9zczQtYGA0MTYwYTVjLjM1MTM6Yw%3D%3D&vl=&vr=
# https://v26-web.douyinvod.com/5f2fec91fdfa45b85e80d2e48edc5e20/62679207/video/tos/cn/tos-cn-ve-15-alinc2/74cfb5f241284d8385ffa0dabb59de08/?a=6383&br=1717&bt=1717&cd=1%7C0%7C0%7C0&ch=26&cr=0&cs=0&cv=1&dr=0&ds=3&er=&ft=5q_lc5mmnPD12Nh46z.-UxH1FuYKc3wv25y3&l=021650945717381fdbddc0100fff0030ac3789c0000007893298c&lr=all&mime_type=video_mp4&net=0&pl=0&qs=0&rc=M3doNjw6ZjRxOzMzNGkzM0ApOWhoOWg1OmRlNzhlNmg0NGcxZmNecjQwa19gLS1kLS9zczQtYGA0MTYwYTVjLjM1MTM6Yw%3D%3D&vl=&vr=
 

但我死活在dev tools里没找到这个链接怎么出来的

**Comment by Evil0ctal** [comment]
> html里面倒是有video src
> 
> ```
>             # https://v26-web.douyinvod.com/d7cbc2bb8e1c99f754a99a9550435470/62678e38/video/tos/cn/tos-cn-ve-15-alinc2/74cfb5f241284d8385ffa0dabb59de08/?a=6383&br=1717&bt=1717&cd=1%7C0%7C0%7C0&ch=26&cr=0&cs=0&cv=1&dr=0&ds=3&er=&ft=iDIGbiNN6VQ9wUHpmBlW.CDJ-XtmbhdxwiP8_4kag36&l=021650944742163fdbddc0300fff0010a81ecd80000007a10e237&lr=all&mime_type=video_mp4&net=0&pl=0&qs=0&rc=M3doNjw6ZjRxOzMzNGkzM0ApOWhoOWg1OmRlNzhlNmg0NGcxZmNecjQwa19gLS1kLS9zczQtYGA0MTYwYTVjLjM1MTM6Yw%3D%3D&vl=&vr=
> # https://v26-web.douyinvod.com/5f2fec91fdfa45b85e80d2e48edc5e20/62679207/video/tos/cn/tos-cn-ve-15-alinc2/74cfb5f241284d8385ffa0dabb59de08/?a=6383&br=1717&bt=1717&cd=1%7C0%7C0%7C0&ch=26&cr=0&cs=0&cv=1&dr=0&ds=3&er=&ft=5q_lc5mmnPD12Nh46z.-UxH1FuYKc3wv25y3&l=021650945717381fdbddc0100fff0030ac3789c0000007893298c&lr=all&mime_type=video_mp4&net=0&pl=0&qs=0&rc=M3doNjw6ZjRxOzMzNGkzM0ApOWhoOWg1OmRlNzhlNmg0NGcxZmNecjQwa19gLS1kLS9zczQtYGA0MTYwYTVjLjM1MTM6Yw%3D%3D&vl=&vr=
> ```
> 
> 但我死活在dev tools里没找到这个链接怎么出来的

控制台里面可以看到这个请求，但是好像要带签名。
`https://www.douyin.com/aweme/v1/web/aweme/related/?device_platform=webapp&aid=6383&channel=channel_pc_web&aweme_id=7068253884954791182&count=20&filterGids=7068253884954791182,7068253884954791182,7068253884954791182&version_code=170400&version_name=17.4.0&cookie_enabled=true&screen_width=1348&screen_height=758&browser_language=zh-CN&browser_platform=Win32&browser_name=Chrome&browser_version=100.0.4896.127&browser_online=true&engine_name=Blink&engine_version=100.0.4896.127&os_name=Windows&os_version=10&cpu_core_num=16&device_memory=8&platform=PC&downlink=10&effective_type=4g&round_trip_time=100&webid=7089948928418498060&msToken=rDxpWD5t95VBlGV2m7lPRiZYKG8Qdh1fiHf6OXyjueKx97iw-5kvCxTjjTsf9D_D-zSLP-6QO9EK1hG_Mcb3rptx6AGjO1OZ4hk16gQk8fWyQ6pDco7ZNYZOs64oe-5_kQ==&X-Bogus=DFSzswVOgxiAN92NSU/tjM9WX7jZ&_signature=_02B4Z6wo00001KznKnAAAIDALOXQMoeSE7Ss5y7AAElj6k5eqdPfvYGVPwJo16SBvzMw10UTHpQi-.YFPjSvT4lRUY2T3bL3GkTdfWSYh2s0n9z20dPdoc3kjyefDGFO0wsZN0-SzX2EbVASb6`

**Comment by Evil0ctal** [comment]
live视频已经支持解析。
请查看scraper.py文件。
