### ISSUE TITLE
[Feature request] 自己部署的话，请问可以改cookie吗

### ISSUE THREAD

**Issue by cosylxc** [Evil0ctal/Douyin_TikTok_Download_API#182]
你好，抖音很多账号都是私密账号，还有就是日常24小时那种，也只有关注者可以看。

我试了一下，那些视频网页版api都无法解析呢，想问一下，如果自己部署，可以改cookie，然后获得视频地址吗？

**Comment by Evil0ctal** [comment]
你可以登录后使用自己的cookie，但是注意自己账号的安全。
