### ISSUE TITLE
抖音图集？

### ISSUE THREAD

**Issue by wanghaisheng** [Evil0ctal/Douyin_TikTok_Download_API#19]
# https://www.iesdouyin.com/web/api/v2/aweme/iteminfo/?item_ids=6742624178265984268    

这个视频是不是要改成这样
            if js['item_list'][0]['images'] is not None or js['item_list'][0]['image_infos'] is not None:

**Comment by Evil0ctal** [comment]
> 

请问[https://www.douyin.com/video/6742624178265984268](https://www.douyin.com/video/6742624178265984268)这个链接是直播回放吗？我看API里没有返回视频或图集的直链。

**Comment by wanghaisheng** [comment]
我也不太懂 我是从用户页抠出来的

**Comment by Evil0ctal** [comment]
> 我也不太懂 我是从用户页抠出来的

哦哦哦，这个视频很奇怪，没有图片文件的直链也没有视频文件的直链，不知道是不是和抖音最近更新有关系。
