### ISSUE TITLE
[BUG] docker部署，下载视频时候报错 TypeError: Constructor parameter should be str

### ISSUE THREAD

**Issue by KimFu2** [Evil0ctal/Douyin_TikTok_Download_API#190]
TypeError: Constructor parameter should be str

<img width="838" alt="image" src="https://user-images.githubusercontent.com/47135958/228776155-66f5acff-8e2f-4675-b937-79f08015a28f.png">

详细日志：
当前链接平台为:douyin
正在获取视频ID...
正在通过抖音分享链接获取原始链接...
获取原始链接成功, 原始链接为: https://www.iesdouyin.com/share/video/7213889226960653628/
获取到的抖音视频ID为: 7213889226960653628
获取视频ID成功,视频ID为:7213889226960653628
正在获取视频数据...
正在获取抖音视频数据...
生成的X-Bogus签名为: DFSzswSLg7bANJ96tG4kvt9WcBjh
正在获取视频数据API: https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=webapp&aid=6383&channel=channel_pc_web&aweme_id=7213889226960653628&pc_client_type=1&version_code=190500&version_name=19.5.0&cookie_enabled=true&screen_width=1344&screen_height=756&browser_language=zh-CN&browser_platform=Win32&browser_name=Firefox&browser_version=110.0&browser_online=true&engine_name=Gecko&engine_version=109.0&os_name=Windows&os_version=10&cpu_core_num=16&device_memory=&platform=PC&webid=7158288523463362079&msToken=abL8SeUTPa9-EToD8qfC7toScSADxpg6yLh2dbNcpWHzE0bT04txM_4UwquIcRvkRb9IU8sifwgM1Kwf1Lsld81o9Irt2_yNyUbbQPSUO8EfVlZJ_78FckDFnwVBVUVK&X-Bogus=DFSzswSLg7bANJ96tG4kvt9WcBjh
获取视频数据成功！
获取视频数据成功，正在判断数据类型...
数据类型代码: 0
数据类型: video
准备开始判断并处理数据...
正在处理抖音视频数据...
日志记录成功！
url:  https://aweme.snssdk.com/aweme/v1/playwm/?video_id=v02033g10000cgee4bjc77u3eck6q5cg&radio=1080p&line=0
file_path:  ./download/api.douyin.wtf_douyin_7213889226960653628_watermark.mp4
当前链接平台为:douyin
正在获取视频ID...
正在通过抖音分享链接获取原始链接...
获取原始链接成功, 原始链接为: https://www.iesdouyin.com/share/video/7213889226960653628/
获取到的抖音视频ID为: 7213889226960653628
获取视频ID成功,视频ID为:7213889226960653628
正在获取视频数据...
正在获取抖音视频数据...
生成的X-Bogus签名为: DFSzswSLg7bANJ96tG4kI09WcBj5
正在获取视频数据API: https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=webapp&aid=6383&channel=channel_pc_web&aweme_id=7213889226960653628&pc_client_type=1&version_code=190500&version_name=19.5.0&cookie_enabled=true&screen_width=1344&screen_height=756&browser_language=zh-CN&browser_platform=Win32&browser_name=Firefox&browser_version=110.0&browser_online=true&engine_name=Gecko&engine_version=109.0&os_name=Windows&os_version=10&cpu_core_num=16&device_memory=&platform=PC&webid=7158288523463362079&msToken=abL8SeUTPa9-EToD8qfC7toScSADxpg6yLh2dbNcpWHzE0bT04txM_4UwquIcRvkRb9IU8sifwgM1Kwf1Lsld81o9Irt2_yNyUbbQPSUO8EfVlZJ_78FckDFnwVBVUVK&X-Bogus=DFSzswSLg7bANJ96tG4kI09WcBj5
获取视频数据成功！
获取视频数据成功，正在判断数据类型...
数据类型代码: 0
数据类型: video
准备开始判断并处理数据...
正在处理抖音视频数据...
日志记录成功！
url:  https://aweme.snssdk.com/aweme/v1/playwm/?video_id=v02033g10000cgee4bjc77u3eck6q5cg&radio=1080p&line=0
file_path:  ./download/api.douyin.wtf_douyin_7213889226960653628_watermark.mp4
当前链接平台为:douyin
正在获取视频ID...
正在通过抖音分享链接获取原始链接...
获取原始链接成功, 原始链接为: https://www.iesdouyin.com/share/video/7213889226960653628/
获取到的抖音视频ID为: 7213889226960653628
获取视频ID成功,视频ID为:7213889226960653628
正在获取视频数据...
正在获取抖音视频数据...
生成的X-Bogus签名为: DFSzswSLg7bANJ96tG4kBt9WcBJz
正在获取视频数据API: https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=webapp&aid=6383&channel=channel_pc_web&aweme_id=7213889226960653628&pc_client_type=1&version_code=190500&version_name=19.5.0&cookie_enabled=true&screen_width=1344&screen_height=756&browser_language=zh-CN&browser_platform=Win32&browser_name=Firefox&browser_version=110.0&browser_online=true&engine_name=Gecko&engine_version=109.0&os_name=Windows&os_version=10&cpu_core_num=16&device_memory=&platform=PC&webid=7158288523463362079&msToken=abL8SeUTPa9-EToD8qfC7toScSADxpg6yLh2dbNcpWHzE0bT04txM_4UwquIcRvkRb9IU8sifwgM1Kwf1Lsld81o9Irt2_yNyUbbQPSUO8EfVlZJ_78FckDFnwVBVUVK&X-Bogus=DFSzswSLg7bANJ96tG4kBt9WcBJz
获取视频数据成功！
获取视频数据成功，正在判断数据类型...
数据类型代码: 0
数据类型: video
准备开始判断并处理数据...
正在处理抖音视频数据...
日志记录成功！
url:  https://aweme.snssdk.com/aweme/v1/playwm/?video_id=v02033g10000cgee4bjc77u3eck6q5cg&radio=1080p&line=0
file_path:  ./download/api.douyin.wtf_douyin_7213889226960653628_watermark.mp4
当前链接平台为:douyin
正在获取视频ID...
正在通过抖音分享链接获取原始链接...
获取原始链接成功, 原始链接为: https://www.iesdouyin.com/share/video/7213889226960653628/
获取到的抖音视频ID为: 7213889226960653628
获取视频ID成功,视频ID为:7213889226960653628
正在获取视频数据...
正在获取抖音视频数据...
生成的X-Bogus签名为: DFSzswSLg7bANJ96tG4kkt9WcBJh
正在获取视频数据API: https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=webapp&aid=6383&channel=channel_pc_web&aweme_id=7213889226960653628&pc_client_type=1&version_code=190500&version_name=19.5.0&cookie_enabled=true&screen_width=1344&screen_height=756&browser_language=zh-CN&browser_platform=Win32&browser_name=Firefox&browser_version=110.0&browser_online=true&engine_name=Gecko&engine_version=109.0&os_name=Windows&os_version=10&cpu_core_num=16&device_memory=&platform=PC&webid=7158288523463362079&msToken=abL8SeUTPa9-EToD8qfC7toScSADxpg6yLh2dbNcpWHzE0bT04txM_4UwquIcRvkRb9IU8sifwgM1Kwf1Lsld81o9Irt2_yNyUbbQPSUO8EfVlZJ_78FckDFnwVBVUVK&X-Bogus=DFSzswSLg7bANJ96tG4kkt9WcBJh
获取视频数据成功！
获取视频数据成功，正在判断数据类型...
数据类型代码: 0
数据类型: video
准备开始判断并处理数据...
正在处理抖音视频数据...
日志记录成功！
url:  https://aweme.snssdk.com/aweme/v1/playwm/?video_id=v02033g10000cgee4bjc77u3eck6q5cg&radio=1080p&line=0
file_path:  ./download/api.douyin.wtf_douyin_7213889226960653628_watermark.mp4
当前链接平台为:douyin
正在获取视频ID...
正在通过抖音分享链接获取原始链接...
获取原始链接成功, 原始链接为: https://www.iesdouyin.com/share/video/7213889226960653628/
获取到的抖音视频ID为: 7213889226960653628
获取视频ID成功,视频ID为:7213889226960653628
正在获取视频数据...
正在获取抖音视频数据...
生成的X-Bogus签名为: DFSzswSLg7bANJ96tG4p809WcBJj
正在获取视频数据API: https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=webapp&aid=6383&channel=channel_pc_web&aweme_id=7213889226960653628&pc_client_type=1&version_code=190500&version_name=19.5.0&cookie_enabled=true&screen_width=1344&screen_height=756&browser_language=zh-CN&browser_platform=Win32&browser_name=Firefox&browser_version=110.0&browser_online=true&engine_name=Gecko&engine_version=109.0&os_name=Windows&os_version=10&cpu_core_num=16&device_memory=&platform=PC&webid=7158288523463362079&msToken=abL8SeUTPa9-EToD8qfC7toScSADxpg6yLh2dbNcpWHzE0bT04txM_4UwquIcRvkRb9IU8sifwgM1Kwf1Lsld81o9Irt2_yNyUbbQPSUO8EfVlZJ_78FckDFnwVBVUVK&X-Bogus=DFSzswSLg7bANJ96tG4p809WcBJj
获取视频数据成功！
获取视频数据成功，正在判断数据类型...
数据类型代码: 0
数据类型: video
准备开始判断并处理数据...
正在处理抖音视频数据...
日志记录成功！
url:  https://aweme.snssdk.com/aweme/v1/play/?video_id=v02033g10000cgee4bjc77u3eck6q5cg&ratio=1080p&line=0
file_path:  ./download/api.douyin.wtf_douyin_7213889226960653628.mp4
当前链接平台为:douyin
正在获取视频ID...
正在通过抖音分享链接获取原始链接...
获取原始链接成功, 原始链接为: https://www.iesdouyin.com/share/video/7213889226960653628/
获取到的抖音视频ID为: 7213889226960653628
获取视频ID成功,视频ID为:7213889226960653628
正在获取视频数据...
正在获取抖音视频数据...
生成的X-Bogus签名为: DFSzswSLg7bANJ96tG4peU9WcBnt
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/.local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/root/.local/lib/python3.10/site-packages/fastapi/applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "/root/.local/lib/python3.10/site-packages/starlette/applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/root/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/root/.local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/root/.local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/root/.local/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/root/.local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/root/.local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/root/.local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/root/.local/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/root/.local/lib/python3.10/site-packages/slowapi/extension.py", line 729, in async_wrapper
    response = await func(*args, **kwargs)  # type: ignore
  File "/app/web_api.py", line 660, in download_file_hybrid
    async with session.get(url=cdn_url) as res:
  File "/root/.local/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/root/.local/lib/python3.10/site-packages/aiohttp/client.py", line 423, in _request
    url = self._build_url(str_or_url)
  File "/root/.local/lib/python3.10/site-packages/aiohttp/client.py", line 357, in _build_url
    url = URL(str_or_url)
  File "/root/.local/lib/python3.10/site-packages/yarl/_url.py", line 154, in __new__
    raise TypeError("Constructor parameter should be str")
TypeError: Constructor parameter should be str

**Comment by KimFu2** [comment]
你的意思是把参数url替换成原始url吗？如果是这样的话，还是老样子

**Comment by 546200350** [comment]
> 应该是抖音web端出验证码了，用原始url，如：https://www.douyin.com/video/7213889226960653628

如何处理呢这种情况？  我这边服务器也报这个错了

**Comment by gameopenwrt** [comment]
有得救吗，大神们！
我也遇到报错了
