### ISSUE TITLE
可以抓到具体的评论的内容嘛

### ISSUE THREAD

**Issue by hhhheep** [Evil0ctal/Douyin_TikTok_Download_API#191]
如题，还有一个问题是 可以根据 关键字 去收集视频嘛？
先谢谢作者回答了

**Comment by Evil0ctal** [comment]
tikhub的商用API可以

**Comment by hhhheep** [comment]
> tikhub的商用API可以

如果需要想要购买 那个商业api的使用次数在哪购买？好像 网站 进不去 买不了  签不了到  ，微信加不了……

**Comment by Evil0ctal** [comment]
修好了，你再试一下，加我微信：Evil0ctal
