### ISSUE TITLE
[BUG] Internal Server Error

### ISSUE THREAD

**Issue by cauindo113** [Evil0ctal/Douyin_TikTok_Download_API#192]
请帮我解决这个问题
![image](https://user-images.githubusercontent.com/79757202/229462562-676da958-ad2d-4fe0-88c5-2c2ad2b0e1ac.png)

**Comment by cauindo113** [comment]
please help me !!!!!

**Comment by cauindo113** [comment]
please help me !!!!!!!!!!!!

**Comment by Evil0ctal** [comment]
晚点我去看看

**Comment by maxsky** [comment]
> 晚点我去看看

已测试通过，见 PR #193

**Comment by Evil0ctal** [comment]
已修复
