### ISSUE TITLE
[BUG] 在linux平台运行,发现报js错误

### ISSUE THREAD

**Issue by liandyao** [Evil0ctal/Douyin_TikTok_Download_API#194]
感谢作者开源代码!!!

我在按正常部署完成之后, 输入网址可以正常访问,但是不能解析,报如下错误
Use http://192.168.0.4:8110/ to access the application
当前链接平台为:douyin
正在获取视频ID...
正在通过抖音分享链接获取原始链接...
获取原始链接成功, 原始链接为: https://www.iesdouyin.com/share/video/7218525164365991183/
获取到的抖音视频ID为: 7218525164365991183
获取视频ID成功,视频ID为:7218525164365991183
正在获取视频数据...
正在获取抖音视频数据...
获取抖音视频数据失败！原因:(101, '', '/tmp/execjsn0k5jk7t.js:483:16 Expected ; but found a\n            let a = !1;\n                ^\n/tmp/execjsn0k5jk7t.js:524:8 Expected an operand but found )\n    }, () => 0, () => "03v", {\n        ^\n/tmp/execjsn0k5jk7t.js:526:5 Expected an operand but found ,\n    }, {\n     ^\n/tmp/execjsn0k5jk7t.js:528:22 Expected ; but found :\n        msNewTokenList: [],\n                      ^\n/tmp/execjsn0k5jk7t.js:530:17 Expected ; but found :\n        clickList: [],\n                 ^\n/tmp/execjsn0k5jk7t.js:532:19 Expected ; but found :\n        activeState: [],\n                   ^\n/tmp/execjsn0k5jk7t.js:534:15 Expected ; but found :\n        envcode: 0,\n               ^\n/tmp/execjsn0k5jk7t.js:536:16 Expected ; but found :\n        msStatus: 0,\n                ^\n/tmp/execjsn0k5jk7t.js:538:13 Expected ; but found :\n        ttwid: "",\n             ^\n/tmp/execjsn0k5jk7t.js:540:19 Expected ; but found :\n        tt_webid_v2: ""\n                   ^\n/tmp/execjsn0k5jk7t.js:544:12 Expected : but found a\n        let a = new Uint8Array(3);\n            ^\n/tmp/execjsn0k5jk7t.js:545:8 Invalid return statement\n        return a[0] = e / 256, a[1] = e % 256, a[2] = b % 256, String.fromCharCode.apply(null, a)\n        ^\n/tmp/execjsn0k5jk7t.js:546:4 Expected eof but found }\n    }, (e, b) => {\n    ^\n')
^CTraceback (most recent call last):
  File "/www/wwwroot/Douyin_TikTok_Download_API/web_app.py", line 398, in <module>
    start_server(main, port=port, debug=False, cdn=cdn)
  File "/usr/python3.11/lib/python3.11/site-packages/pywebio/platform/tornado.py", line 302, in start_server
    tornado.ioloop.IOLoop.current().start()
  File "/usr/python3.11/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "/usr/python3.11/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/python3.11/lib/python3.11/asyncio/base_events.py", line 1881, in _run_once
    event_list = self._selector.select(timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/python3.11/lib/python3.11/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

**Comment by liandyao** [comment]
在自己的windows10上面部署可以运行成功

**Comment by Evil0ctal** [comment]
使用Ubuntu22部署一下
