### ISSUE TITLE
Cookie失效了

### ISSUE THREAD

**Issue by Cestb0n** [Evil0ctal/Douyin_TikTok_Download_API#195]
***Platform where the error occurred?***

Such as: Douyin/TikTok

***The endpoint where the error occurred?***

Such as: API-V1/API-V2/Web APP

***Submitted input value?***

Such as: video link

***Have you tried again?***

Such as: Yes, the error still exists after X time after the error occurred.

***Have you checked the readme or interface documentation for this project?***

Such as: Yes, and it is very sure that the problem is caused by the program.

**Comment by Evil0ctal** [comment]
Can you provide more information?

**Comment by Cestb0n** [comment]
获取原始链接成功, 原始链接为: https://www.iesdouyin.com/share/video/7219994611979160892/
获取到的抖音视频ID为: 7219994611979160892
获取视频ID成功,视频ID为:7219994611979160892
正在获取视频数据...
正在获取抖音视频数据...
正在获取视频数据API: https://www.iesdouyin.com/aweme/v1/web/aweme/detail/?aweme_id=7219994611979160892&aid=1128&version_name=23.5.0&device_platform=android&os_version=2333&Github=Evil0ctal&words=F**K-U-ByteDance
获取抖音视频数据失败！原因:0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://www.iesdouyin.com/aweme/v1/web/aweme/detail/?aweme_id=7219994611979160892&aid=1128&version_name=23.5.0&device_platform=android&os_version=2333&Github=Evil0ctal&words=F**K-U-ByteDance')
[抖音|TikTok方法]返回数据为空，无法处理！
The hybrid parsing result:
 {'status': 'failed', 'message': '返回数据为空，无法处理！/Return data is empty and cannot be processed!'}
