### ISSUE TITLE
请问我下载代码到本地pycharm运行，但是下载不了任何视频[BUG] 简短明了的描述问题

### ISSUE THREAD

**Issue by skyhhuc** [Evil0ctal/Douyin_TikTok_Download_API#197]
***发生错误的平台？***

如：抖音 & TikTok

***发生错误的端点？***

如：API-V1/API-V2/Web APP

***提交的输入值？***

如：douyin_url = 'https://v.douyin.com/ATnQNCg/'
    tiktok_url = 'https://www.tiktok.com/@cocosneaker0'
![pp1](https://user-images.githubusercontent.com/66587321/231547357-2211517c-8071-46ad-9d13-3a17a3a6cca8.png)
![tk03](https://user-images.githubusercontent.com/66587321/231547367-1a294b92-7242-4aee-bbce-1b85cfec1cd7.png)
![tk33](https://user-images.githubusercontent.com/66587321/231547372-de8bfbc7-a2b9-43a8-948b-855589ab251a.png)

***是否有再次尝试？***

如：是，发生错误后X时间后错误依旧存在。

***你有查看本项目的自述文件或接口文档吗？***

如：有，并且很确定该问题是程序导致的。我也不知道是哪里有问题，连国内的抖音视频都无法下载，就卡在那里什么应用启动完成，然后一点动静都没有了
还有我测试scrapy.py也是没有反应，只有一个视频数据解析地址，打开是空的

**Comment by skyhhuc** [comment]
我分别输入了一个douyin单视频链接和一个tiktok单视频链接，运行scrapy.py还是报错，如截图；运行api.py跟之前一样没有动静，;只有运行web是正常的，抖音可以解析，tiktok可能是没有代理解析不成功，因为我部署在本地的。
![123](https://user-images.githubusercontent.com/66587321/231568826-2ab01fcf-68c2-453c-bf1d-9a00ddee82ba.png)
![321](https://user-images.githubusercontent.com/66587321/231568840-7b989014-f31e-4fcd-b38a-4325acc99891.png)

**Comment by skyhhuc** [comment]
应该也不是代理的问题，我设置了socks5，还有一样获取失败，tiktok的
![999999](https://user-images.githubusercontent.com/66587321/231584759-547bc5ce-781a-43e7-a33b-b4a126462fdc.png)

**Comment by Evil0ctal** [comment]
你输入的链接我看看，视频URL。

**Comment by skyhhuc** [comment]
https://www.tiktok.com/@cocosneaker0/video/7221204237257313582

**Comment by Evil0ctal** [comment]
好的，你的IP是在哪个位置？

**Comment by skyhhuc** [comment]
我国内的，用的pycharm，但是我设置了代理，而且你那个配置文件也设置了socks5的代理，我目前在用的，应该是有效的，不知道是不是代理没成功。我用你那个网址测试了一下，好像一下子就出来了。。。另外我看你这上面那个什么tikhub api不是支持批量下载吗

**Comment by Evil0ctal** [comment]
tikhub支持API调用，下载功能需要自己写，目前看下来应该是你的代理有问题，用美国的IP试一下。

**Comment by skyhhuc** [comment]
我那个代理就是美国的ip，我在本地使用，地址是192.168.1.101:80，不知道是不是因为是局域网地址造成代理不能用，外网什么都可以打开的。但是tiktok就是解析不出来

**Comment by Evil0ctal** [comment]
你在config.ini里配置代理了吗

**Comment by skyhhuc** [comment]
配置了，socks5://用户名@密码:xxx.xxx.xx.xx:端口，应该是这样吧？？？

**Comment by Evil0ctal** [comment]
使用http代理代替socks5试一下。
