### ISSUE TITLE
tiktok视频总是获取信息失败，部署在docker里也还是失败

### ISSUE THREAD

**Issue by CCLCK** [Evil0ctal/Douyin_TikTok_Download_API#199]
![image](https://user-images.githubusercontent.com/84182037/235693760-672aa10a-9d6e-438c-994f-99df5ff105b6.png)
运行结果：
![image](https://user-images.githubusercontent.com/84182037/235693649-0ee72c13-33e9-49d2-83bb-f5ec26c1ada2.png)

纯小白，是这样运行吗😭😭😭

**Comment by Evil0ctal** [comment]
可能是你IP被拉黑了。

**Comment by CCLCK** [comment]
参考了大佬的源码自己构造请求爬了orz
