### ISSUE TITLE
有错误

### ISSUE THREAD

**Issue by xinqing123** [Evil0ctal/Douyin_TikTok_Download_API#20]
<html>
<body>
<div class="alert alert-danger " role="alert" style="box-sizing: border-box; position: relative; padding: 0.75rem 1.25rem; margin-bottom: 1rem; border: 1px solid rgb(245, 198, 203); border-radius: 0.25rem; color: rgb(114, 28, 36); background-color: rgb(248, 215, 218); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 10px; white-space: pre-wrap;">发生了了意料之外的错误，输入值已被记录。</p></div><h3 style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-weight: 600; line-height: 1.25; font-size: 1.25em; color: rgb(33, 37, 41); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">⚠详情</h3><div style="box-sizing: border-box; color: rgb(33, 37, 41); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; overflow: auto;">

函数名 | 原因 | 输入值
-- | -- | --
Scraper.tiktok() | HTTPSConnectionPool(host='www.tiktok.com', port=443): Max retries exceeded with url: /@tvamii/video/7045537727743380782 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CBF7DC35E0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。')) | https://www.tiktok.com/@tvamii/video/7045537727743380782

</div><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 10px; color: rgb(33, 37, 41); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">可能的原因:</p><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 10px; color: rgb(33, 37, 41); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">服务器可能被目标主机的防火墙限流(稍等片刻后再次尝试)</p><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 10px; color: rgb(33, 37, 41); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">输入了错误的链接(暂不支持主页链接解析)</p><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 10px; color: rgb(33, 37, 41); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">该视频已经被删除或屏蔽(你看的都是些啥(⊙_⊙)?)</p><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 10px; color: rgb(33, 37, 41); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">你可以在右上角的关于菜单中查看本站错误日志。</p><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 10px; color: rgb(33, 37, 41); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a href="https://github.com/Evil0ctal/Douyin_TikTok_Download_API/issues" style="box-sizing: border-box; color: rgb(3, 102, 214); text-decoration: none; background-color: initial;">点击此处在GayHub上进行反馈</a></p>
</body>
</html>发生了了意料之外的错误，输入值已被记录。

⚠详情
函数名	原因	输入值
Scraper.tiktok()	HTTPSConnectionPool(host='www.tiktok.com', port=443): Max retries exceeded with url: /@tvamii/video/7045537727743380782 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CBF7DC35E0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))	https://www.tiktok.com/@tvamii/video/7045537727743380782
可能的原因:

服务器可能被目标主机的防火墙限流(稍等片刻后再次尝试)

输入了错误的链接(暂不支持主页链接解析)

该视频已经被删除或屏蔽(你看的都是些啥(⊙_⊙)?)

你可以在右上角的关于菜单中查看本站错误日志。

[点击此处在GayHub上进行反馈](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/issues)

**Comment by Evil0ctal** [comment]
> 发生了了意料之外的错误，输入值已被记录。
> 
> ### ⚠详情
> 函数名	原因	输入值
> Scraper.tiktok()	HTTPSConnectionPool(host='www.tiktok.com', port=443): Max retries exceeded with url: /@tvamii/video/7045537727743380782 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CBF7DC35E0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))	https://www.tiktok.com/@tvamii/video/7045537727743380782
> 可能的原因:
> 
> 服务器可能被目标主机的防火墙限流(稍等片刻后再次尝试)
> 
> 输入了错误的链接(暂不支持主页链接解析)
> 
> 该视频已经被删除或屏蔽(你看的都是些啥(⊙_⊙)?)
> 
> 你可以在右上角的关于菜单中查看本站错误日志。
> 
> [点击此处在GayHub上进行反馈](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/issues)
> 
> 发生了了意料之外的错误，输入值已被记录。
> ⚠详情 函数名 原因 输入值 Scraper.tiktok() HTTPSConnectionPool(host='www.tiktok.com', port=443): Max retries exceeded with url: /@tvamii/video/7045537727743380782 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CBF7DC35E0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。')) https://www.tiktok.com/@tvamii/video/7045537727743380782 可能的原因:
> 
> 服务器可能被目标主机的防火墙限流(稍等片刻后再次尝试)
> 
> 输入了错误的链接(暂不支持主页链接解析)
> 
> 该视频已经被删除或屏蔽(你看的都是些啥(⊙_⊙)?)
> 
> 你可以在右上角的关于菜单中查看本站错误日志。
> 
> [点击此处在GayHub上进行反馈](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/issues)

是TikTok API的问题，多尝试几次即可。
API Link：[https://api.tiktokv.com/aweme/v1/multi/aweme/detail/?aweme_ids=%5B7045537727743380782%5D](url)
