### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sheldygg** [Evil0ctal/Douyin_TikTok_Download_API#200]
Hello, how can I get the user's channel without this https://api.tikhub.io/tiktok_profile_videos endpoint.
i do with https://tiktok.com/@therock
but only 30 videos. maybe tiktok has a private api for example just like the video information in your code

**Comment by Evil0ctal** [comment]
Reverse engineering TikTok.

**Comment by sheldygg** [comment]
> Reverse engineering TikTok.

yes, i find wanted request in mobile app, but him have headers with X-Argus and X-Ladon signature =(

u have method to generate him?

**Comment by Evil0ctal** [comment]
If you want the method generate the sign, you will need to reverse the application. I can't provide any details about that part, maybe you can try Google it:)

**Comment by sheldygg** [comment]
ok, finally solved.
i have new question.
maybe you have method for generate short url?
from this
https://www.tiktok.com/@yyyasnooo/video/7234978439462227205

to this
https://vm.tiktok.com/ZM2LJa7ux/
