### ISSUE TITLE
[BUG] 从dockerhub上拉取的docker文件，运行出错

### ISSUE THREAD

**Issue by sparkzzt** [Evil0ctal/Douyin_TikTok_Download_API#201]
***发生错误的端点？***

如：web api出错，web app可以运行

***提交的输入值？***

还没有启动成功

***是否有再次尝试？***

如：是，发生错误后X时间后错误依旧存在。

运行docker后，报的这个错误，导致web_api启动失败
2023/5/16 18:33:12Traceback (most recent call last):
2023/5/16 18:33:12  File "/app/web_api.py", line 109, in <module>
2023/5/16 18:33:12    limiter = Limiter(key_func=get_remote_address)
2023/5/16 18:33:12  File "/root/.local/lib/python3.10/site-packages/slowapi/extension.py", line 240, in __init__
2023/5/16 18:33:12    self._storage: Union[Storage, AsyncStorage] = storage_from_string(
2023/5/16 18:33:12  File "/root/.local/lib/python3.10/site-packages/limits/storage/__init__.py", line 63, in storage_from_string
2023/5/16 18:33:12    return cast(StorageTypes, SCHEMES[scheme](storage_string, **options))
2023/5/16 18:33:12  File "/root/.local/lib/python3.10/site-packages/limits/storage/memory.py", line 32, in __init__
2023/5/16 18:33:12    self.timer.start()
2023/5/16 18:33:12  File "/usr/lib/python3.10/threading.py", line 935, in start
2023/5/16 18:33:12    _start_new_thread(self._bootstrap, ())
2023/5/16 18:33:12RuntimeError: can't start new thread

**Comment by Evil0ctal** [comment]
是不是你内存不足了？我目前无法复现你这个问题。

**Comment by muchunless** [comment]
在mac和linux上运行docker 也同样报这个错误，windows上正常。mac是16G内存，没有内存不足

**Comment by Evil0ctal** [comment]
使用Ubuntu进行部署试一下。

**Comment by muchunless** [comment]
ubuntu上成功了，之前是centos失败

**Comment by Evil0ctal** [comment]
是的，目前只支持Ubuntu部署。

**Comment by huangpj0210** [comment]
centos遇到此问题可以通过如下链接进行解决[https://medium.com/nttlabs/ubuntu-21-10-and-fedora-35-do-not-work-on-docker-20-10-9-1cd439d9921](链接)
