### ISSUE TITLE
[BUG] API return Internal Server Error

### ISSUE THREAD

**Issue by tudoanh** [Evil0ctal/Douyin_TikTok_Download_API#205]
***Platform where the error occurred?***

Such as: Douyin

***The endpoint where the error occurred?***

Such as: API-V1

***Submitted input value?***

Such as: [video link](https://v.douyin.com/UPmkWUE/)

Example: https://api.douyin.wtf/douyin_video_data/?douyin_video_url=https://v.douyin.com/UPmkWUE/

***Have you tried again?***

Such as: Yes, the error still exists for about 24hrs

***Have you checked the readme or interface documentation for this project?***

Such as: Yes, and it is very sure that the problem is caused by the program.

**Comment by tahirafridi** [comment]
Same 500 internal server error is occurring on their tiktok api, below is the example

https://api.douyin.wtf/api?url=https://www.tiktok.com/@dard..e..dill/video/7225981135069760773?is_from_webapp=1&sender_device=pc

**Comment by Evil0ctal** [comment]
@tahirafridi @tudoanh 

The API is back online

**Comment by tudoanh** [comment]
It died again 🥲

**Comment by Evil0ctal** [comment]
Can you provide more information?

**Comment by tudoanh** [comment]
So sorry, but a few hours ago seem like the API was down.

**Comment by tahirafridi** [comment]
Tiktok api is down again

**Comment by tahirafridi** [comment]
I don't know why the api is going down again and again? Is it something changes on tiktok end or it by the developers who publish new code without testing the whole process from start.

**Comment by tahirafridi** [comment]
here is the api url giving internal server error, status code: 500
https://api.douyin.wtf/api?url=https://www.tiktok.com/@dard..e..dill/video/7225981135069760773

**Comment by tudoanh** [comment]
Seem like only their API server is down, maybe because of high requests. I've created a simple script to get video url from their homepage using selenium, which is working fine.

https://gist.github.com/tudoanh/feda12ff6f97ce5bf9a55c75845ce7ea

**Comment by Evil0ctal** [comment]
Hi, code is all working and the server being Ddos since yesterday, remember I'm providing the free server, can't make any money of this, so it's all my passion support the free api server running, otherwise you can deploy this repo to your own server which is private and more stable, I will fix the Ddos problem soon.

**Comment by tahirafridi** [comment]
Thanks for your efforts, can I get its nodejs or php version? I don't know Python program

**Comment by artemmarkov050** [comment]
> Hi, code is all working and the server being Ddos since yesterday, remember I'm providing the free server, can't make any money of this, so it's all my passion support the free api server running, otherwise you can deploy this repo to your own server which is private and more stable, I will fix the Ddos problem soon.

Hi, how can I deploy the api on my server? Is there any tutorial ?

**Comment by tudoanh** [comment]
> Hi, code is all working and the server being Ddos since yesterday, remember I'm providing the free server, can't make any money of this, so it's all my passion support the free api server running, otherwise you can deploy this repo to your own server which is private and more stable, I will fix the Ddos problem soon.

Just ignore that guy, you are awesome and thanks for your efforts.

**Comment by tahirafridi** [comment]
> > Hi, code is all working and the server being Ddos since yesterday, remember I'm providing the free server, can't make any money of this, so it's all my passion support the free api server running, otherwise you can deploy this repo to your own server which is private and more stable, I will fix the Ddos problem soon.
> 
> Just ignore that guy, you are awesome and thanks for your efforts.

what's wrong? I just reported an issue as you did, and I raised my concern that why its getting stop working. The author replied and I got understood. You seem to me an attention seeker. Grow up bro.

**Comment by artemmarkov050** [comment]
> Hi, code is all working and the server being Ddos since yesterday, remember I'm providing the free server, can't make any money of this, so it's all my passion support the free api server running, otherwise you can deploy this repo to your own server which is private and more stable, I will fix the Ddos problem soon.

I did everything as instructed, but I don't really understand how I can find my api, what do I have to do to find a url like you have 'https://douyin.wtf/api?url={video_url}' ?

**Comment by Evil0ctal** [comment]
Alright boys, the API is now back online, hope no one will overuse it and take the server down again :)

I had to set up the WAF for 5 req/10s

**Comment by tahirafridi** [comment]
> Alright boys, the API is now back online, hope no one will overuse it and take the server down again :)
> 
> I had to set up the WAF for 5 req/10s

Thats great, thank you! I appreciate your willingness to support open source community <3 Brother I've my onw dedicated server but as I said I don't know how to setup it my Linux unbuntu server, Can you please guide me or recommend me a video/written tutorial. Thank you!
I ve server from contabo

**Comment by Evil0ctal** [comment]
Use my bash script:

https://github.com/Evil0ctal/Douyin_TikTok_Download_API/blob/main/README.en.md#-deployment-method-1-linux

**Comment by tahirafridi** [comment]
Thanks, let me try this and I will get back to you in case I need more informaiton. Thank you bro you are gem

**Comment by Evil0ctal** [comment]
Good good 👍🏻
