### ISSUE TITLE
[BUG] API is down 522

### ISSUE THREAD

**Issue by max-lychko** [Evil0ctal/Douyin_TikTok_Download_API#207]
Looks like API is down 
https://api.douyin.wtf
Returns code 522 
![2023-06-01_21-54](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/23723597/92c2ac4a-6d9a-4f54-9ca1-8b65163bab6a)

**Comment by tahirafridi** [comment]
Same here 500 error https://api.douyin.wtf/api?url=https://www.tiktok.com/@dard..e..dill/video/7225981135069760773

**Comment by Evil0ctal** [comment]
Fixed

**Comment by max-lychko** [comment]
@Evil0ctal thanks a lot
