### ISSUE TITLE
[BUG] Brief and clear description of the problem

### ISSUE THREAD

**Issue by artemmarkov050** [Evil0ctal/Douyin_TikTok_Download_API#209]
I installed api on my server, when I send a link to tiktok video, it downloads the same video, can you help me solve the problem?

**Comment by Evil0ctal** [comment]
Can you provide me the link of the TikTok video?

**Comment by artemmarkov050** [comment]
https://www.tiktok.com/@mallitis/video/7231248112466054426?is_from_webapp=1&sender_device=pc, and this happens with every video, I use my url 'https://217.18.61.254/api?url={video_url}'
