### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by TheShyzzcy** [Evil0ctal/Douyin_TikTok_Download_API#210]
在docker部署的时候，发生错误，以下都是docker报的错误和一些配置截图，求大佬解答
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/105832208/0fc6f3e9-a96f-4576-9680-9ed0104e8bcd)
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/105832208/72e86fcc-5491-454b-8a28-9d95d9c1ffd9)
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/105832208/aa96973a-49cb-4f5f-880d-16ee8eee2682)
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/105832208/0055e270-2fef-4a19-bc86-d0a8d551c442)

**Comment by Evil0ctal** [comment]
看起来是端口被占用了。

**Comment by TheShyzzcy** [comment]
> 看起来是端口被占用了。

那要怎么修改呢，之前的8000端口是被占用的，但是现在的8022是没有东西的，不解

**Comment by Evil0ctal** [comment]
再次修改端口，重启容器再试试。

**Comment by TheShyzzcy** [comment]
> 再修改端口，重新启动容器再试。
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/105832208/a3049e0a-044d-45bf-b681-627c09653f2b)
好像还是不行呢
能不能出一个详细的视频教程呢，太难了

**Comment by Evil0ctal** [comment]
这一行报错

OSError: [Errno 98] Address already in use

你是否启用了多个进程？

或者删掉容器重新部署一次。
