### ISSUE TITLE
运行pip包时报错0

### ISSUE THREAD

**Issue by xuepeilei** [Evil0ctal/Douyin_TikTok_Download_API#213]
获取抖音视频数据失败！原因:0, message='Attempt to decode JSON with unexpected mimetype
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/16931942/3fd3617c-e941-44fe-b163-cc9d00b57673)
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/16931942/64fef802-f0e6-4f88-bc40-0bf2e5bf1a46)

**Comment by Evil0ctal** [comment]
手动构建API的HTTP请求即可。

**Comment by Evil0ctal** [comment]
晚些时候我会更新PyPi包。
