### ISSUE TITLE
示例代码运行失败，返回错误码101，js 文件解析错误

### ISSUE THREAD

**Issue by anxinyf** [Evil0ctal/Douyin_TikTok_Download_API#214]
***发生错误的平台？***

抖音

***发生错误的端点？***

按照 README 的示例：
demo.py:
```
import asyncio
from douyin_tiktok_scraper.scraper import Scraper

api = Scraper()

async def hybrid_parsing(url: str) -> dict:
    # Hybrid parsing(Douyin/TikTok URL)
    result = await api.hybrid_parsing(url)
    print(f"The hybrid parsing result:\n {result}")
    return result

asyncio.run(hybrid_parsing(url="https://v.douyin.com/UWsSXHD/"))
```
代码运行平台：CentOS7：
python3 demo.py

***提交的输入值？***

短视频链接：https://v.douyin.com/UWsSXHD/

***是否有再次尝试？***

是，发生错误后X时间后错误依旧存在：
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/37263263/7bbe4edb-0459-44b5-81b7-9c475ea4394f)

看上去是解析 X-Bogus.js 有问题

***你有查看本项目的自述文件或接口文档吗？***

有，并且很确定该问题是程序导致的。

**Comment by Evil0ctal** [comment]
使用Ubuntu进行部署再次尝试一下。

**Comment by anxinyf** [comment]
> 使用Ubuntu进行部署再次尝试一下。

Ubuntu 可以的，在镜像里运行的！多谢

**Comment by Evil0ctal** [comment]
感谢支持😊
