### ISSUE TITLE
当我请求访问用户主页时候会遇到错误

### ISSUE THREAD

**Issue by emmIsabella** [Evil0ctal/Douyin_TikTok_Download_API#215]
https://api.tikhub.io/douyin/user_profile_videos_data
当我使用这个api请求访问用户主页时，我签到剩余的访问api次数会变成0，这是为什么

**Comment by Evil0ctal** [comment]
请到TikHub Discord中的#Support频道中寻求客户支持。

https://discord.gg/KgxUQv4Kpy
