### ISSUE TITLE
[BUG] Internal Server Error 500

### ISSUE THREAD

**Issue by max-lychko** [Evil0ctal/Douyin_TikTok_Download_API#216]
API route /api?url= returns 500

https://[api.douyin.wtf/api?url=https://www.tiktok.com/@overtime/video/7212720718847642926](https://api.douyin.wtf/api?url=https://www.tiktok.com/@overtime/video/7212720718847642926)

**Comment by Evil0ctal** [comment]
Server IP had been blocked

**Comment by max-lychko** [comment]
@Evil0ctal is this possible to fix?

**Comment by Evil0ctal** [comment]
Yes, need to redeploy and change the server IP, will fix this soon.

**Comment by max-lychko** [comment]
@Evil0ctal thank you very much, I'll wait for the fix

**Comment by Evil0ctal** [comment]
Good, I will close the issue when everything done, or you can deploy this project to your own server and make API call.

**Comment by max-lychko** [comment]
@Evil0ctal ok, thanks for the advice about deploying on my server, I'll think about it

**Comment by Evil0ctal** [comment]
Fixed
