### ISSUE TITLE
[Feature request] tiktok slide images

### ISSUE THREAD

**Issue by Sansekai** [Evil0ctal/Douyin_TikTok_Download_API#218]
**Is your feature request related to a problem? Please describe.**
when I want to download a slide image from tiktok but audio appears

**Describe the solution you'd like**
I want the result to be an array of slide image links

**Describe alternatives you've considered**
when I want to download a slide image from tiktok but audio appears

**Additional context**
I have example url https://vt.tiktok.com/ZSLSYb3sb/

Sorry my english so bad

**Comment by Evil0ctal** [comment]
Can you give me more detail about you issue?

**Comment by Sansekai** [comment]
@Evil0ctal example
![Screenshot_20230809_164035_Chrome](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/34540627/6e7e3d19-c755-485c-adde-b0107c5daaec)

**Comment by Evil0ctal** [comment]
Already supported via: https://douyin.wtf
