### ISSUE TITLE
清晰的不高 考虑换接口吗？

### ISSUE THREAD

**Issue by 2478641181** [Evil0ctal/Douyin_TikTok_Download_API#220]
如题 
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/92560664/81dc2dbe-0e38-4f31-8115-6437dbf0bbee)

**Comment by Evil0ctal** [comment]
可以，第二个视频你是在哪里下载的。

**Comment by 2478641181** [comment]
> 可以，第二个视频你是在哪里下载的。

 http://124.220.15.161:80

**Comment by 2478641181** [comment]
> > 可以，第二个视频你是在哪里下载的。http://124.220.15.161

这是我二改完的一个项目 大佬看看源码

**Comment by Evil0ctal** [comment]
可以，我去看一下他这个仓库的功能。

**Comment by 2478641181** [comment]
> 可以，我去看一下他这个仓库的功能。

https://dy.hejin520.xyz
可以直接用我搭建好的接口

**Comment by Evil0ctal** [comment]
目前好像有两个功能可以加入：
- 更换视频文件play_address
- 支持主页视频解析

你觉得还有什么功能需求可以添加？

**Comment by Evil0ctal** [comment]
请使用最新的V4.0.0版本。
