### ISSUE TITLE
[BUG] Docker部署请求失败

### ISSUE THREAD

**Issue by Ora2** [Evil0ctal/Douyin_TikTok_Download_API#222]
本地运行了几个月之后，最近就无法访问了，同样的链接，在wtf域名的80可以解析，docker的80会显示：

获取视频ID失败！
Input value: https://v.douyin.com/iyr9xcb/

本地Docker8000的API也无法正常运行了。
大佬你的80是可以用的，但https://api.douyin.wtf又开始500了。

是不是我IP被ban了？:(

**Comment by Evil0ctal** [comment]
可能是的，换一台机器重新部署一下看看。

**Comment by Evil0ctal** [comment]
可以看一下：api.tikhub.io
