### ISSUE TITLE
[BUG] 显示conversion error

### ISSUE THREAD

**Issue by sharonge0525** [Evil0ctal/Douyin_TikTok_Download_API#223]
***发生错误的平台？***

tiktok 抖音

***发生错误的端点？***

ios shortcut

***提交的输入值？***

直接复制的短视频链接 尝试了很多不同的都不行
例子 https://vm.tiktok.com/ZT8d4fnnx/

***是否有再次尝试？***

是 发现好像之前是不是出现过这个问题 是不是修复过还是这样

***你有查看本项目的自述文件或接口文档吗？***

有 显示conversion error
get dictionary from input failed
b/c shortcuts couldn't convert text to dictionary 

当前链接解析失败 dictionary value无法转化

**Comment by Evil0ctal** [comment]
服务器IP被block了，已经解决了。
