### ISSUE TITLE
获取用户主页作品接口返回出现错误

### ISSUE THREAD

**Issue by unknownUser99999** [Evil0ctal/Douyin_TikTok_Download_API#224]
https://api.tikhub.io/douyin/user_profile_videos_data
这个接口返回{"status":false,"platform":"douyin","endpoint":"/douyin/user_profile_videos_data/","total_time":null,"message":"解析失败，检查参数/Parse failed, check parameters","video_id":null,"sec_user_id":null,"has_more":null,"cursor":null,"next_url":null,"count":null,"aweme_list":null}
很奇怪，最近百分99的时候都返回的是这个，突然有一二次返回的是正常的。

**Comment by unknownUser99999** [comment]
这个参数是你这边设置返回的， 还是我被别人篡改流量了，我怀疑

**Comment by Evil0ctal** [comment]
你好，这个是我们服务器的问题，最近抖音更新了Web端的验证码逻辑，我们在想办法进行相应的处理，在下一个大版本更新中我们会将TikHub代码进行拆分，你可以自己部署客户端在自己的服务器。

**Comment by unknownUser99999** [comment]
> 

可是为啥有时候可以有时候不可以，这和验证逻辑没关系吧

**Comment by unknownUser99999** [comment]
> 你好，这个是我们服务器的问题，最近抖音更新了Web端的验证码逻辑，我们在想办法进行相应的处理，在下一个大版本更新中我们会将TikHub代码进行拆分，你可以自己部署客户端在自己的服务器。

可是为啥有时候可以有时候不可以，这和验证逻辑没关系吧

**Comment by Evil0ctal** [comment]
有的时候没有被验证码拦，有的时候验证码会出来，你打开网页版抖音浏览个人主页就知道了。

**Comment by unknownUser99999** [comment]
> 



> 有的时候没有被验证码拦，有的时候验证码会出来，你打开网页版抖音浏览个人主页就知道了。

网页版是一次都不行

**Comment by bxiaoj** [comment]
> 这个参数是你这边设置返回的， 还是我被别人篡改流量了，我怀疑

推荐下[video-parser](https://github.com/bxiaoj/video-parser)可以解决你的问题

**Comment by unknownUser99999** [comment]
> 你好，这个是我们服务器的问题，最近抖音更新了Web端的验证码逻辑，我们在想办法进行相应的处理，在下一个大版本更新中我们会将TikHub代码进行拆分，你可以自己部署客户端在自己的服务器。

我部署在自己的服务器的话，是不是就不需要加签到那个界面的身份token了
