### ISSUE TITLE
如何切换v2以及是否考虑增加一个自动抓取最新视频的功能？

### ISSUE THREAD

**Issue by AIEOV** [Evil0ctal/Douyin_TikTok_Download_API#226]
已经部署好了 现在只有单一解析  没太看懂那个付费的api 购买之后如何替换？我是一键部署到linux  可否简单指导下 
另外是否考虑定时自动抓取某一用户的最新视频，我现在用的一个微博爬虫，定时运行并将之前爬到的结果记录跳过，感觉这个功能很有用

**Comment by Evil0ctal** [comment]
付费的那个是我们的云托管API，修改一下代码替换TikHhb的Token即可，我们现在在写一台客户端软件，晚些时候会支持你要的功能。

**Comment by AIEOV** [comment]
'修改一下代码替换TikHhb的Token'   就是这一步不太懂 是替换web_api.py里的内容吗  
是否有tg群可以交流下

**Comment by Evil0ctal** [comment]
你可以加我们的discord：

https://discord.gg/KgxUQv4Kpy
