### ISSUE TITLE
[BUG] issue with  TikTok video download

### ISSUE THREAD

**Issue by spac3orange** [Evil0ctal/Douyin_TikTok_Download_API#229]
Hello!
First, I want to thank the author for such a wonderful project, but in the process of getting to know him, I had an error related to uploading a video

I am running project in docker desktop

When i insert TikTok video link in WebAPP interface and go to the parsing results page, after clicking on the Video Download-No-Watermark button, I am transferred to the (https://api.douyin.wtf/download?url=https://vt.tiktok.com/ZSL9yE7jq/&prefix=true&watermark=false), where i can see this information:

status | "endpoint closed"
-- | --
message | "此端点已关闭请在配置文件中开启/This endpoint is closed, please enable it in the configuration file"

I am very new with docker so I would appreciate any help
[Thanks!](url)
![Screenshot 2023-07-27 203135](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/131010015/27639661-caff-4742-a754-429c06f55eb2)
![Screenshot 2023-07-27 203115](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/131010015/aa6a7083-0590-45c7-a9f6-0494d0117e7e)
![Screenshot 2023-07-27 203101](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/131010015/c7bcdf05-47cd-4007-a913-ca1e29ac3992)

**Comment by Evil0ctal** [comment]
Hi! 
Thanks for the feedback, so to change the default API, pls go to config.ini, and change this to you own domain or server IP:
https://github.com/Evil0ctal/Douyin_TikTok_Download_API/blob/edf1a93aa54b1442e6512ea5820e5519da02c5bd/config.ini#L32
