### ISSUE TITLE
[BUG] 调用API 提示 无法验证Token，请重新登录

### ISSUE THREAD

**Issue by zhm735554270** [Evil0ctal/Douyin_TikTok_Download_API#231]
***发生错误的平台？***

如：TikTok

调用接口提示
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/19621818/54e6607d-3f22-46e0-bbca-781a807304ac)

![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/19621818/5b9b2a50-6a0a-4843-8ecb-22d4204c0510)

**Comment by zhm735554270** [comment]
token 是调用https://api.tikhub.io/user/login 这个接口拿到的

**Comment by Evil0ctal** [comment]
重新获取一下token。

**Comment by zhm735554270** [comment]
重新获取了也还是提示无法验证  开的国外的代理

**Comment by Evil0ctal** [comment]
代理可能重写请求头了吧，在cookie字段里添加以下代码：

'Authorization=<YOUR_TOKEN>'

**Comment by Evil0ctal** [comment]
已经对这个问题进行了修复，原因是新账户中的requests_remain字段为null，服务器后端的判断函数未对null做处理。
