### ISSUE TITLE
error about get_douyin_video_data

### ISSUE THREAD

**Issue by Crabbit-F** [Evil0ctal/Douyin_TikTok_Download_API#232]
I use the func get_douyin_video_data which from [Douyin_TikTok_Download_API]/scraper.py line 266. But it don't work,I got the 200 code and empty result.

**Comment by Evil0ctal** [comment]
I can't reproduce the issue on my side, can anyone of you provide more context?

**Comment by Crabbit-F** [comment]
This is my code,thanks for your help.

def get_douyin_video_data(video_id: str):
    """

    :param video_id: str - 抖音视频id
    :return:dict - 包含信息的字典
    """
    print('正在获取抖音视频数据...')
    try:
        # 构造访问链接/Construct the access link
        api_url = f"https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=webapp&aid=6383&channel=channel_pc_web&aweme_id={video_id}&pc_client_type=1&version_code=190500&version_name=19.5.0&cookie_enabled=true&screen_width=1344&screen_height=756&browser_language=zh-CN&browser_platform=Win32&browser_name=Firefox&browser_version=110.0&browser_online=true&engine_name=Gecko&engine_version=109.0&os_name=Windows&os_version=10&cpu_core_num=16&device_memory=&platform=PC&webid=7158288523463362079&msToken=abL8SeUTPa9-EToD8qfC7toScSADxpg6yLh2dbNcpWHzE0bT04txM_4UwquIcRvkRb9IU8sifwgM1Kwf1Lsld81o9Irt2_yNyUbbQPSUO8EfVlZJ_78FckDFnwVBVUVK"
        api_url = generate_x_bogus_url(api_url)
        # 访问API/Access API
        print("正在获取视频数据API: {}".format(api_url))
        response = requests.get(api_url, headers=douyin_api_headers, proxies=proxy)
        #response = requests.get(api_url, headers=douyin_api_headers, proxies=proxy)
        response = response.json()
        # 获取视频数据/Get video data
        video_data = response['aweme_detail']
        print('获取视频数据成功！')
        # print("抖音API返回数据: {}".format(video_data))
        print(video_data)
        #return video_data
    except Exception as e:
        print('获取抖音视频数据失败！原因:{}'.format(e))
        # return None
        raise e

**Comment by Evil0ctal** [comment]
Can you print the response text?

If text is null, make sure that your server IP is able to access Douyin website, you can use proxy to do that.

**Comment by Crabbit-F** [comment]
Whether use proxy or not,the response content is empty.
![tiktokresponse](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/52477243/3c750409-c7a8-42a9-b105-323c13ee9e8d)

**Comment by Evil0ctal** [comment]
Use the US proxies and try again.

**Comment by bxiaoj** [comment]
> I use the func get_douyin_video_data which from [Douyin_TikTok_Download_API]/scraper.py line 266. But it don't work,I got the 200 code and empty result.

[video-parser](https://github.com/bxiaoj/video-parser/), may be able to help you solve the problem, worth trying.

**Comment by Crabbit-F** [comment]
US proxies can't resolve this question.Is it JSON parsing error？

**Comment by Evil0ctal** [comment]
I'm not sure, could you print the response.text to see what does the server response?

**Comment by Crabbit-F** [comment]
All right.Thanks a lot.
