### ISSUE TITLE
https://api.douyin.wtf/api?url=  查询不了视频播放量吗？

### ISSUE THREAD

**Issue by hhfmiirvaxb943** [Evil0ctal/Douyin_TikTok_Download_API#236]
https://api.douyin.wtf/api?url=  查询不了视频播放量吗？

**Comment by Evil0ctal** [comment]
如果抖音的API没有返回，就是拿不到。

**Comment by bxiaoj** [comment]
> https://api.douyin.wtf/api?url= 查询不了视频播放量吗？

[video-parser](https://github.com/bxiaoj/video-parser/), may be able to help you solve the problem, worth trying.
