### ISSUE TITLE
[BUG] 一键部署报错

### ISSUE THREAD

**Issue by cqLJH** [Evil0ctal/Douyin_TikTok_Download_API#237]
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/52238648/4b817db4-fc8b-4b89-8113-c3b3e8b3420a)

Run API or Web? [api/web/all/quit] all
Do you want to start the app and api service when system boot? [y/n] y
Created symlink from /etc/systemd/system/multi-user.target.wants/web_app.service to /etc/systemd/system/web_app.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/web_api.service to /etc/systemd/system/web_api.service.
Starting WEB and API Services...
Failed to start web_app.service: Unit is not loaded properly: Invalid argument.
See system logs and 'systemctl status web_app.service' for details.
Failed to start web_api.service: Unit is not loaded properly: Invalid argument.
See system logs and 'systemctl status web_api.service' for details.
API and APP service are running!
You can stop the api service by running following command: 
systemctl stop (web_app.service||web_api.service)
[root@glory ~]# systemctl status web_api.service
● web_api.service - www/wwwroot/Douyin_TikTok_Download_API/web_api.py deamon
   Loaded: error (Reason: Invalid argument)
   Active: inactive (dead)

Aug 11 09:32:44 glory systemd[1]: [/etc/systemd/system/web_api.service:10] Executable path is not absolute, ignoring: python3 web_api.py
Aug 11 09:32:44 glory systemd[1]: web_api.service lacks both ExecStart= and ExecStop= setting. Refusing.
Aug 11 09:32:44 glory systemd[1]: [/etc/systemd/system/web_api.service:10] Executable path is not absolute, ignoring: python3 web_api.py
Aug 11 09:32:44 glory systemd[1]: web_api.service lacks both ExecStart= and ExecStop= setting. Refusing.

**Comment by Evil0ctal** [comment]
请使用Ubuntu进行部署。
