### ISSUE TITLE
No such file or directory: './X-Bogus.js

### ISSUE THREAD

**Issue by dfinity-web3** [Evil0ctal/Douyin_TikTok_Download_API#238]
运行示例程序：
import asyncio
from douyin_tiktok_scraper.scraper import Scraper

api = Scraper()

async def hybrid_parsing(url: str) -> dict:
    # Hybrid parsing(Douyin/TikTok URL)
    result = await api.hybrid_parsing(url)
    print(f"The hybrid parsing result:\n {result}")
    return result

asyncio.run(hybrid_parsing(url=input("Paste Douyin/TikTok share URL here: ")))

输入 给的例子网址：
https://v.douyin.com/L4FJNR3/

结果：
当前链接平台为:douyin
正在获取视频ID...
正在通过抖音分享链接获取原始链接...
获取原始链接成功, 原始链接为: https://www.iesdouyin.com/share/video/6918273131559881997/
获取到的抖音视频ID为: 6918273131559881997
获取视频ID成功,视频ID为:6918273131559881997
正在获取视频数据...
正在获取抖音视频数据...
获取抖音视频数据失败！原因:[Errno 2] No such file or directory: './X-Bogus.js'

**Comment by Evil0ctal** [comment]
检测你的本地文件：

原因:[Errno 2] No such file or directory: './X-Bogus.js'
