### ISSUE TITLE
为啥部署了之后，我发现没法获取抖音用户主页数据

### ISSUE THREAD

**Issue by ghost** [Evil0ctal/Douyin_TikTok_Download_API#239]
是这个接口现在不能正常工作吗/douyin/user_profile_videos_data

**Comment by Evil0ctal** [comment]
可以的

**Comment by unknownUser99999** [comment]
> 可以的

返回

detail  "Not Found"

**Comment by unknownUser99999** [comment]
> 可以的
http://127.0.0.1:8000/douyin/user_profile_videos_data%20?douyin_user_url=https://www.douyin.com/user/MS4wLjABAAAAeGnLoM4pD1QBmO1h0IkzAxlhFm9PT7VRss3kUCAxky4&cursor=0&count=20

**Comment by unknownUser99999** [comment]
> 可以的

http://127.0.0.1:8000/douyin/user_profile_videos_data?douyin_user_url=https://www.douyin.com/user/MS4wLjABAAAAQWAcqcLyPbofnLeelBjvBHxOEWf1rvvjz6vLlD-trfU&cursor=0&count=20

**Comment by Evil0ctal** [comment]
晚些时候我会修复这个问题。

**Comment by unknownUser99999** [comment]
> 

谢了

**Comment by tlament** [comment]
请问这个问题解决了吗

**Comment by Evil0ctal** [comment]
api.tikhub.io

**Comment by unknownUser99999** [comment]
> api.tikhub.io

现在是解决了吗，可是我看docker镜像并没有更新啊

**Comment by Evil0ctal** [comment]
需要手动从api.tikhub.io调用接口。

**Comment by unknownUser99999** [comment]
> 需要手动从api.tikhub.io调用接口。

域名就是api,tikhub,io是吧，接口后面的地址还是以前文档上写的是吧

**Comment by Evil0ctal** [comment]
请使用最新的V4.0.0版本。
