### ISSUE TITLE
测试的时候发生错误，没法下载

### ISSUE THREAD

**Issue by 110wuqu** [Evil0ctal/Douyin_TikTok_Download_API#24]
D:\Anaconda3\envs\titok\python.exe D:/project/Douyin_TikTok_Download_API/test.py

在此输入TikTok分享口令/链接：https://www.tiktok.com/@martinalynnnn/video/7033880938924739846?is_copy_url=1&is_from_webapp=v1&q=%23coversong&t=1652695567630
目标链接:  https://www.tiktok.com/@martinalynnnn/video/7033880938924739846?is_copy_url=1&is_from_webapp=v1&q=%23coversong&t=1652695567630
获取到的TikTok视频ID是7033880938924739846
\{'status': 'failed', 'reason': ProxyError(MaxRetryError("HTTPSConnectionPool(host='www.tiktok.com', port=443): Max retries exceeded with url: /@martinalynnnn/video/7033880938924739846?is_copy_url=1&is_from_webapp=v1&q=%23coversong&t=1652695567630 (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))")), 'function': 'Scraper.tiktok()', 'value': 'https://www.tiktok.com/@martinalynnnn/video/7033880938924739846?is_copy_url=1&is_from_webapp=v1&q=%23coversong&t=1652695567630'}

Process finished with exit code 0

**Comment by 110wuqu** [comment]
https://douyin.wtf/ 上点下载也不行
{"Reason":"This API is disabled. To enable it, set the value of \"api_switch\" to True.","Status":"Failed"}

**Comment by Evil0ctal** [comment]
> https://douyin.wtf/ 上点下载也不行
> 
> {"Reason":"This API is disabled. To enable it, set the value of \"api_switch\" to True.","Status":"Failed"}

你好，这个API在演示站点被关闭了。
