### ISSUE TITLE
[Feature request] 根据搜索关键词进行批量视频下载

### ISSUE THREAD

**Issue by zhangj1an** [Evil0ctal/Douyin_TikTok_Download_API#241]
你们的API非常好！感谢开发！请问能不能添加一个根据搜索关键词进行批量视频下载的功能？

我最近在收集egocentric类的家用电器操作视频, 抖音作为信息源，质量挺好的，可是光用hashtag检索有点不够。谢谢！

**Comment by Evil0ctal** [comment]
没有问题的，TikHub的API已经支持了常规的搜索功能，我们现在在重写新的dashboard，你需要的这个功能可以合并起来。

**Comment by navinwen** [comment]
> 没有问题的，TikHub的API已经支持了常规的搜索功能，我们现在在重写新的dashboard，你需要的这个功能可以合并起来。

感谢大大，在下也在需要通过关键词进行批量爬取的功能！

**Comment by xinmans** [comment]
现在的dashboard支持批量下载吗？一个个点击很麻烦

**Comment by Evil0ctal** [comment]
那个功能已经在写了

**Comment by xinmans** [comment]
是否支持后台配置某个用户的douyin 主页link，然后自动定期刷新下载发布的视频》？

**Comment by Evil0ctal** [comment]
tikhub.io

**Comment by darvsum** [comment]
@Evil0ctal  关键词搜索的接口做好了吗？搜了下文档没找到。

**Comment by darvsum** [comment]
@Evil0ctal  关键词搜索的接口做好了吗？搜了下文档没找到。

**Comment by Evil0ctal** [comment]
已经有了，但是在闭源的接口文档里：

api.tikhub.io

**Comment by darvsum** [comment]
@Evil0ctal 
这个接口计划开源吗

**Comment by Evil0ctal** [comment]
目前暂时不会
