### ISSUE TITLE
how to download the videos etc - what is the command that I need to run

### ISSUE THREAD

**Issue by ayushi0803** [Evil0ctal/Douyin_TikTok_Download_API#242]
***Platform where the error occurred?***

Such as: Douyin/TikTok

***The endpoint where the error occurred?***

Such as: API-V1/API-V2/Web APP

***Submitted input value?***

Such as: video link

***Have you tried again?***

Such as: Yes, the error still exists after X time after the error occurred.

***Have you checked the readme or interface documentation for this project?***

Such as: Yes, and it is very sure that the problem is caused by the program.

**Comment by Evil0ctal** [comment]
What happened?

**Comment by ayushi0803** [comment]
just not able to download - keeps saying it failed - also I can only speak English so I am using a translator to go through everything - I just need a command that I can run to download things!

**Comment by Evil0ctal** [comment]
You can manually save the file, hold the video and save.

**Comment by ayushi0803** [comment]
how do I run the file once I have done that?
