### ISSUE TITLE
我用cloudflare解析了域名，为什么无法访问，是不是我使用了泛解析，还是证书问题？

### ISSUE THREAD

**Issue by tiermove** [Evil0ctal/Douyin_TikTok_Download_API#243]
***发生错误的平台？***

如：抖音/TikTok

***发生错误的端点？***

如：API-V1/API-V2/Web APP

***提交的输入值？***

如：短视频链接

***是否有再次尝试？***

如：是，发生错误后X时间后错误依旧存在。

***你有查看本项目的自述文件或接口文档吗？***

如：有，并且很确定该问题是程序导致的。

**Comment by tiermove** [comment]
我用ip+80能正常访问

**Comment by Evil0ctal** [comment]
请提供上下文，如http代码，另外这个问题听起来跟ssl有关，建议你去cloudflare的社区进行提问，这个问题与本仓库无关。

**Comment by zuosc** [comment]
同样的问题。套了CF以后就无法正常使用了，  目前看出来是wss无法正常使用导致的。  但是为什么wss失败不知道原因。
