### ISSUE TITLE
tiktok正常，抖音出现错误，这种情况是服务器问题吗？我用的日本服务器，用cloudflare做了泛解析！

### ISSUE THREAD

**Issue by tiermove** [Evil0ctal/Douyin_TikTok_Download_API#244]
***Platform where the error occurred?***

Such as: Douyin/TikTok

***The endpoint where the error occurred?***

Such as: API-V1/API-V2/Web APP

***Submitted input value?***

Such as: video link

***Have you tried again?***

Such as: Yes, the error still exists after X time after the error occurred.

***Have you checked the readme or interface documentation for this project?***

Such as: Yes, and it is very sure that the problem is caused by the program.

**Comment by tiermove** [comment]
当前链接平台为:douyin
正在获取视频ID...
正在通过抖音分享链接获取原始链接...
获取原始链接成功, 原始链接为: https://www.iesdouyin.com/share/video/7268233830249581865/
获取到的抖音视频ID为: 7268233830249581865
获取视频ID成功,视频ID为:7268233830249581865
正在获取视频数据...
正在获取抖音视频数据...
获取抖音视频数据失败！原因:TypeError: Cannot read property 'JS_MD5_NO_COMMON_JS' of null
正在获取抖音视频数据...
获取抖音视频数据失败！原因:TypeError: Cannot read property 'JS_MD5_NO_COMMON_JS' of null
正在获取抖音视频数据...
获取抖音视频数据失败！原因:TypeError: Cannot read property 'JS_MD5_NO_COMMON_JS' of null
正在获取抖音视频数据...
获取抖音视频数据失败！原因:TypeError: Cannot read property 'JS_MD5_NO_COMMON_JS' of null

**Comment by tiermove** [comment]
正常tiktok当前链接平台为:tiktok
正在获取视频ID...
该链接为原始链接,无需转换,原始链接为: https://www.tiktok.com/@goha_magical/video/7232703374053920026?is_from_webapp=1&sender_device=pc
获取到的TikTok视频ID是7232703374053920026
获取视频ID成功,视频ID为:7232703374053920026
正在获取视频数据...
正在获取TikTok视频数据...
正在获取视频数据API: https://api16-normal-c-useast1a.tiktokv.com/aweme/v1/feed/?aweme_id=7232703374053920026
获取视频信息成功！
获取视频数据成功，正在判断数据类型...
数据类型代码: 0
数据类型: video
准备开始判断并处理数据...
正在处理TikTok视频数据...

**Comment by diowcnx** [comment]
I got the Cloudflare connection timeout too. Error code 522

**Comment by Evil0ctal** [comment]
> 当前链接平台为:douyin 正在获取视频ID... 正在通过抖音分享链接获取原始链接... 获取原始链接成功, 原始链接为: [iesdouyin.com/share/video/7268233830249581865](https://www.iesdouyin.com/share/video/7268233830249581865/) 获取到的抖音视频ID为: 7268233830249581865 获取视频ID成功,视频ID为:7268233830249581865 正在获取视频数据... 正在获取抖音视频数据... 获取抖音视频数据失败！原因:TypeError: Cannot read property 'JS_MD5_NO_COMMON_JS' of null 正在获取抖音视频数据... 获取抖音视频数据失败！原因:TypeError: Cannot read property 'JS_MD5_NO_COMMON_JS' of null 正在获取抖音视频数据... 获取抖音视频数据失败！原因:TypeError: Cannot read property 'JS_MD5_NO_COMMON_JS' of null 正在获取抖音视频数据... 获取抖音视频数据失败！原因:TypeError: Cannot read property 'JS_MD5_NO_COMMON_JS' of null

这个报错请安装nodejs环境

**Comment by Evil0ctal** [comment]
> I got the Cloudflare connection timeout too. Error code 522

Fixed

**Comment by tiermove** [comment]
> > 当前链接平台为:douyin 正在获取视频ID... 正在通过抖音分享链接获取原始链接... 获取原始链接成功, 原始链接为: [iesdouyin.com/share/video/7268233830249581865](https://www.iesdouyin.com/share/video/7268233830249581865/) 获取到的抖音视频ID为: 7268233830249581865 获取视频ID成功,视频ID为:7268233830249581865 正在获取视频数据... 正在获取抖音视频数据... 获取抖音视频数据失败！原因:TypeError: Cannot read property 'JS_MD5_NO_COMMON_JS' of null 正在获取抖音视频数据... 获取抖音视频数据失败！原因:TypeError: Cannot read property 'JS_MD5_NO_COMMON_JS' of null 正在获取抖音视频数据... 获取抖音视频数据失败！原因:TypeError: Cannot read property 'JS_MD5_NO_COMMON_JS' of null 正在获取抖音视频数据... 获取抖音视频数据失败！原因:TypeError: Cannot read property 'JS_MD5_NO_COMMON_JS' of null
> 
> 这个报错请安装nodejs环境

安装了，
root@tierm:~# nodejs --version
v10.19.0

**Comment by Evil0ctal** [comment]
建议你重新部署至美国地区的服务器，我这边没有足够的上下文判断你的问题。
