### ISSUE TITLE
[BUG]对问题的简要而清晰的描述

### ISSUE THREAD

**Issue by yizhe-629** [Evil0ctal/Douyin_TikTok_Download_API#245]
在网站下载快捷指令
然后抖音分享链接启动快捷指令出现这个

![Uploading 5C35E8E8-C130-4FF6-AFD3-136CCC6D2E9C.png…]()

**Comment by Evil0ctal** [comment]
你好，我这边没有办法看到你的图片。

**Comment by yizhe-629** [comment]
显示未指定url

**Comment by Evil0ctal** [comment]
我这边随机测试了TikTok和抖音的视频分享文本，无法复现你的问题，请提供你输入的URL。

**Comment by Evil0ctal** [comment]
这个问题应该得到解决了
