### ISSUE TITLE
[BUG] 无法下载

### ISSUE THREAD

**Issue by Kwaiyu** [Evil0ctal/Douyin_TikTok_Download_API#248]
<html>
<body>

视频下载-无水印 | 点击下载
-- | --

</body>
</html>
http://api.douyin.wtf/download?url=https://v.douyin.com/iJp9BVd9/&prefix=true&watermark=false

{
"status": "endpoint closed",
"message": "此端点已关闭请在配置文件中开启/This endpoint is closed, please enable it in the configuration file"
}

![IMG_7382(20230822-051110)](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/28617728/7935fc8b-3118-45a4-b61d-24d221e47aeb)
视频下载-无水印	[点击下载](http://api.douyin.wtf/download?url=https://v.douyin.com/iJp9BVd9/&prefix=true&watermark=false)

**Comment by Kwaiyu** [comment]
自部署已解决

**Comment by Evil0ctal** [comment]
好的👍🏻
