### ISSUE TITLE
支持抓douyin 评论吗？

### ISSUE THREAD

**Issue by guCiel** [Evil0ctal/Douyin_TikTok_Download_API#249]
**您的功能请求是否与问题相关？ 如有，请描述。**

如：我在使用xxx时觉得如果可以改进xxx的话会更好。

**描述您想要的解决方案**

如：对您想要发生的事情的清晰简洁的描述。

**描述您考虑过的替代方案**

如：对您考虑过的任何替代解决方案或功能的清晰简洁的描述。

**附加上下文**

在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by Evil0ctal** [comment]
支持

**Comment by Evil0ctal** [comment]
请使用最新的V4.0.0版本。
