### ISSUE TITLE
使用Douyin TikTok Download/Scraper API-V1,抖音单条视频下载进行测试

### ISSUE THREAD

**Issue by chenningxi** [Evil0ctal/Douyin_TikTok_Download_API#250]
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/45838419/2ffc0716-82b8-402e-9201-e3bff2ce321c)
访问接口报500错误
此API 是下架了?

**Comment by Evil0ctal** [comment]
IP被封了，晚点重新部署一下。

**Comment by Evil0ctal** [comment]
已经使用cookie解决了这个问题，请部署最新的代码。
