### ISSUE TITLE
[BUG] 抖音好像在更新X-Bogus加密算法，这两天极不稳定。

### ISSUE THREAD

**Issue by q1016134519** [Evil0ctal/Douyin_TikTok_Download_API#251]
***发生错误的平台？***

如：抖音

通过抓包使用抖音PC网站生成的，带加密参数的url可以正常访问。此项目中的X-Bogus.js文件计算的结果经常出现不可用情况，抖音服务器返回空body0字节。已排除cookie影响。

上次出现这种情况还是去年抖音更新的时候，大佬及时跟进啊！

**Comment by Evil0ctal** [comment]
嗯嗯，需要判断一下加密的方法是否更改了，这两天研究一下。

**Comment by Evil0ctal** [comment]
看了一下，不是xb的问题，你排查一下你个人网络的问题，有可能是你的IP被风控了。

**Comment by q1016134519** [comment]
确实被风控了，最近非常容易被封IP，过个十秒就恢复正常，只能用代理缓解了。

**Comment by Evil0ctal** [comment]
是的👍🏻
