### ISSUE TITLE
[BUG] 获取抖音视频数据失败！原因:0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8',

### ISSUE THREAD

**Issue by SLHE135** [Evil0ctal/Douyin_TikTok_Download_API#252]
***发生错误的平台？***

如：抖音

***发生错误的端点？***
获取抖音视频数据失败！原因:0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://www.douyin.com/aweme/v1/web/aweme/detailform=webapp&aid=6383&channel=channel_pc_web&aweme_id=6981363125752843557&pc_client_type=1&version_code=190500&version_name=19.5.0&cookie_enabled=true&screen_width=1344&screen_height=756&browser_language=zh-CN&browser_platform=Win32&browser_name=Firefox&browser_version=110.0&browser_online=true&engine_name=Gecko&engine_version=109.0&os_name=Windows&os_version=10&cpu_core_num=16&device_memory=&platform=PC&webid=7158288523463362079&msToken=abL8SeUTPa9-EToD8qfC7toScSADxpg6yLh2dbNcpWHzE0bT04txM_4UwquIcRvkRb9IU8sifwgM1Kwf1Lsld81o9Irt2_yNyUbbQPSUO8EfVlZJ_78FckDFnwVBVUVK&X-Bogus=DFSzswSLU5UANnEftxKYq09WcBru')

**Comment by Evil0ctal** [comment]
请使用最新的代码

**Comment by jacktou** [comment]
> 请使用最新的代码

重新拉取安装库，还是上面一样错误，好像视频详细接口不返回JSON数据

**Comment by Evil0ctal** [comment]
使用你自己的cookie替换scraper.py的cookie即可

**Comment by jacktou** [comment]
> 使用你自己的cookie替换scraper.py的cookie即可

🙏，妹子图片很美，技术也很牛，膜拜

**Comment by Evil0ctal** [comment]
:)
