### ISSUE TITLE
[BUG] 简短明了的描述问题

### ISSUE THREAD

**Issue by xhacker5000** [Evil0ctal/Douyin_TikTok_Download_API#254]
***发生错误的平台？***

抖音/

***发生错误的端点？***

api

本机是OK的， 部署到ubuntu上之后
TypeError: Cannot read property 'JS_MD5_NO_COMMON_JS' of null

**Comment by xhacker5000** [comment]
知道问题了
nodejs version too low

**Comment by Evil0ctal** [comment]
👍🏻👍🏻👍🏻
