### ISSUE TITLE
[BUG] douyin下载视频失败

### ISSUE THREAD

**Issue by jackviv** [Evil0ctal/Douyin_TikTok_Download_API#256]
1.按照你视频教程，使用pip安装
`pip install douyin-tiktok-scraper`
2.新建项目 copy readme.md的代码
3.输入抖音链接，提示一下错误

`Paste Douyin/TikTok share URL here: https://v.douyin.com/L4FJNR3/
当前链接平台为:douyin
正在获取视频ID...
正在通过抖音分享链接获取原始链接...
获取原始链接失败！
Cannot connect to host v.douyin.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:992)')]`

请问现在抖音下载功能是否正常？

**Comment by Evil0ctal** [comment]
请尝试讲scraper.py以及X-Bogus.js放到你的项目中手动导入。

**Comment by Evil0ctal** [comment]
另外，这个报错看起来是你的代理出现的问题，属于网络层，你需要自己debug一下。

**Comment by jackviv** [comment]
> 另外，这个报错看起来是你的代理出现的问题，属于网络层，你需要自己debug一下。

解决方法：
使用pip安装不行，直接下载源码，修改源码，在请求的时候添加了下面的参数，可以正常请求了。
`async with aiohttp.ClientSession(connector=aiohttp.TCPConnector(limit=64,verify_ssl=False),trust_env=True) as session:`

具体什么原理不知道

**Comment by Evil0ctal** [comment]
如果你使用的代理对证书进行了修改，则需要加上verify_ssl=False。
