### ISSUE TITLE
解析服务器挂了

### ISSUE THREAD

**Issue by Kwaiyu** [Evil0ctal/Douyin_TikTok_Download_API#259]
打不开
https://api.douyin.wtf/docs
https://api.douyin.wtf/ios

403
"nwm_video_url_HQ": "https://aweme.snssdk.com/aweme/v1/play/?video_id=v0200fg10000cjldjsbc77u2mbvo0cr0&ratio=1080p&line=0",

**Comment by diowcnx** [comment]
Error 522 again today

**Comment by Evil0ctal** [comment]
Fixed
