### ISSUE TITLE
Error 552  api.douyin.wtf

### ISSUE THREAD

**Issue by ceasarXuu** [Evil0ctal/Douyin_TikTok_Download_API#262]
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/50387804/40c02a1b-8e35-4e32-95fc-743fdaf5a263)

**Comment by diowcnx** [comment]
Error 552 happened every a few days. Any solutions to solve this problem for a long term use ? VPN or something??

**Comment by Evil0ctal** [comment]
fixed
