### ISSUE TITLE
引用 X-Bogus.js 的时候，能不能使用绝对路径呢

### ISSUE THREAD

**Issue by Jeffrey-deng** [Evil0ctal/Douyin_TikTok_Download_API#263]
跨模块调用scraper的时候，会出现文件找不到

**Comment by Evil0ctal** [comment]
确实，你看看能不能直接来一个pr，这个问题我当时没想到。

**Comment by Jeffrey-deng** [comment]
> 确实，你看看能不能直接来一个pr，这个问题我当时没想到。

已提交

另外那个cookies是否可以放置在 `config.ini` 中呢，或者用扫码获取

**Comment by Evil0ctal** [comment]
放在config.ini也是可以的，扫码需要进一步逆向。

**Comment by Evil0ctal** [comment]
感谢你的PR，已经Merge了：）
