### ISSUE TITLE
[Feature request] 发现cookie失效的时候，没法下载，需要更新代码，能把cookie的获取也写成方法包含在代码里吗？

### ISSUE THREAD

**Issue by gillbates** [Evil0ctal/Douyin_TikTok_Download_API#265]
最近，一直部署的docker无法解析了。。。一看，原来是cookie需要更新啦。。
https://github.com/Evil0ctal/Douyin_TikTok_Download_API/commit/9addcca7b12d85ea891b69b03dbe3d867ee9fec2

不知道，作者方便把cookie的获取方法也自动化吗？

**Comment by Evil0ctal** [comment]
目前可能要手动改，你可以研究一下自动获取然后pr，最近生病了一直没时间搞。

**Comment by moo611** [comment]
> 目前可能要手动改，你可以研究一下自动获取然后pr，最近生病了一直没时间搞。

手动如何获取到cookie呢？

**Comment by Evil0ctal** [comment]
Hi I just make a new realease fixed this issue, please see the note below:

https://github.com/Evil0ctal/Douyin_TikTok_Download_API/releases/tag/V3.2.1

Thank you all, and have a nice day ❤️
