### ISSUE TITLE
[BUG] X-Bogus.js 算出来的参数是不是已经失效了

### ISSUE THREAD

**Issue by geniuskai** [Evil0ctal/Douyin_TikTok_Download_API#266]
***发生错误的平台？***

如：抖音

X-Bogus.js 算出来的参数X-Bogus 貌似已经不可用了？请求无数据

**Comment by Evil0ctal** [comment]
检查你的cookie或者尝试使用代理。

**Comment by geniuskai** [comment]
没有失效，

**Comment by Evil0ctal** [comment]
是的

**Comment by geniuskai** [comment]
请教大佬一个问题，不知道大佬有没有用过这个接口：https://www.douyin.com/aweme/v1/web/aweme/post/，为什么有的时候接口返回空呢，有时候旧有数据返回，大佬能给个思路吗

**Comment by Evil0ctal** [comment]
那个接口已经不能用了

**Comment by geniuskai** [comment]
那有其他替代接口吗，我试着，一会有数据，一会没数据，这个是请求个人主页作品列表的接口

**Comment by Evil0ctal** [comment]
属于抖音风控，这个必须要自己想办法解决了。

**Comment by geniuskai** [comment]
有什么办法解决吗，给个思路也行

**Comment by Evil0ctal** [comment]
思路很简单，过抖音滑块验证。

**Comment by geniuskai** [comment]
我是直接调用的接口，不知道他什么时候出现滑块啊

**Comment by Evil0ctal** [comment]
你都拿不到数据了，这还看不出来出验证了吗……

**Comment by Evil0ctal** [comment]
如果不返回就是风控了，尝试换IP或者拿新的cookie请求。
