### ISSUE TITLE
[BUG] Discourse page not found

### ISSUE THREAD

**Issue by diowcnx** [Evil0ctal/Douyin_TikTok_Download_API#269]
When proceed download link. Page doesn't exist reported.

![Screenshot 2566-09-11 at 14 18 30](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/33758700/33e1cb20-92b2-4589-ac6f-f579808cad0f)

**Comment by Evil0ctal** [comment]
The server IP got took over few days ago, already fixed.
