### ISSUE TITLE
获取抖音视频数据失败！原因:SyntaxError: 缺少 ';'

### ISSUE THREAD

**Issue by shimxx** [Evil0ctal/Douyin_TikTok_Download_API#270]
安装解析库：pip install douyin-tiktok-scraper
使用示例代码，Win10 本地测试运行成功，同样的脚本放到 Windows Server 2019 以及 Windows Server 2008 报错：
正在获取抖音视频数据...
获取抖音视频数据失败！原因:SyntaxError: 缺少 ';'

Win10的Python版本为：Python 3.11.0
pip安装包版本：Successfully installed Brotli-1.1.0 PyExecJS-1.5.1 douyin-tiktok-scraper-1.2.8 orjson-3.9.7

Windows Server 2019 的Python版本：Python 3.11.3
pip安装包版本：Successfully installed douyin_tiktok_scraper-1.2.8

在Windows Server 2019也尝试换过Python3.8 也是报：获取抖音视频数据失败！原因:SyntaxError: 缺少 ';'
以及在Windows Server 2008 运行也报错：获取抖音视频数据失败！原因:SyntaxError: 缺少 ';'

![39424](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/33460342/bd7913cc-1c42-484d-8388-9480b9911157)
![1088](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/33460342/997fac79-ab4d-45af-8e92-d31bf28ebf16)

**Comment by Evil0ctal** [comment]
安装nodejs环境。
