### ISSUE TITLE
[BUG] 小白求助 按文档直接docker部署后 未找到端口映射，不知道怎么访问

### ISSUE THREAD

**Issue by gnemgnahz** [Evil0ctal/Douyin_TikTok_Download_API#271]
按文档流程部署docker：
留下config.int和docker-compose.yml文件 执行docker compose up -d后成功运行容器，但8000端口未映射上哈，127.0.0.1:8000 根本访问不了哈，求部署时是还要修改什么吗？

**Comment by kokojacket** [comment]
config.ini修改web端口

**Comment by Evil0ctal** [comment]
如楼上答案😊

**Comment by gnemgnahz** [comment]
> config.ini修改web端口

感谢🙏

**Comment by ChricLu** [comment]
> > config.ini修改web端口
> 
> 感谢🙏

你好，应该修改哪个地方，现在没有config.ini，是config.yaml，yaml文件里哪一句是设置web端口的呢
