### ISSUE TITLE
[Feature request] 可以有发布视频的API接口吗

### ISSUE THREAD

**Issue by ench2** [Evil0ctal/Douyin_TikTok_Download_API#274]
**您的功能请求是否与问题相关？ 如有，请描述。**

如：需要在多平台同时发布相同的短视频，如果提供了发布视频的API 接口，可以减少逆向时间。

**描述您想要的解决方案**

**Comment by Evil0ctal** [comment]
需要进行逆向，目前还没有这个计划，可以定制开发，联系我的discord。
