### ISSUE TITLE
[BUG] 部署到Google Cloud时一切正常，但是部署到Oracle Cloud时却会报错 500: Internal Server Error

### ISSUE THREAD

**Issue by kbk2005** [Evil0ctal/Douyin_TikTok_Download_API#276]
***发生错误的平台？***

如：Oracle Cloud

***发生错误的端点？***

如：API-V1

***提交的输入值？***

如：0.23 12/20 l@c.Nj xsr:/ 复制打开抖音，看看一分钟内环游地球一圈是种什么体验？# 南极圈# 南... https://v.douyin.com/iexvju3V/

***是否有再次尝试？***

如：是，发生错误后任何时间错误依旧存在。

***你有查看本项目的自述文件或接口文档吗？***

如：有。对FastAPI一知半解，可能思路有误，有疑惑求解答。

**Comment by Evil0ctal** [comment]
应该是IP的问题。

**Comment by kbk2005** [comment]
> 应该是IP的问题。

 找到原因了，vps的内存选得太小了。
插空问一个问题：脚本后续更新能添加卸载的命令么？顺道再次感谢无私的奉献。
