### ISSUE TITLE
下载了3.1.7还显示3.1.3版本

### ISSUE THREAD

**Issue by jqsl2012** [Evil0ctal/Douyin_TikTok_Download_API#278]
为什么下载了https://github.com/Evil0ctal/Douyin_TikTok_Download_API/archive/refs/tags/V3.1.7.zip  
然后执行 
curl -X 'GET' \
  'http://127.0.0.1:8000/' \
  -H 'accept: application/json'
还显示是  "Version": "3.1.3" 的版本呢？

**Comment by befantasy** [comment]
一样

**Comment by Evil0ctal** [comment]
我忘记修改版本号了，一会儿修改一下😂

**Comment by 1amfine2333** [comment]
docker也一样。。。

**Comment by Evil0ctal** [comment]
已经修复了
