### ISSUE TITLE
tiktok无法下载无水印视频

### ISSUE THREAD

**Issue by yhqnh** [Evil0ctal/Douyin_TikTok_Download_API#282]
***发生错误的平台？***

如：TikTok

***发生错误的端点？***

如：快捷指令6.0中文版和英文版本

***提交的输入值？***

如：所有的都不能下载

***是否有再次尝试？***

如：是，发生错误后几天后错误依旧存在。

***你有查看本项目的自述文件或接口文档吗？***

如：没有

**Comment by Evil0ctal** [comment]
API已经恢复
