### ISSUE TITLE
[BUG] /tiktok_profile_videos  没有定义get_tiktok_user_profile_videos方法

### ISSUE THREAD

**Issue by wahahababaozhou** [Evil0ctal/Douyin_TikTok_Download_API#284]
***发生错误的平台？***
TikTok  /tiktok_profile_videos/  没有定义get_tiktok_user_profile_videos方法
***发生错误的端点？***

如：API-V1/API-V2/Web APP

***提交的输入值？***

短视频链接

***是否有再次尝试？***

如：是，发生错误后X时间后错误依旧存在。

***你有查看本项目的自述文件或接口文档吗？***

如：有，并且很确定该问题是程序导致的。

**Comment by Evil0ctal** [comment]
请使用:

www.tikhub.io

中的方法进行编写代码请求。
