### ISSUE TITLE
[Feature request] 是否可以支持 https://b23.tv/s9wvl0O 这样bilibili的分享链接？

### ISSUE THREAD

**Issue by befantasy** [Evil0ctal/Douyin_TikTok_Download_API#286]
bilibili app分享时类似 https://b23.tv/s9wvl0O 这样的链接。实际上是个跳转。现在API无法识别，报Internal Server Error

**Comment by Evil0ctal** [comment]
可以检测相应头的代码，如果不等于200则从响应头中的location获取目标链接。

**Comment by Xuenew** [comment]
> bilibili app分享时类似 https://b23.tv/s9wvl0O 这样的链接。实际上是个跳转。现在API无法识别，报Internal Server Error
现在最新版本是可以解析的哈

**Comment by Evil0ctal** [comment]
感谢各位讨论，[b23.tv/s9wvl0O](https://b23.tv/s9wvl0O) 这样的链接已经支持。
