### ISSUE TITLE
docker部署的api失效了

### ISSUE THREAD

**Issue by aweill** [Evil0ctal/Douyin_TikTok_Download_API#287]
1. 通过docker在自己ubuntu上部署的api下载抖音视频，9月25日还可以正常使用，今天发现api用不了了
2. 访问api的子域名显示正常运行的，如下所示
```
API_status | "Running"
Version | "3.1.3"
Update_time | "2023/02/19"
Request_Rate_Limit | "30/minute"
Web_APP | "https://www.douyin.wtf/"
API_V1_Document | "https://api.douyin.wtf/docs"
TikHub_API_Document | "https://api.tikhub.io/docs"
GitHub | "https://github.com/Evil0ctal/Douyin_TikTok_Download_API"
```
3. 以抖音视频链接 https://v.douyin.com/ieoJ2ew2/ 为例，构造并访问形似 https://api.domain.com/api?url=https%3A%2F%2Fv.douyin.com%2FieoJ2ew2%2F&minimal=true 的链接，显示 **Internal Server Error**，然而之前是能正常使用的
4. 测试发现 官方api 文档链接 https://api.douyin.wtf/docs 也无法打开

**Comment by befantasy** [comment]
今天出了同样问题，昨天还可用。

**Comment by Evil0ctal** [comment]
已经对此进行了修复，使用最新代码。
