### ISSUE TITLE
[BUG] 抖音解析失败

### ISSUE THREAD

**Issue by ArcherZX** [Evil0ctal/Douyin_TikTok_Download_API#288]
***发生错误的平台？***

抖音

***发生错误的端点？***

get_douyin_video_data函数，api构造之后返回的数据是空值

***提交的输入值？***

https://v.douyin.com/idNcvBWW/

**Comment by befantasy** [comment]
今天同样问题，bilibili等其他的正常解析。

**Comment by Evil0ctal** [comment]
请尝试使用自己的抖音cookie对scraper.py文件中的cookie进行替换。

**Comment by Evil0ctal** [comment]
我晚点回对此进行处理

**Comment by befantasy** [comment]
> 请尝试使用自己的抖音cookie对scraper.py文件中的cookie进行替换。

请教这一步如何操作？

**Comment by befantasy** [comment]
搞定了。如果这个cookie经常会过期的话。可否考虑将其做成config.json，修改一下docker-compose.yml，挂载到宿主机上。

**Comment by ArcherZX** [comment]
换cookie可以了，我也觉得频繁换cookie会很麻烦

**Comment by vanjune** [comment]
我好像是帐号被限流了，换了cookie也没用，我也没干啥啊
https://v.douyin.com/idFU3Qyv/
同过视频每次分享的url都不一样，估计后台有记录对应的帐号吧


ValueError: 获取抖音视频数据出错了: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=webapp&aid=6383&channel=channel_pc_web&aweme_id=7284550306283785533&pc_client_type=1&version_code=190500&version_name=19.5.0&cookie_enabled=true&screen_width=1344&screen_height=756&browser_language=zh-CN&browser_platform=Win32&browser_name=Firefox&browser_version=110.0&browser_online=true&engine_name=Gecko&engine_version=109.0&os_name=Windows&os_version=10&cpu_core_num=16&device_memory=&platform=PC&webid=7158288523463362079&msToken=abL8SeUTPa9-EToD8qfC7toScSADxpg6yLh2dbNcpWHzE0bT04txM_4UwquIcRvkRb9IU8sifwgM1Kwf1Lsld81o9Irt2_yNyUbbQPSUO8EfVlZJ_78FckDFnwVBVUVK&X-Bogus=DFSzswSLQsGANnEftOzr2U9WcBrw')
  File "/root/.local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/app/scraper.py", line 346, in get_douyin_video_data
    raise ValueError(f"获取抖音视频数据出错了: {e}")

**Comment by unknownUser99999** [comment]
其他的抖音解析网站好像没问题啊，抖音平台又搞什么鸟操作了吗

**Comment by zhs509** [comment]
@Evil0ctal 昨天测试过自动从浏览器获取cookie。好像只有chrome浏览器的能成功。可以尝试用rookiepy模块获取浏览器cookie。暂时不建议用browser_cookie3，chrome、msedge等浏览器自动更新后，后台有浏览器进程，会导致获取cookie失败。

**Comment by 546200350** [comment]
@Evil0ctal 我这边也不行了，更新了cookie也无效；
我吧接口 https://www.douyin.com/aweme/v1/web/aweme/detail
替换换成 https://www.douyin.com/aweme/v1/web/aweme/related 可以请求到数据

**Comment by yaakua** [comment]
我更换了cookie也不行

**Comment by JimmyLv** [comment]
🤣 我在浏览器里面直接访问都不行呢？（登录状态，带上cookie）

**Comment by javaswing** [comment]
没有解决办法了吗？
🧐🧐🧐

**Comment by 546200350** [comment]
> 没有解决办法了吗？ 🧐🧐🧐

https://www.douyin.com/aweme/v1/web/aweme/related
换成这个接口试试吧，我是用的这个

**Comment by JimmyLv** [comment]
换成这个，然后还要变更cookie哇？ @546200350

**Comment by aweill** [comment]
请问大家，现在这个bug修复好没，docker应用有没有修复更新，部署api是否可以正常使用？

**Comment by Evil0ctal** [comment]
各位就等了，已修复，请使用最新的代码。
