### ISSUE TITLE
[BUG]部署完成了，为啥在网页端一直在Server酱正收到你输入的链接啦！(◍•ᴗ•◍) 正在努力处理中，请稍等片刻...

### ISSUE THREAD

**Issue by a186232641** [Evil0ctal/Douyin_TikTok_Download_API#290]
***发生错误的平台？***

抖音

***发生错误的端点？***

Web APP/

![错误提示](https://cdn.jsdelivr.net/gh/a186232641/images/img/202310062108409.png)

**Comment by Evil0ctal** [comment]
请使用最新的代码。
