### ISSUE TITLE
/tiktok/profile_videos/ 接口无法正常使用

### ISSUE THREAD

**Issue by CodeWhoWrite** [Evil0ctal/Douyin_TikTok_Download_API#295]
平台：tiktok
接口：/tiktok/profile_videos/
参数：
video_url：https://www.tiktok.com/@evil0ctal/video/7156033831819037994
其他参数都是默认参数

返回值：
{
  "status": false,
  "platform": "tiktok",
  "endpoint": "/tiktok/profile_videos/",
  "total_time": null,
  "message": "解析失败，检查参数/Parse failed, check parameters",
  "video_id": null,
  "sec_user_id": null,
  "has_more": null,
  "cursor": null,
  "next_url": null,
  "count": null,
  "aweme_list": null
}

**Comment by avadasma** [comment]
平台：douyin
接口：/douyin/user_profile_videos_data/
{
    "status": false,
    "platform": "douyin",
    "endpoint": "/douyin/user_profile_videos_data/",
    "total_time": null,
    "message": "解析失败，检查参数/Parse failed, check parameters",
    "video_id": null,
    "sec_user_id": null,
    "has_more": null,
    "cursor": null,
    "next_url": null,
    "count": null,
    "aweme_list": null
}

**Comment by Evil0ctal** [comment]
晚点修复一下
