### ISSUE TITLE
[BUG] 获取抖音主页和抖音视频的接口都不能用了

### ISSUE THREAD

**Issue by ghost** [Evil0ctal/Douyin_TikTok_Download_API#296]
还有抖音视频是一定要cookie吗，能看下别人接口怎么实现的吗，他们好像不用cookie,实在不行就算了。主要接口改来改去好麻烦

**Comment by Evil0ctal** [comment]
是的 抖音验证Cookie了

**Comment by unknownUser99999** [comment]
> 是的 抖音验证Cookie了

那获取抖音主页视频的接口呢，哪个不是你们服务器上提供的吗，好像也挂了

**Comment by moo611** [comment]
> 是的 抖音验证Cookie了

请问这个cookie是如何手动获取的？
