### ISSUE TITLE
抖音图集 解析失败

### ISSUE THREAD

**Issue by mrzhaoer** [Evil0ctal/Douyin_TikTok_Download_API#30]
函数名 | 原因 | 输入值

Scraper.douyin() | local variable 'album_music' referenced before assignment | https://v.douyin.com/XXXXXX/

**Comment by Evil0ctal** [comment]
> 函数名 | 原因 | 输入值
> 
> 
> 
> Scraper.douyin() | local variable 'album_music' referenced before assignment | https://v.douyin.com/XXXXXX/
> 
> 
> 
> 

你好，方便提供一下提交值吗？

**Comment by mrzhaoer** [comment]
> 

https://v.douyin.com/F4tV5A1/ 
https://v.douyin.com/F4txL8Y/

**Comment by Evil0ctal** [comment]
> > 
> 
> https://v.douyin.com/F4tV5A1/ https://v.douyin.com/F4txL8Y/

已修复，感谢反馈！
