### ISSUE TITLE
[BUG] 输入bilibili 链接后下载报错 

### ISSUE THREAD

**Issue by Unrealplace** [Evil0ctal/Douyin_TikTok_Download_API#303]
![截屏2023-10-19 21 08 49](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/16250045/7ccf9a93-534c-4aff-bbb5-d7ec3d5c7d91)
![截屏2023-10-19 21 10 03](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/16250045/0230563e-6125-482a-8026-53c24005cc0f)

**Comment by Evil0ctal** [comment]
bilibili的支持暂时移除了
