### ISSUE TITLE
抖音获取那边，一直提示语法错误缺少 “；”

### ISSUE THREAD

**Issue by davinc123** [Evil0ctal/Douyin_TikTok_Download_API#310]
***发生错误的平台？***

如：抖音/TikTok

***发生错误的端点？***

如：API-V1/API-V2/Web APP

***提交的输入值？***

如：短视频链接

***是否有再次尝试？***

如：是，发生错误后X时间后错误依旧存在。

***你有查看本项目的自述文件或接口文档吗？***

如：有，并且很确定该问题是程序导致的。

**Comment by davinc123** [comment]
raise ValueError(f"获取抖音视频数据出错了: {e}")
ValueError: 获取抖音视频数据出错了: SyntaxError: 缺少 ';'

**Comment by davinc123** [comment]
raise ValueError(f"获取抖音视频数据出错了: {e}")
ValueError: 获取抖音视频数据出错了: SyntaxError: 缺少 ';'

**Comment by javaswing** [comment]
> raise ValueError(f"获取抖音视频数据出错了: {e}") ValueError: 获取抖音视频数据出错了: SyntaxError: 缺少 ';'

cookie过期问题，参考[308](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/issues/308)
