### ISSUE TITLE
TikTok work, but douyin fails exception

### ISSUE THREAD

**Issue by androidformax** [Evil0ctal/Douyin_TikTok_Download_API#318]
I saw that many people have such a problem with douyin, so I read it and maybe I'll find a solution there, or I'm waiting for you to answer them.

**Comment by androidformax** [comment]
I saw that many people have such a problem with douyin, so I read it and maybe I'll find a solution there, or I'm waiting for you to answer them.

**Comment by Evil0ctal** [comment]
Use dynamic proxy.

**Comment by Nhaqua** [comment]
@Evil0ctal 
Can I use this type of proxy: IP:port:user:pass?
