### ISSUE TITLE
[BUG] config.ini配置文件中cookie赋值请教

### ISSUE THREAD

**Issue by Yiwei666** [Evil0ctal/Douyin_TikTok_Download_API#319]
1. 注意到新修改的 config.ini 配置文件中新增 cookie 赋值，相关提示信息如下

```
# 抖音cookies配置项
# odin_tt=xxx;sessionid_ss=xxx;ttwid=xxx;passport_csrf_token=xxx;msToken=xxx;
DouYinCookies =
```

2. 打算采用docker部署，请问具体的赋值形式是采用如下字符串形式吗？

```
DouYinCookies = "odin_tt=xxx;sessionid_ss=xxx;ttwid=xxx;passport_csrf_token=xxx;msToken=xxx;"
```

还是采用字典形式？

```
DouYinCookies = {
    'odin_tt': 'xxx',
    'sessionid_ss': 'xxx',
    'ttwid': 'xxx',
    'passport_csrf_token': 'xxx',
    'msToken': 'xxx'
}
```
3. 只需要对以上5个参数进行赋值吗？

非常感谢！

**Comment by sd816224** [comment]
同问

**Comment by javaswing** [comment]
> 1. 注意到新修改的 config.ini 配置文件中新增 cookie 赋值，相关提示信息如下
> 
> ```
> # 抖音cookies配置项
> # odin_tt=xxx;sessionid_ss=xxx;ttwid=xxx;passport_csrf_token=xxx;msToken=xxx;
> DouYinCookies =
> ```
> 
> 2. 打算采用docker部署，请问具体的赋值形式是采用如下字符串形式吗？
> 
> ```
> DouYinCookies = "odin_tt=xxx;sessionid_ss=xxx;ttwid=xxx;passport_csrf_token=xxx;msToken=xxx;"
> ```
> 
> 还是采用字典形式？
> 
> ```
> DouYinCookies = {
>     'odin_tt': 'xxx',
>     'sessionid_ss': 'xxx',
>     'ttwid': 'xxx',
>     'passport_csrf_token': 'xxx',
>     'msToken': 'xxx'
> }
> ```
> 
> 3. 只需要对以上5个参数进行赋值吗？
> 
> 非常感谢！

字符形式即可
