### ISSUE TITLE
好像都不能解析了，

### ISSUE THREAD

**Issue by afycn** [Evil0ctal/Douyin_TikTok_Download_API#321]
一直都在
Server酱正收到你输入的链接啦！(◍•ᴗ•◍)
正在努力处理中，请稍等片刻...

**Comment by Evil0ctal** [comment]
需要使用代理，我晚点加上。

**Comment by ajirocn** [comment]
> 需要使用代理，我晚点加上。

我机子是首尔的，应该不要吧

**Comment by balckduck** [comment]
> 需要使用代理，我晚点加上。

以后都需要代理吗？香港的代理也是<请稍等片刻>

**Comment by 419606974** [comment]
今天又出现这个问题了

**Comment by Evil0ctal** [comment]
Hi I just make a new realease fixed this issue, please see the note below:

https://github.com/Evil0ctal/Douyin_TikTok_Download_API/releases/tag/V3.2.1

Thank you all, and have a nice day ❤️
