### ISSUE TITLE
## iOS Shortcut/快捷指令

### ISSUE THREAD

**Issue by starry2240** [Evil0ctal/Douyin_TikTok_Download_API#324]
## iOS Shortcut/快捷指令

>  快捷指令只需手动安装一次，往后在运行时会自动连接API-V1进行更新检查。

> The shortcut command only needs to be manually installed once, and will automatically connect to API-V1 for update checking at runtime.

> 如果你愿意分享你魔改的快捷方式(捷径)，欢迎在下方留言，我会将你的快捷方式链接收录至此文档内，感谢你的工作(#^.^#)

> If you are willing to share the shortcut of your magic modification, please leave a message below, I will include your shortcut link in this document, thank you for your work (#^.^#)

[V6.0]
Release date: 2022/11/06
中文：
https://www.icloud.com/shortcuts/4465d514869e4ca585074d40328f3e0e
English：
https://www.icloud.com/shortcuts/58e3a2cbac784a6782f1031c6b1dd9f8
Note:
对最新的API-V1进行了适配，必须安装此更新才能正常使用捷径。
Note:
Adapted to the latest API-V1, this update must be installed to use shortcuts normally.

[V5.0]
Release date: 2022/07/18
中文/Chinese：
https://www.icloud.com/shortcuts/331073aca78345cf9ab4f73b6a457f97
英文/English：
https://www.icloud.com/shortcuts/83548306bc0c4f8ea563108f79c73f8d

[V4.0]
Release date: 2022/07/15
中文/Chinese：
https://www.icloud.com/shortcuts/25af5f6d9a9140e1a4e35c771313732f
英文/English：
https://www.icloud.com/shortcuts/0d37a661c1044ce4a428a84c13113c30

[V3.0]
Release date: 2022/04/16
中文/Chinese：
https://www.icloud.com/shortcuts/126820d2783748d1bdec95a223a02639

[V2.0]
Release date: 2022/04/06
中文/Chinese：
https://www.icloud.com/shortcuts/38df6ca6f54840e5af80b98bf52b9c3b

[V1.0]
Release date: 2022/02/06
中文/Chinese：
https://www.icloud.com/shortcuts/e8243369340548efa0d4c1888dd3c170

_Originally posted by @Evil0ctal in https://github.com/Evil0ctal/Douyin_TikTok_Download_API/discussions/104_

**Comment by Evil0ctal** [comment]
Hi I just make a new realease fixed this issue, please see the note below:

https://github.com/Evil0ctal/Douyin_TikTok_Download_API/releases/tag/V3.2.1

Thank you all, and have a nice day ❤️
