### ISSUE TITLE
[BUG] I get other video instead of the one on URL

### ISSUE THREAD

**Issue by Veraokulo** [Evil0ctal/Douyin_TikTok_Download_API#327]
***Platform where the error occurred?***

TikTok

***The endpoint where the error occurred?***

API-V1/API-V2/Web APP

***Submitted input value?***

https://vm.tiktok.com/ZM6c7y6PU/

***Have you tried again?***

Yes
***Have you checked the readme or interface documentation for this project?***

Yes

**Comment by Evil0ctal** [comment]
Hi I just make a new realease fixed this issue, please see the note below:

https://github.com/Evil0ctal/Douyin_TikTok_Download_API/releases/tag/V3.2.1

Thank you all, and have a nice day ❤️
