### ISSUE TITLE
tiktok 失效了

### ISSUE THREAD

**Issue by 5wcx** [Evil0ctal/Douyin_TikTok_Download_API#328]
今天下午失效的
https://api16-normal-c-useast1a.tiktokv.com/aweme/v1/feed/?aweme_id=7328504267440950536 
返回为空

**Comment by nnhutan** [comment]
same problem

**Comment by OFZFZS** [comment]
同样的问题

**Comment by OFZFZS** [comment]
参考https://github.com/yt-dlp/yt-dlp/issues/9441的回答， 需要改成api22-normal-c-useast2a.tiktokv.com

**Comment by Evil0ctal** [comment]
已经将TikTok的API进行更换了，感谢各位的回答。

**Comment by 419606974** [comment]
https://api22-normal-c-useast2a.tiktokv.com/aweme/v1/feed/?aweme_id=7312142533205839136，这个域名返回的也是空了

**Comment by nnhutan** [comment]
any solutions?

**Comment by Evil0ctal** [comment]
Hi I just make a new realease fixed this issue, please see the note below:

https://github.com/Evil0ctal/Douyin_TikTok_Download_API/releases/tag/V3.2.1

Thank you all, and have a nice day ❤️
