### ISSUE TITLE
tiktok api

### ISSUE THREAD

**Issue by johngao01** [Evil0ctal/Douyin_TikTok_Download_API#33]
我想知道这个获取单个作品详细信息 https://api.tiktokv.com/aweme/v1/multi/aweme/detail/?aweme_ids=%5B{}%5D 的api，作者是从那里看到的，代码上的注释是官方api？ 请求解答，感激

**Comment by Evil0ctal** [comment]
> 我想知道这个获取单个作品详细信息 [https://api.tiktokv.com/aweme/v1/multi/aweme/detail/?aweme_ids=%5B{}%5D](https://api.tiktokv.com/aweme/v1/multi/aweme/detail/?aweme_ids=%5B%7B%7D%5D) 的api，作者是从那里看到的，代码上的注释是官方api？ 请求解答，感激

是Google搜出来的。

**Comment by johngao01** [comment]
抖音也有类似的api，我知道有两种，一种是获取单个作品详细信息的，另一个是获取用户作品的。我想tiktok也会有，不知道tiktok获取用户作品的api是什么。我Google 不到
