### ISSUE TITLE
docker版本部署成功之后访问8000端口号不是web页面？

### ISSUE THREAD

**Issue by kdyzm** [Evil0ctal/Douyin_TikTok_Download_API#335]
返回了这个东西：![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/12097910/c91fe8ce-3a83-47d2-b74c-7f72383b0b6e)

web页面该如何访问？
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/12097910/0349a848-4b78-4a8d-a3e2-5ffffacf4fde)

**Comment by Evil0ctal** [comment]
尝试一下8080端口

**Comment by kdyzm** [comment]
> 尝试一下8080端口

![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/12097910/2b6fc31c-b2b1-42b6-848d-6555d07c440a)

启动日志上没显示有8080端口号可用

docker-compose也没有对应的端口配置，这没问题吗，直接使用8080端口号我这边直接报错
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/12097910/db35bda3-b24c-449f-a6fc-b9855057b62d)

**Comment by Evil0ctal** [comment]
Hi I just make a new realease fixed this issue, please see the note below:

https://github.com/Evil0ctal/Douyin_TikTok_Download_API/releases/tag/V3.2.1

Thank you all, and have a nice day ❤️
