### ISSUE TITLE
tiktok失效了

### ISSUE THREAD

**Issue by AmituofoChant** [Evil0ctal/Douyin_TikTok_Download_API#337]
Such as: (https://api22-normal-c-useast2a.tiktokv.com/aweme/v1/feed/?aweme_id=7099005841247948074)

**Comment by xudoyberdi0410** [comment]
same problem

**Comment by 419606974** [comment]
same problem

**Comment by laosanyuan** [comment]
我也遇到了

**Comment by nnhutan** [comment]
我也遇到了

**Comment by Evil0ctal** [comment]
I'm currently working on find the new API.

**Comment by sheldygg** [comment]
https://github.com/sheldygg/aiotiktok

My code is working.

**Comment by Evil0ctal** [comment]
Hi I just make a new realease fixed this issue, please see the note below:

https://github.com/Evil0ctal/Douyin_TikTok_Download_API/releases/tag/V3.2.1

Thank you all, and have a nice day ❤️
