### ISSUE TITLE
tiktok /feed/ is closed now ?

### ISSUE THREAD

**Issue by maatoot** [Evil0ctal/Douyin_TikTok_Download_API#339]
***Platform where the error occurred?***
TikTok

**Comment by sheldygg** [comment]
Now you must send more params with request.
My code is working
https://github.com/sheldygg/aiotiktok

**Comment by Evil0ctal** [comment]
Hi I just make a new realease fixed this issue, please see the note below:

https://github.com/Evil0ctal/Douyin_TikTok_Download_API/releases/tag/V3.2.1

Thank you all, and have a nice day ❤️
