### ISSUE TITLE
老师求教

### ISSUE THREAD

**Issue by Jasper20155** [Evil0ctal/Douyin_TikTok_Download_API#34]
老师请问根据个人主页获取所有视频这个怎么做，不商用仅做毕设学习

**Comment by Evil0ctal** [comment]
> 老师请问根据个人主页获取所有视频这个怎么做，不商用仅做毕设学习

你可以去GitHub上另外一个TikTok download项目仓库看一下代码实现，我一直没做这个功能。

**Comment by johngao01** [comment]
这个我做过，api是https://www.iesdouyin.com/web/api/v2/aweme/post/?sec_uid={sec_uid}&count=21&max_cursor={max_cursor}&aid=1128&_signature={signature}&dytk='

**Comment by Evil0ctal** [comment]
> 这个我做过，api是https://www.iesdouyin.com/web/api/v2/aweme/post/?sec_uid={sec_uid}&count=21&max_cursor={max_cursor}&aid=1128&_signature={signature}&dytk='

哦哦哦，好的，我下次更新到我的仓库里，谢谢啦！

**Comment by Jasper20155** [comment]
> 这个我做过，api是[https://www.iesdouyin.com/web/api/v2/aweme/post/?sec_uid={sec_uid}&count=21&max_cursor={max_cursor}&aid=1128&_signature={signature}&dytk=](https://www.iesdouyin.com/web/api/v2/aweme/post/?sec_uid=%7Bsec_uid%7D&count=21&max_cursor=%7Bmax_cursor%7D&aid=1128&_signature=%7Bsignature%7D&dytk=)'

老师您好，您这个是国内的是吗，我需要的是国际版tictok的那个

**Comment by Evil0ctal** [comment]
> > 这个我做过，api是[https://www.iesdouyin.com/web/api/v2/aweme/post/?sec_uid={sec_uid}&count=21&max_cursor={max_cursor}&aid=1128&_signature={signature}&dytk=](https://www.iesdouyin.com/web/api/v2/aweme/post/?sec_uid=%7Bsec_uid%7D&count=21&max_cursor=%7Bmax_cursor%7D&aid=1128&_signature=%7Bsignature%7D&dytk=)'
> 
> 老师您好，您这个是国内的是吗，我需要的是国际版tictok的那个

我去研究一下，有进展会在这里update

**Comment by Jasper20155** [comment]
> > > 这个我做过，api是[https://www.iesdouyin.com/web/api/v2/aweme/post/?sec_uid={sec_uid}&count=21&max_cursor={max_cursor}&aid=1128&_signature={signature}&dytk=](https://www.iesdouyin.com/web/api/v2/aweme/post/?sec_uid=%7Bsec_uid%7D&count=21&max_cursor=%7Bmax_cursor%7D&aid=1128&_signature=%7Bsignature%7D&dytk=)'
> > 
> > 
> > 老师您好，您这个是国内的是吗，我需要的是国际版tictok的那个
> 
> 我去研究一下，有进展会在这里update

嗯嗯，谢谢老师

**Comment by Evil0ctal** [comment]
你好，已经做出来了。

文档地址：

https://api-v2.douyin.wtf/docs#/

**Comment by tongyan18** [comment]
> 你好，已经做出来了。
> 
> 文档地址：
> 
> https://api-v2.douyin.wtf/docs#/

老哥，这个api是开放代码，只能调你的服务吗

**Comment by Evil0ctal** [comment]
> > 你好，已经做出来了。
> 
> > 
> 
> > 文档地址：
> 
> > 
> 
> > https://api-v2.douyin.wtf/docs#/
> 
> 
> 
> 老哥，这个api是不开放代码，只能调你的服务吗

是的，以后可能会公开。
