### ISSUE TITLE
[BUG]/download无法使用

### ISSUE THREAD

**Issue by MTpupil** [Evil0ctal/Douyin_TikTok_Download_API#342]
***发生错误的平台？***

抖音/TikTok

***发生错误的端点？***

api.douyin.wtf/download

返回信息：{"status":"endpoint closed","message":"此端点已关闭请在配置文件中开启\/This endpoint is closed, please enable it in the configuration file"}

***提交的输入值？***

提交正常参数

***是否有再次尝试？***

自重构以来多次尝试

***你有查看本项目的自述文件或接口文档吗？***

有，并且很确定该问题是程序导致的。

**Comment by Evil0ctal** [comment]
为节省服务器资源 我把这个功能关闭了 手动保存即可
