### ISSUE TITLE
最新版的配置类型问题引起：{"status":"endpoint closed","message":"此端点已关闭请在配置文件中开启/This endpoint is closed, please enable it in the configuration file"}

### ISSUE THREAD

**Issue by cbug404** [Evil0ctal/Douyin_TikTok_Download_API#343]
查看代码这个是字符串类型：
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/154126496/7b5b7db0-cf86-48da-b706-8f04c97a682e)

但配置示例config.yml中这个是布尔型，所以默认不生效
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/154126496/5d21a473-179e-419b-941e-9e53c9afe443)

**Comment by Evil0ctal** [comment]
是的，这个当时忘记修改了，我晚点去修改，感谢反馈！

**Comment by Evil0ctal** [comment]
已修复
