### ISSUE TITLE
[BUG] 视频数据获取失败/Failed to get video data

### ISSUE THREAD

**Issue by c7e715d1b04b17683718fb1e8944cc28** [Evil0ctal/Douyin_TikTok_Download_API#344]
***Platform where the error occurred?***

TikTok

***The endpoint where the error occurred?***

API-V1

***Submitted input value?***

https://www.tiktok.com/@mami_chokin/video/7352055487875140872

***Have you tried again?***

Yes, the error still exists after 48 time after the error occurred.

***Have you checked the readme or interface documentation for this project?***

Yes, and it is very sure that the problem is caused by the program.

**Comment by sheldygg** [comment]
Hello, works fine with my wrapper: https://github.com/sheldygg/aiotiktok
```python
import asyncio

from aiotiktok.client import TikTokClient


async def main():
    client = TikTokClient()

    data = await client.get_video_data(video_url="https://www.tiktok.com/@mami_chokin/video/7352055487875140872")
    print(data)
    await client.close()


asyncio.run(main())
```

**Comment by Evil0ctal** [comment]
> _**Platform where the error occurred?**_
> 
> TikTok
> 
> _**The endpoint where the error occurred?**_
> 
> API-V1
> 
> _**Submitted input value?**_
> 
> [tiktok.com/@mami_chokin/video/7352055487875140872](https://www.tiktok.com/@mami_chokin/video/7352055487875140872)
> 
> _**Have you tried again?**_
> 
> Yes, the error still exists after 48 time after the error occurred.
> 
> _**Have you checked the readme or interface documentation for this project?**_
> 
> Yes, and it is very sure that the problem is caused by the program.

Can you provide me with the logs? I can reproduce the issue

**Comment by axsddlr** [comment]
could be an issue that video maybe asking for a captcha?
