### ISSUE TITLE
[BUG] API Document Page 522

### ISSUE THREAD

**Issue by ReAlign** [Evil0ctal/Douyin_TikTok_Download_API#346]
<img width="917" alt="image" src="https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/25849349/873026f0-a5af-40c6-9f98-1ae7470e6d34">

**Comment by Evil0ctal** [comment]
The server had been down for a while but had been rebooted already, thank you for letting me know:)

**Comment by ReAlign** [comment]
> The server had been down for a while but had been rebooted already, thank you for letting me know:)

Still 522
