### ISSUE TITLE
[Feature request] Can I get the "paid partnership" information of the tiktok video?

### ISSUE THREAD

**Issue by YepJin** [Evil0ctal/Douyin_TikTok_Download_API#347]
**Is your feature request related to a problem? Please describe.**

I found the API can't return the "paid partnership" information of the video. For example, https://www.tiktok.com/@bobbyparrish/video/7249131513927781675, it shows it is a "paid partnership" video, but i can't find this information returned by API. Can you help check this, thanks!
![Screenshot 2024-04-06 122047](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/104165305/3f278328-1ba2-4f00-aaf0-450fef330919)

**Comment by Evil0ctal** [comment]
I believe you can, but is the attachment from web TikTok or App?

**Comment by YepJin** [comment]
It is from the web tiktok, I checked the json file and I found the information, thanks!

**Comment by Evil0ctal** [comment]
Sounds good, glad you find it!
