### ISSUE TITLE
可以出个搭建视频教程

### ISSUE THREAD

**Issue by cenguigui** [Evil0ctal/Douyin_TikTok_Download_API#350]
用的是宝塔面板，不会docker,可以出个视频教程么~

**Comment by esoman888** [comment]
摸索出来了么

**Comment by Evil0ctal** [comment]
使用一键部署脚本，自述文档里有写。

**Comment by esoman888** [comment]
> 使用一键配置脚本，自述文档中有描述。


![截屏2024-04-26 11 38 37](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/45381544/609ba9e2-5d86-4d91-80fd-2c20d988540e)
搭建好了 但是我打不开http://ip:80/docs 服务器已经开放80端口。
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/45381544/77966ac1-d9a3-410c-9506-11983d185945)
配置参数都没动过
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/45381544/91545c5e-d90e-4a58-a5cf-1e1e263b7856)

**Comment by Evil0ctal** [comment]
看一下视频教程：

【【开源项目教程】教你一分钟内部署属于你自己的抖音和TikTok数据接口，可以下载视频，做数据分析等。-哔哩哔哩】 https://b23.tv/MTGT71Z
