### ISSUE TITLE
I want to start with 1 application that can import links @user TikTok and Douyin to download the entire video of the imported user? How much does that cost?

### ISSUE THREAD

**Issue by KalvinThien** [Evil0ctal/Douyin_TikTok_Download_API#351]
I want to start with 1 application that can import links @user TikTok and Douyin to download the entire video of the imported user?
How much does that cost?

**Comment by Evil0ctal** [comment]
https://beta.tikhub.io/

**Comment by 1264967889** [comment]
10000$




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Evil0ctal/Douyin_TikTok_Download_API"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月11日(星期四) 中午11:08
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Evil0ctal/Douyin_TikTok_Download_API] I want to start with 1 application that can import links @user TikTok and Douyin to download the entire video of the imported user? How much does that cost? (Issue #351)





 
I want to start with 1 application that can import links @user TikTok and Douyin to download the entire video of the imported user?
 How much does that cost?

**Comment by Evil0ctal** [comment]
> 10000$
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 
> 发件人:                                                                                                                        "Evil0ctal/Douyin_TikTok_Download_API"                                                                                    ***@***.***&gt;;
> 
> 发送时间:&nbsp;2024年4月11日(星期四) 中午11:08
> 
> ***@***.***&gt;;
> 
> ***@***.***&gt;;
> 
> 主题:&nbsp;[Evil0ctal/Douyin_TikTok_Download_API] I want to start with 1 application that can import links @user TikTok and Douyin to download the entire video of the imported user? How much does that cost? (Issue #351)
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
>  
> 
> I want to start with 1 application that can import links @user TikTok and Douyin to download the entire video of the imported user?
> 
>  How much does that cost?
> 
>  
> 
> —
> 
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

I will take that money right away 😎😎😎

**Comment by KalvinThien** [comment]
For $10,000, I can use the solution to buy software for only $ 200 can download douyin, tiktok, instagram, facebook, youtube ,... Lifetime all in one

**Comment by Evil0ctal** [comment]
That sounds like a good deal, can you send a link here? I wanna take a look
