### ISSUE TITLE
咨询：IPV6的地址无法使用吗

### ISSUE THREAD

**Issue by pubg-Eddie** [Evil0ctal/Douyin_TikTok_Download_API#355]
程序只支持IPV4了吗？我好像也使用过IPV6，但现在使用IPV6是不通的,IPV4是能正常使用的
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/70614635/1016c8a1-0c8d-43b8-845c-68d54becfc43)

**Comment by Evil0ctal** [comment]
这个不确定
