### ISSUE TITLE
[BUG] 根据tiktok的用户首页连接,获取sec_user_id 接口报错500

### ISSUE THREAD

**Issue by Black1874** [Evil0ctal/Douyin_TikTok_Download_API#356]
***发生错误的平台？***

如：TikTok

***发生错误的端点？***

如：TikHub Unofficial 抖音/TikTok/小红书 RESTful API

***提交的输入值？***

如：用户首页地址: https://www.tiktok.com/@gwizzle_

***是否有再次尝试？***

如：是，发生错误后5时间后错误依旧存在。

***你有查看本项目的自述文件或接口文档吗？***

如：有，并且很确定该问题是程序导致的。

**Comment by Evil0ctal** [comment]
请使用最新的V4.0.0版本。
