### ISSUE TITLE
docker部署，开启代理之后无法解析

### ISSUE THREAD

**Issue by KasonWan** [Evil0ctal/Douyin_TikTok_Download_API#357]
docker部署，开启代理之后无法解析
![B2SA2JRURWQER(16D36UJ53](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/58059719/23ba2269-5940-45b0-94c7-15f0bac7feed)

**Comment by Evil0ctal** [comment]
请使用最新的V4.0.0版本。
