### ISSUE TITLE
[question] 付费短剧可以下载么

### ISSUE THREAD

**Issue by demoManito** [Evil0ctal/Douyin_TikTok_Download_API#365]
***Platform where the error occurred?***

- 抖音
https://v.douyin.com/iYcagwYd/
<img width="1047" alt="image" src="https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/27986239/a638e1bb-12eb-4909-b630-81cf52cf41a9">

***The endpoint where the error occurred?***

Such as: API-V1/API-V2/Web APP

***Submitted input value?***

Such as: video link

***Have you tried again?***

Such as: Yes, the error still exists after X time after the error occurred.

***Have you checked the readme or interface documentation for this project?***

Such as: Yes, and it is very sure that the problem is caused by the program.

**Comment by Evil0ctal** [comment]
付费视频需要带上用户的cookie，目前不会计划支持，你可以尝试自行部署然后在config.yaml文件中替换你自己的cookie。

**Comment by demoManito** [comment]
> cookie

thanks
