### ISSUE TITLE
多次请求后报错

### ISSUE THREAD

**Issue by llxbl** [Evil0ctal/Douyin_TikTok_Download_API#369]
![gd](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/24247995/ef36954e-ca15-42d9-b3f0-f2a8e1498ae1)
多次请求抖音链接后失败，是需要更换自己账号cookie吗？还是更换IP？

**Comment by Evil0ctal** [comment]
请在此处更换成你自己的cookie：

https://github.com/Evil0ctal/Douyin_TikTok_Download_API/blob/cfa4b0ce95cc14775a0c843817f92764edfcc773/crawlers/douyin/web/config.yaml#L7
