### ISSUE TITLE
[BUG] 简短明了的描述问题

### ISSUE THREAD

**Issue by Jiohon** [Evil0ctal/Douyin_TikTok_Download_API#371]
***安装依赖库异常***
- 系统：Linux version 5.4.0-96-generic (buildd@lgw01-amd64-051) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) 
- Python：Python 3.8.10
- pip：pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
- ERROR: No matching distribution found for numpy==2.0.0rc1 (from -r requirements.txt (line 17))
<img width="899" alt="image" src="https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/95086492/425f1309-b291-43ea-9aa4-536f5b728a14">

**Comment by Evil0ctal** [comment]
升级一下你的python版本，3.11。

**Comment by Jiohon** [comment]
> 升级一下你的python版本，3.11。

👌  我尝试一下
