### ISSUE TITLE
msToken API错误：timed out

### ISSUE THREAD

**Issue by pubg-Eddie** [Evil0ctal/Douyin_TikTok_Download_API#372]
ERROR    msToken API错误：timed out                                             
INFO     生成虚假的msToken                                                      
INFO:     Will watch for changes in these directories: ['/app']
ERROR:    [Errno 98] Address already in use
ERROR    msToken API错误：timed out                                             
INFO     生成虚假的msToken                                                      
INFO:     Will watch for changes in these directories: ['/app']
ERROR:    [Errno 98] Address already in use
ERROR    msToken API错误：timed out                                             
INFO     生成虚假的msToken

**Comment by Evil0ctal** [comment]
你的80端口是否被占用？

Address already in use

**Comment by pubg-Eddie** [comment]
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/70614635/f48b33e4-92e7-428b-a1c9-57f4f84c12ef)
我的config文件不是80端口，修改了的

**Comment by Evil0ctal** [comment]
使用最新的版本试一下

**Comment by pubg-Eddie** [comment]
> 使用最新的版本试一下

![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/70614635/3abae153-85ad-4bb0-890e-f77be94d493a)
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/70614635/30ceee7c-d6b4-4e9b-ba1e-1e56bf08ce95)
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/70614635/b844d7e9-2cb1-4377-ac1d-f41403bf7338)
已经是最新版了，我看了是19小时前推送的

**Comment by Evil0ctal** [comment]
尝试部署在美国地区的vps试一下

**Comment by Evil0ctal** [comment]
已经拆分了，我这边没有办法复现出你的这个问题。

**Comment by pubg-Eddie** [comment]
挂载卷这里只需要挂载抖音的config文件就行了吗

**Comment by KasonWan** [comment]
我也是这个报错。
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/58059719/e4247c95-b5b1-410d-bc5a-17e7a75acd2b)

**Comment by zuonidelaowang** [comment]
我也是这个错误，这个问题，已经修改端口了。 这个问题有人知道怎么解决吗？
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/16249614/30c3ffc9-0f0d-472b-90da-e2fe32afa7fc)

![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/16249614/6e168cb8-41bd-4a74-b87e-d70f673914a1)
