### ISSUE TITLE
[BUG] msToken 怎么生成

### ISSUE THREAD

**Issue by markvlenvision** [Evil0ctal/Douyin_TikTok_Download_API#374]
启动后

`● Douyin_TikTok_Download_API.service - Douyin_TikTok_Download_API deamon
   Loaded: loaded (/etc/systemd/system/Douyin_TikTok_Download_API.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2024-04-27 10:39:50 UTC; 8s ago
 Main PID: 5067 (python3)
    Tasks: 1 (limit: 23204)
   Memory: 46.4M
   CGroup: /system.slice/Douyin_TikTok_Download_API.service
           └─5067 /usr/local/bin/python3 start.py

Apr 27 10:39:50 CentOS systemd[1]: Started Douyin_TikTok_Download_API deamon.
Apr 27 10:39:59 CentOS python3[5067]: ERROR    msToken API错误：EOF occurred in violation of protocol (_ssl.c:1000)
Apr 27 10:39:59 CentOS python3[5067]: INFO     生成虚假的msToken`

token怎么生成，是在crawlers/douyin/web/config.yaml 里修改吗

**Comment by Evil0ctal** [comment]
使用Ubuntu22以及python3.11将本项目部署在境外服务器（如美国地区）上即可。

**Comment by qcks** [comment]
> 使用Ubuntu22以及python3.11将本项目部署在境外服务器（如美国地区）上即可。

那就是本机不能跑了？

**Comment by Evil0ctal** [comment]
本机可以，我晚点会修复TikTok。

**Comment by Evil0ctal** [comment]
最新版本已经修复了

**Comment by gulangyushaonian** [comment]
请问下你是安装在CentOS系统上吗，requirements.txt文件可以提供看下嘛？谢谢！
