### ISSUE TITLE
直播间的数据流有包含评论及点赞这些数据吗

### ISSUE THREAD

**Issue by yuenwah** [Evil0ctal/Douyin_TikTok_Download_API#375]
测试没拿到这些数据，比如实时评论，送礼物等信息

**Comment by Evil0ctal** [comment]
不会提供这部分的数据支持

**Comment by harrett** [comment]
不会提供，因为这部分是单独销售的：

`直播弹幕 WebSocket 源码
获取完整的直播弹幕 WebSocket 源码，支持 TikTok 和抖音平台。

更新时间：2025年6月13日

[联系购买](https://user.tikhub.io/dashboard/support)`

`
接口名称 | 定价 | 备注
-- | -- | --
WebcastMemberMessage | $140 | 观众进入直播间
WebcastLikeMessage | $140 | 点赞消息
WebcastChatMessage | $224 | 评论弹幕（高价值互动）
WebcastCommonTextMessage | $84 | 普通文本消息
WebcastRoomMessage | $56 | 房间状态通知
WebcastEmojiChatMessage | $84 | 表情包互动
`
