### ISSUE TITLE
[BUG] Cookie风控问题

### ISSUE THREAD

**Issue by kiko923** [Evil0ctal/Douyin_TikTok_Download_API#377]
现在版本很容易风控 导致无法解析 换了cookie之后半个钟又风控了 v3.0的时候的一个cookie可以用一个月多 请问有方法解决吗

**Comment by Evil0ctal** [comment]
我目前还没有遇到这种情况，你先登陆一下web抖音，然后点进随机个人主页然后先刷会儿视频，然后再把cookie替换到配置文件中。

**Comment by lifei6671** [comment]
我也遇到了，哪怕是web版的cookie也会马上被风控，主要表现就是弹出验证码。

**Comment by Evil0ctal** [comment]
请注意请求频率，并且最好使用自己的账号登陆后获取cookie。

**Comment by Evil0ctal** [comment]
请使用V4.0.2版本。

**Comment by Evil0ctal** [comment]
> 非常感谢 我已经订阅了这个仓库 我已经邮件收到更新的4.0.2啦 感谢作者

不客气😊
