### ISSUE TITLE
小白求助，用的方法二，在打开localhost的时候显示failed to load resource怎么解决

### ISSUE THREAD

**Issue by xhj0214** [Evil0ctal/Douyin_TikTok_Download_API#379]
小白求助，用的方法二，在打开localhost的时候显示failed to load resource怎么解决

**Comment by Evil0ctal** [comment]
方便截图看一下吗

**Comment by xhj0214** [comment]
重启电脑之后正常了...

**Comment by jileerliu** [comment]
![微信截图_20240502131324](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/151448891/8d22ef0c-7056-47d4-b62f-5b4d46177ccb)
小白求助，请问这是哪里设置错了吗？

**Comment by xhj0214** [comment]
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/87804710/402c5980-23e2-42f4-ae39-5decc62d08e0)
换个浏览器就复现了，

**Comment by Evil0ctal** [comment]
目测应该是跟本项目使用的包有关系，Pywebio库的静态资源似乎没有被正确加载，我晚点去尝试解决一下。

或者你们可以到PyWebIO的仓库提交issue，也许会有人知道怎么解决。
