### ISSUE TITLE
fetch_user_post_videos 参数无效

### ISSUE THREAD

**Issue by xxccll** [Evil0ctal/Douyin_TikTok_Download_API#380]
***发生错误的平台？***

抖音

***发生错误的端点？***

/api/douyin/web/fetch_user_post_videos

***提交的输入值？***

sec_user_id=MS4wLjABAAAAdA0laclcQnyYhFNhuP3yOWNy1BkeVf3kboZiW9yNIcA
max_cursor 第一次传0,后面全都根据返回的值取

***是否有再次尝试？***

是，当从第一次的返回结果中取到 max_cursor 后再请求，就变成了：
{"code":200,"router":"/api/douyin/web/fetch_user_post_videos","data":{"status_code":0}}

***你有查看本项目的自述文件或接口文档吗？***

有

**Comment by Evil0ctal** [comment]
请问是否是在Demo站点上进行的测试？

**Comment by xxccll** [comment]
不是的, 我是拉取的 evil0ctal/douyin_tiktok_download_api:V4.0.1 的镜像然后在我自己的服务器上部署的

**Comment by Evil0ctal** [comment]
好的，我晚点去复现一下看看是什么原因。

**Comment by xxccll** [comment]
我注意到源码里面的  max_cursor 是用 int 接收的, 但是实际上我用java 测试这个值是 long, 用int 接收会溢出成负数,是这个原因导致的吗?

**Comment by xxccll** [comment]
V4.0.1 这个镜像有这个问题，4fa7ac0 版本的镜像没有这个问题

**Comment by xxccll** [comment]
先关闭了哈

**Comment by xxccll** [comment]
不好意思，这个问题确实还存在，参数是这个：

**Comment by xxccll** [comment]
难道是因为抖音限制了这个接口不登录不能获取更多了吗?那为什么昨天又是好的呢,好奇怪

**Comment by Evil0ctal** [comment]
如果没有返回状态码400，那就是cookie导致的，这部分属于Douyin平台的后端风控，建议你尝试登陆然后选择记住登陆，然后手动过一次验证码后再将cookie填入，你可以参考README文件中的视频教程。

【【开源项目教程】教你一分钟内部署属于你自己的抖音和TikTok数据接口，可以下载视频，做数据分析等。-哔哩哔哩】 https://b23.tv/YCiwXRR

**Comment by Evil0ctal** [comment]
Hi，我刚刚在本地使用旧的Cookie复现了这个问题，但是当你收到过一次验证码之后，第二页就有返回的数据了，总结下来这个问题还是抖音的Web端风控导致的，代码目前看起来一切正常，请尝试过验证码后替换Cookie至config.yaml文件，如果没有问题了的话这个issue就可以关闭了：）
