### ISSUE TITLE
[BUG] Brief and clear description of the problem

### ISSUE THREAD

**Issue by wuye901126** [Evil0ctal/Douyin_TikTok_Download_API#384]
请问我部署在电脑上接口都可访问，唯独/api/hybrid/video_data   和   /api/douyin/fetch_one_video   就提示数据受保护  换了cookies 也是这样

**Comment by Evil0ctal** [comment]
截图我看一下

**Comment by Evil0ctal** [comment]
我这边无法复现你的这个issue，我先把这个issue关闭，有后续再reopen。
