### ISSUE TITLE
[BUG] 好多接口400了

### ISSUE THREAD

**Issue by idcim** [Evil0ctal/Douyin_TikTok_Download_API#385]
***发生错误的平台？***

抖音

***发生错误的端点？***

API-V4.0

***提交的输入值？***
https://douyin.wtf/api/douyin/web/fetch_one_video?aweme_id=7345492945006595379
[短视频链接](https://douyin.wtf/api/douyin/web/fetch_one_video?aweme_id=7345492945006595379)

***是否有再次尝试？***

是，发生错误后错误依旧存在。

**Comment by Evil0ctal** [comment]
晚点修复，demo站点无法保证可用性，请尝试自行部署。
