### ISSUE TITLE
[BUG] 下载抖音视频出现这个问题

### ISSUE THREAD

**Issue by pubg-Eddie** [Evil0ctal/Douyin_TikTok_Download_API#388]
WARNING  第 3 次响应内容为空, 状态码: 200,                                      
         URL:https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=w
         ebapp&aid=6383&channel=channel_pc_web&pc_client_type=1&version_code=190
         500&version_name=19.5.0&cookie_enabled=true&screen_width=1920&screen_he
         ight=1080&browser_language=zh-CN&browser_platform=Win32&browser_name=Fi
         refox&browser_version=124.0&browser_online=true&engine_name=Gecko&engin
         e_version=122.0.0.0&os_name=Windows&os_version=10&cpu_core_num=12&devic
         e_memory=8&platform=PC&msToken=naRsCGXt-XR2vtoRvytaeBv_Dc0_OKs0z5NlUV30
         rFROQhzeWyi09sZOXE2Zb7_-kTCdGsZsFy_ELqQ0VtO9fSeKiQRVvTXiLo1fjdd4FEkelmz
         -ouE_jFLgi1iXrQ==&aweme_id=7352866711739108617&X-Bogus=DFSzswVY6XbANGVR
         tllbge9WX7Jm                                                           
程序出现异常，请检查错误信息。
ERROR    无效响应类型。响应类型: <class 'NoneType'>                             
程序出现异常，请检查错误信息。
INFO:     192.168.31.229:12140 - "GET /api/hybrid/video_data?url=[https://v.douyin.com/iYEXChtF]&minimal=false HTTP/1.1" 400 Bad Request
INFO:     192.168.31.229:12140 - "GET /favicon.ico HTTP/1.1" 404 Not Found

**Comment by shuntan** [comment]
5.0版本什么时候出啊，呜呜～

**Comment by nguyenduclongwin** [comment]
> WARNING 第 3 次响应内容为空, 状态码: 200, URL:https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=w ebapp&aid=6383&channel=channel_pc_web&pc_client_type=1&version_code=190 500&version_name=19.5.0&cookie_enabled=true&screen_width=1920&screen_he ight=1080&browser_language=zh-CN&browser_platform=Win32&browser_name=Fi refox&browser_version=124.0&browser_online=true&engine_name=Gecko&engin e_version=122.0.0.0&os_name=Windows&os_version=10&cpu_core_num=12&devic e_memory=8&platform=PC&msToken=naRsCGXt-XR2vtoRvytaeBv_Dc0_OKs0z5NlUV30 rFROQhzeWyi09sZOXE2Zb7_-kTCdGsZsFy_ELqQ0VtO9fSeKiQRVvTXiLo1fjdd4FEkelmz -ouE_jFLgi1iXrQ==&aweme_id=7352866711739108617&X-Bogus=DFSzswVY6XbANGVR tllbge9WX7Jm 程序出现异常，请检查错误信息。 ERROR 无效响应类型。响应类型: <class 'NoneType'> 程序出现异常，请检查错误信息。 INFO: 192.168.31.229:12140 - "GET /api/hybrid/video_data?url=[https://v.douyin.com/iYEXChtF]&minimal=false HTTP/1.1" 400 Bad Request INFO: 192.168.31.229:12140 - "GET /favicon.ico HTTP/1.1" 404 Not Found

Replace your cookies and the problem will be solved

**Comment by pubg-Eddie** [comment]
> > WARNING 第 3 次响应内容为空, 状态码: 200, URL:https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=w ebapp&aid=6383&channel=channel_pc_web&pc_client_type=1&version_code=190 500&version_name=19.5.0&cookie_enabled=true&screen_width=1920&screen_he ight=1080&browser_language=zh-CN&browser_platform=Win32&browser_name=Fi refox&browser_version=124.0&browser_online=true&engine_name=Gecko&engin e_version=122.0.0.0&os_name=Windows&os_version=10&cpu_core_num=12&devic e_memory=8&platform=PC&msToken=naRsCGXt-XR2vtoRvytaeBv_Dc0_OKs0z5NlUV30 rFROQhzeWyi09sZOXE2Zb7_-kTCdGsZsFy_ELqQ0VtO9fSeKiQRVvTXiLo1fjdd4FEkelmz -ouE_jFLgi1iXrQ==&aweme_id=7352866711739108617&X-Bogus=DFSzswVY6XbANGVR tllbge9WX7Jm 程序出现异常，请检查错误信息。 ERROR 无效响应类型。响应类型: <class 'NoneType'> 程序出现异常，请检查错误信息。 INFO: 192.168.31.229:12140 - "GET /api/hybrid/video_data?url=[https://v.douyin.com/iYEXChtF]&minimal=false HTTP/1.1" 400 Bad Request INFO: 192.168.31.229:12140 - "GET /favicon.ico HTTP/1.1" 404 Not Found
> 
> Replace your cookies and the problem will be solved

What is the format of cookies

**Comment by Evil0ctal** [comment]
You need to get a new cookie from the browser, please check the video link in Read me file.

**Comment by Evil0ctal** [comment]
请先查看此视频：

【【开源项目教程】教你一分钟内部署属于你自己的抖音和TikTok数据接口，可以下载视频，做数据分析等。-哔哩哔哩】 https://b23.tv/lq3NS8z
