### ISSUE TITLE
关于新版本的快捷指令的配置自定义的服务器设置 

### ISSUE THREAD

**Issue by Smecta** [Evil0ctal/Douyin_TikTok_Download_API#390]
（如果修复的话 就不需要下面的内容的配置了）

第一个文本设置成自己的域名(自定义端口需要后面加:自定义的端口）
_比如说` http://192.168.0.1:9090/api/ios/shortcut `下面同样_
`http://192.168.0.1/api/ios/shortcut`

第二个文本设置成自己的域名，此时要修改下url 参考修改一下即可

`http://192.168.0.1/api/hybrid/video_data?url=文本&minimal=true`

第三个地方就是

文本 
video 

下面的判断的地方 有两个地方改一下 1. 这里type ->改成data.type 2.nwm_video_url_HQ -> data.video_data.nwm_video_url_HQ
* 在 rcuts 中获取 data.type 的值 
如果 文本 是 词典值 
  * 在 rcuts 中获取 data.video_data.nwm_video_url_HQ

下面图片的判断也要加 data. image_data.no_watermark_image_list

这样快捷指令就可以用了

**Comment by Evil0ctal** [comment]
是的，根据当前的response修改即可

**Comment by fgprodigal** [comment]
[https://www.icloud.com/shortcuts/114024953bce4723a55c31c7179e1ba7](url)

**Comment by Evil0ctal** [comment]
参考这个快捷指令然后自己重写一下就可以了

**Comment by Smecta** [comment]
> 参考这个快捷指令然后自己重写一下就可以了

好的
