### ISSUE TITLE
现在是不是抖音和tk 都不行了？

### ISSUE THREAD

**Issue by 5wcx** [Evil0ctal/Douyin_TikTok_Download_API#395]
api22-normal-c-alisg.tiktokv.com/aweme/v1/feed
www.douyin.com/aweme/v1/web/aweme/detail  
都没有返回了

**Comment by Evil0ctal** [comment]
第一个目前失效，第二个需要自己修改cookie

**Comment by 5wcx** [comment]
第二个确定可以吗？今天下午失效了  我换cookie也没用，您那边可以？

**Comment by Evil0ctal** [comment]
我这边可以，你看看是不是没有登陆抖音web然后拿cookie

**Comment by PIGNF** [comment]
tiktok的获取失效了

**Comment by yuananf** [comment]
这里还能用
https://beta.tikhub.io/#/TikTok-App-V3-API/fetch_one_video_api_v1_tiktok_app_v3_fetch_one_video_get

**Comment by yuanmomoya** [comment]
> 我这边可以，你看看是不是没有登陆抖音web然后拿cookie

<img width="1336" alt="image" src="https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/34645703/1b7b0a9c-4b96-4313-9c80-4348143a53d8">
我自己部署了一下，修改了cookie，是不是抖音获取单个获取单个作品数据/api/douyin/web/fetch_one_video?aweme_id=7369921631218650409 及抖音的一些接口必须获取一下登陆后的cookie啊，我使用了没有登陆的cookie，借口调用400了

**Comment by aslanTT** [comment]
我这里调用跟你一样的错误，但我点那个链接在浏览器打开其实可以返回数据

**Comment by aslanTT** [comment]
> > 我这边可以，你看看是不是没有登陆抖音web然后拿cookie
> 
> <img alt="image" width="1336" src="https://private-user-images.githubusercontent.com/34645703/331792355-1b7b0a9c-4b96-4313-9c80-4348143a53d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMzA2NjEsIm5iZiI6MTcxNjAzMDM2MSwicGF0aCI6Ii8zNDY0NTcwMy8zMzE3OTIzNTUtMWI3YjBhOWMtNGI5Ni00MzEzLTljODAtNDM0ODE0M2E1M2Q4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDExMDYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2YzkwMzFiOTIyZGMwMjU3ODE2MGY0MTc5ZTIxM2M4NWE3MzNjZTYwODAzNjE5NTk2NWUzYTQ1MTAwZTQwNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aNAMOVf9wjW4JfW46ytSrIu2g1yCmhyxF2pr577Y_As"> 我自己部署了一下，修改了cookie，是不是抖音获取单个获取单个作品数据/api/douyin/web/fetch_one_video?aweme_id=7369921631218650409 及抖音的一些接口必须获取一下登陆后的cookie啊，我使用了没有登陆的cookie，借口调用400了


我这里调用跟你一样的错误，但我点那个链接在浏览器打开其实可以返回数据

**Comment by Evil0ctal** [comment]
最好使用已经登陆过的cookie，抖音web风控现在越来越严格了，请各位自己解决一下，感谢理解。

**Comment by aslanTT** [comment]
> 最好使用已经登陆过的cookie，抖音web风控现在越来越严格了，请各位自己解决一下，感谢理解。

我抖音还可以，tiktok 换了最新的cookie也还是不行，cookie是从web上登录后获取的

**Comment by isaackogan** [comment]
hi, just to be clear: this endpoint no longer works without login?

**Comment by Evil0ctal** [comment]
You need to login to Douyin Web site to get more stable API.

**Comment by isaackogan** [comment]
Do you have a link to documentation for how to do that? I am using US TikTok. I do not know how to implement login.

**Comment by Evil0ctal** [comment]
请使用V4.0.2版本。
