### ISSUE TITLE
更新后很不稳定啊，有什么办法能解决吗？ 看图

### ISSUE THREAD

**Issue by zuonidelaowang** [Evil0ctal/Douyin_TikTok_Download_API#396]
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/16249614/52fb1270-fa38-4fc9-aee2-87dcf42b1e28)

**Comment by Evil0ctal** [comment]
这个是你的网络原因造成的，跟代码没有关系。

**Comment by zuonidelaowang** [comment]
哦哦 好的，我还以为是更新了版本导致的

**Comment by Evil0ctal** [comment]
这个大概率是Pywebio库的JS和其他静态资源被GFW墙了，更换一下网络即可。
