### ISSUE TITLE
/api/tiktok/web/fetch_post_comment中的cursor和count的使用方法？

### ISSUE THREAD

**Issue by scn0901** [Evil0ctal/Douyin_TikTok_Download_API#403]
我阅读了readme和api doc，并尝试获取作品的评论列表。但我对cursor和count这两个参数的使用有一些疑问，想请教大佬：

1. 关于cursor

如果我要爬取某个作品的所有评论，那么第一次request时cursor应设为0，后面每一次request的cursor应设为上一次response的cursor，直至response中的has_more值为0，是这样的吗？

2. 关于count

我知道它的默认值为20，也就是每次返回20条评论。

我尝试将该值调至1000，目的是通过一次request获取更多的评论，但这样做只返回了几十条评论，而response中的cursor为1020（cursor: 20 + count: 1000 = 1020），我担心用1020作为下一次request的curosr会导致部分评论缺失。我使用的curl命令如下：

```
curl -X 'GET' \
  'https://douyin.wtf/api/tiktok/web/fetch_post_comment?aweme_id=7191965945211129134&cursor=20&count=1000' \
  -H 'accept: application/json'
```

因此，我想知道count应设为何值，以在确保能够获取所有评论的前提下，加快爬取速度？

期待你的解答～

**Comment by Evil0ctal** [comment]
count最大35，推荐20，1000绝对不行。

cursor需要从响应的json中获取。

**Comment by scn0901** [comment]
好的，谢谢你！

**Comment by Evil0ctal** [comment]
不客气
