### ISSUE TITLE
[BUG] 简短明了的描述问题

### ISSUE THREAD

**Issue by xiaoyaozz** [Evil0ctal/Douyin_TikTok_Download_API#405]
docker 版怎么自己换cookie啊。

**Comment by xxccll** [comment]
> docker 版怎么自己换cookie啊。

我这边是在宿主机上面上传了一份配置文件，里面写的是自己的 cookie，然后映射到容器里面。当 cookie 风控之后就vim修改宿主机的配置文件，然后重启容器。。。。
话说 cookie 管理应该抽象一下，这样其他人用的时候可以有自己的实现，比如数据库，redis 之类的。
