### ISSUE TITLE
请问docker方式安装后配置文件在哪里？

### ISSUE THREAD

**Issue by nanxun1991** [Evil0ctal/Douyin_TikTok_Download_API#407]
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/13490885/550276f8-df23-47fe-87c7-2008be4ff98d)
**想修改这个配置文件 第一次用docker不知道在哪里改？
是在`var/lib/docker`里面吗？看了一下都没有 求作者大大指点**
项目现在可以运行 但是找不到配置文件  系统是`Ubuntu Server 22.04 LTS 64bit`  根目录下没有www目录
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/13490885/6fc6ad6d-7f8a-4766-8797-a5bccc89d0c0)
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/13490885/a61da3a8-4270-4f6e-9762-2dc0ee914802)

**Comment by Jupiter1122** [comment]
我是在容器内修改的
# docker exec -it douyin_tiktok_api bash
# cd crawlers/douyin/web

修改以后重启

**Comment by Evil0ctal** [comment]
是的 请参考楼上的回答
