### ISSUE TITLE
[BUG] tiktok  mstoken生成失败

### ISSUE THREAD

**Issue by meepolove** [Evil0ctal/Douyin_TikTok_Download_API#408]
我本地网络能正常访问tiktok 但是调试项目的时候生成tiktok mstoken总是超时
![QQ截图20240523143637](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/28331220/530a2c3d-e324-4e57-b5fb-c021ed1b803b)

**Comment by Evil0ctal** [comment]
你的本地网络是否开起来代理？

**Comment by meepolove** [comment]
本地网络代理开着呢 可以正常访问tiktok

**Comment by meepolove** [comment]
https://mssdk-sg.tiktok.com/web/common?msToken=1Ab-7YxR9lUHSem0PraI_XzdKmpHb6j50L8AaXLAd2aWTdoJCYLfX_67rVQFE4UwwHVHmyG_NfIipqrlLT3kCXps-5PYlNAqtdwEg7TrDyTAfCKyBrOLmhMUjB55oW8SPZ4_EkNxNFUdV7MquA==  这个地址浏览器返回404

**Comment by meepolove** [comment]
![QQ截图20240524094607](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/28331220/a0644cbf-b9ef-49f2-b9c3-ed83b5934667)
