### ISSUE TITLE
No Response from API

### ISSUE THREAD

**Issue by ketanmalempati** [Evil0ctal/Douyin_TikTok_Download_API#409]
Hi I am trying to get video details from the API but I am not getting any response

![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/57043103/61cc3005-5484-41ea-87df-bb51c0bdcb8c)

I tried all the methods possible but no hope
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/57043103/1d3afe7f-608c-4de9-87df-f32594e2b006)

Could you please help.

Thank you

**Comment by Evil0ctal** [comment]
This is a Demo website, you need make your own deployment and replace the cookies value in config.yaml.

**Comment by ketanmalempati** [comment]
Could you let me know how I could do that.
I have installed it using the docker commands you have provided.
From where can I get the cookies and how to replace it in the yaml file

**Comment by Evil0ctal** [comment]
Hi, please read the README.md file, and follow the instructions.
