### ISSUE TITLE
Proxy IP?

### ISSUE THREAD

**Issue by chrisuehlein** [Evil0ctal/Douyin_TikTok_Download_API#41]
This works phenomenally well for my needs on my local host but in production (on heroku) it times out. Is there a way to use a proxy IP address to make the request?

**Comment by chrisuehlein** [comment]
Amazing! Thank you

**Comment by Nhaqua** [comment]
Can I use this type of proxy: IP:port:user:pass?

**Comment by Nhaqua** [comment]
@chrisuehlein Can I use this type of proxy: IP:port:user:pass?
