### ISSUE TITLE
前辈您好 请教一下 我通过api解析出来的视频地址域名是https://v16-webapp-prime.us.tiktok.com而不是https://v16m-default.akamaized.net 是为什么

### ISSUE THREAD

**Issue by 18374907010** [Evil0ctal/Douyin_TikTok_Download_API#410]
前辈您好 请教一下 我通过api解析出来的视频地址域名是https://v16-webapp-prime.us.tiktok.com而不是https://v16m-default.akamaized.net 是为什么

![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/86545790/f1e2d621-da1e-41bb-86c8-fef62116205c)
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/86545790/674b5bab-c007-4171-b2f2-48c52b2c1f39)

**Comment by Evil0ctal** [comment]
这个跟TikTok的API平台有关系，目前使用的是web的接口

**Comment by 18374907010** [comment]
https://v16-webapp-prime.us.tiktok.com 这个域名的视频访问提示403 有什么办法可以解决吗
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/86545790/ca7fbf7a-5ff0-4912-93f9-5858999dcaa1)

**Comment by Evil0ctal** [comment]
请使用V4.0.2版本。
