### ISSUE TITLE
[BUG] got error while parsing tiktok video

### ISSUE THREAD

**Issue by jackleibest** [Evil0ctal/Douyin_TikTok_Download_API#411]
***Platform where the error occurred?***

as the title mentioned, it  encounters the promble while get tiktok video, I have replace the cookie in the config file: Douyin_TikTok_Download_API/crawlers/tiktok/web/config.yaml

Such as: Douyin/TikTok
/api/hybrid/video_data?url=https://www.tiktok.com/t/XXXXX/
***The endpoint where the error occurred?***

Such as: API-V1/API-V2/Web APP

***Submitted input value?***

Such as: video link

***Have you tried again?***

Such as: Yes, the error still exists after X time after the error occurred.

***Have you checked the readme or interface documentation for this project?***

Such as: Yes, and it is very sure that the problem is caused by the program.

**Comment by Evil0ctal** [comment]
请使用V4.0.2版本。
