### ISSUE TITLE
[BUG] 大佬，请求Tiktok出现无法连接或请求超时

### ISSUE THREAD

**Issue by CreateGuy** [Evil0ctal/Douyin_TikTok_Download_API#412]
前提条件：
-已更换cookie，格式和默认的不一样，但一样取的是b站教学视频中的i/comment/list中的cookie
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/56995260/22cd8cf2-f3f4-49da-8c66-65057ac28ad6)

1、由于目标计算机积极拒绝，无法连接
更换了代理地址
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/56995260/687517b9-aa00-495a-884a-d8c74ba0d2d5)
然后在pycharm中启动start.py

import sys; print('Python %s on %s' % (sys.version, sys.platform))
D:\Python3.11\python.exe -X pycache_prefix=C:\Users\lzx\AppData\Local\JetBrains\PyCharm2023.3\cpython-cache "D:/PyCharm 2023.3.2/plugins/python/helpers/pydev/pydevd.py" --multiprocess --qt-support=auto --client 127.0.0.1 --port 59424 --file D:\MyPython\Douyin_TikTok_Download_API\start.py 
Connected to pydev debugger (build 233.13135.95)
ERROR    生成TikTok msToken API错误：[WinError 10061]                          
         由于目标计算机积极拒绝，无法连接。                                    
INFO     当前网络无法正常访问TikTok服务器，已经使用虚假msToken以继续运行。     
INFO     并且TikTok相关API大概率无法正常使用，请在(/tiktok/web/config.yaml)中更
         新代理。                                                              
INFO     如果你不需要使用TikTok相关API，请忽略此消息。                         
INFO:     Will watch for changes in these directories: ['D:\\MyPython\\Douyin_TikTok_Download_API']
INFO:     Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
INFO:     Started reloader process [20832] using WatchFiles
ERROR    生成TikTok msToken API错误：[WinError 10061]                          
         由于目标计算机积极拒绝，无法连接。                                    
INFO     当前网络无法正常访问TikTok服务器，已经使用虚假msToken以继续运行。     
INFO     并且TikTok相关API大概率无法正常使用，请在(/tiktok/web/config.yaml)中更
         新代理。                                                              
INFO     如果你不需要使用TikTok相关API，请忽略此消息。                         
INFO:     Started server process [24276]
INFO:     Waiting for application startup.
INFO:     Application startup complete.

就算用默认的Cookie也是爆出于目标计算机积极拒绝，无法连接

2、链接超时
更换了代理地址格式
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/56995260/f2582fc1-bfa0-4653-9e72-efb5e62f536f)
然后在pycharm中启动start.py

ERROR    生成TikTok msToken API错误：timed out                                 
INFO     当前网络无法正常访问TikTok服务器，已经使用虚假msToken以继续运行。     
INFO     并且TikTok相关API大概率无法正常使用，请在(/tiktok/web/config.yaml)中更
         新代理。                                                              
INFO     如果你不需要使用TikTok相关API，请忽略此消息。                         
INFO:     Will watch for changes in these directories: ['D:\\MyPython\\Douyin_TikTok_Download_API']
INFO:     Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
INFO:     Started reloader process [11220] using WatchFiles
ERROR    生成TikTok msToken API错误：timed out                                 
INFO     当前网络无法正常访问TikTok服务器，已经使用虚假msToken以继续运行。     
INFO     并且TikTok相关API大概率无法正常使用，请在(/tiktok/web/config.yaml)中更
         新代理。                                                              
INFO     如果你不需要使用TikTok相关API，请忽略此消息。                         
INFO:     Started server process [3464]
INFO:     Waiting for application startup.
INFO:     Application startup complete.

**Comment by wanhhe** [comment]
一般是127.0.0.1吧

**Comment by CreateGuy** [comment]
> 一般是127.0.0.1吧

![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/56995260/50cf5eb2-5971-4a98-bb4a-a1eff871004b)
改成127.0.0.1还是一样

而且看请求参数是msToken相关的
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/56995260/b35a93b2-ebc5-47be-b038-d007100c9c45)

**Comment by Evil0ctal** [comment]
这个应该是你本地的代理没有准确设置导致的

**Comment by CreateGuy** [comment]
> 这个应该是你本地的代理没有准确设置导致的

确实是代理地址写错了，后面程序正常启动，但是我请求fetch_post_comment接口还是报400，然后我看了代码没有配置代理地址
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/56995260/2ba9c95a-35dd-4d13-a751-ebb3322ed1e2)

然后我加入了代理地址后才请求成功
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/56995260/c31db333-f329-4ea4-a844-c06ada20f2f0)

难道是字节换了服务器吗

**Comment by Evil0ctal** [comment]
请使用V4.0.2版本。
