### ISSUE TITLE
连接端点失败，检查网络环境或代理，代理：{'http://': None, 'https://': None} 类名：BaseCrawler

### ISSUE THREAD

**Issue by wanhhe** [Evil0ctal/Douyin_TikTok_Download_API#413]
**请问是因为我的代理不稳定吗？**

我在使用web界面下载tiktok视频的时候拉取了很久最终报如下错误：`连接端点失败，检查网络环境或代理：https://api22-normal-c-alisg.tiktokv.com/aweme/v1/feed/?iid=7318518857994389254&device_id=7318517321748022790&channel=googleplay&app_name=musical_ly&version_code=300904&device_platform=android&device_type=SM-ASUS_Z01QD&os_version=9&aweme_id=7364348052653477138 代理：{'http://': None, 'https://': None} 类名：BaseCrawler`

![微信截图_20240527135900](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/70789346/92aedb7c-a1cd-4fdc-abda-493f18fe91cf)

我尝试在`crawlers/tiktok/web/config.yaml`中设置代理，但没有起作用
![微信截图_20240527140050](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/70789346/43ea1979-732e-45e7-bea4-17b757f120a6)
另外，我还尝试修改了`web_crawler.py`中的`proxies`参数，也不起作用
![微信截图_20240527140212](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/70789346/1d8f0e4b-e7d4-4a09-87b4-3ee68b8be64b)

**控制台报错如下**
INFO:     ('127.0.0.1', 59975) - "WebSocket /?app=index&session=NEW" [accepted]
INFO:     connection open
INFO:     ('127.0.0.1', 59976) - "WebSocket /?app=index&session=NEW" [accepted]
INFO:     connection open
程序出现异常，请检查错误信息。
WARNING:  StatReload detected changes in 'crawlers\tiktok\web\web_crawler.py'. Reloading...
INFO:     connection closed

**Comment by wanhhe** [comment]
我模仿抖音中的代码改为`"proxies": {"http://": tiktok_config["proxies"]["http"], "https://": tiktok_config["proxies"]["https"]},`后依然报相同的错误。

**Comment by wanhhe** [comment]
另外我直接使用接口请求数据时，拿到的视频的音乐链接可以直接访问。但视频好像无法访问，请问如果想拿到视频该使用哪个url呢？我尝试了json中`video/playAddr`但报错如下：
![微信截图_20240527143828](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/70789346/9e2e575e-8f94-40f2-8cb7-ed25b21e356d)

求大神指点

**Comment by wanhhe** [comment]
将`model.py`中的`device_id`修改为自己浏览器中的值应该即可拿到视频。

**Comment by Evil0ctal** [comment]
TikTok的app接口目前有问题，使用web的接口可以正常解析，然后你这个本地的代理，我好像没有看到具体的报错，能否打印一下细节看看？

**Comment by wanhhe** [comment]
> TikTok的app接口目前有问题，使用web的接口可以正常解析，然后你这个本地的代理，我好像没有看到具体的报错，能否打印一下细节看看？

  抱歉佬，因为我昨天急着复现就并没有保留当时的具体报错信息。我估计是我哪里可能配置有问题导致创建`BaseCrawler`类的时候没有给代理成功赋值，所以才会有**代理：{'http://': None, 'https://': None} 类名：BaseCrawler**这样的报错。
我最后通过在代码里写死然后正常跑的。
![微信截图_20240528100300](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/70789346/f91a2831-89cc-45bb-a8de-e2b533fc077e)

**Comment by Evil0ctal** [comment]
嗯嗯，解决了就行，我看你的这个proxies其实等价于在config.yaml里修改http和https，这两个key的冒号后面的值，然后我晚点可能会把TikTok的部分简单进行修复一下，目测APP的接口应该是死掉了，我更换成使用Web的接口，然后按照你的结论带上device_id去请求视频资源试一下，你在请求视频资源的时候，是在http请求中的哪个位置加上该值后成功请求视频资源的？ 比如headers，parameters？

**Comment by wanhhe** [comment]
是的，但我在config.yaml中修改了无效，所以不知道哪里配置出问题了。然后device_id只用修改model.py里的值就可以了。修改之后拿到的视频资源我并没有看到它的参数里面有这个值，但是就可以访问了。

我参考了这几个链接：
[https://github.com/Johnserf-Seed/TikTokDownload/issues/711#issuecomment-2127685656](url)
[https://github.com/davidteather/TikTok-Api/issues/311](url)

**Comment by wanhhe** [comment]
> 嗯嗯，解决了就行，我看你的这个proxies其实等价于在config.yaml里修改http和https，这两个key的冒号后面的值，然后我晚点可能会把TikTok的部分简单进行修复一下，目测APP的接口应该是死掉了，我更换成使用Web的接口，然后按照你的结论带上device_id去请求视频资源试一下，你在请求视频资源的时候，是在http请求中的哪个位置加上该值后成功请求视频资源的？ 比如headers，parameters？

是的，但我在config.yaml中修改了无效，所以不知道哪里配置出问题了。然后device_id只用修改model.py里的值就可以了。修改之后拿到的视频资源我并没有看到它的参数里面有这个值，但是就可以访问了。

我参考了这几个链接：
[https://github.com/Johnserf-Seed/TikTokDownload/issues/711#issuecomment-2127685656](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/issues/url)
[https://github.com/davidteather/TikTok-Api/issues/311](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/issues/url)

**Comment by aymanoid** [comment]
I've had the same issue of getting 403 response when requesting videos returned from the web api. I solved it by changing the device_id in the api request (as suggested by @wanhhe), and then using the same cookie when requesting the video as the one used in the api request.

**Comment by Evil0ctal** [comment]
请使用V4.0.2版本。
