### ISSUE TITLE
[BUG] 修改了很多coocke，但是还是提示获取不到数据

### ISSUE THREAD

**Issue by ww462227354** [Evil0ctal/Douyin_TikTok_Download_API#414]
![微信截图_20240527215726](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/52489508/775f72db-6123-43c0-b143-3b71a669fd9b)
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/52489508/b4ed268f-e3d3-4b61-91f8-66c5a629884b)

**Comment by Evil0ctal** [comment]
你使用的是登陆后的cookie吗？

**Comment by ww462227354** [comment]
反复确认过，是登录之后的cookie呢

**Comment by Evil0ctal** [comment]
好的，我晚点尝试复现一下这个问题，看看是什么原因导致的。

**Comment by ww462227354** [comment]
好的 感谢大佬

**Comment by 987472953** [comment]
cookie会被封，清空cookie再创建新的可以使用一会儿，只要用代理频繁换ip，cookie很容易就封了。还有, X-Bogus还能用吗

**Comment by Evil0ctal** [comment]
xb目前是可以用的，我目前只测试了单IP请求是没有问题的，你的请求频率如何？

**Comment by llxbl** [comment]
同样的情况，不过更换新cookie可以用几次，然后就不行了，代理IP也关闭掉没使用。

**Comment by aslanTT** [comment]
我使用的单IP，刚部署的前几天用没问题，后来就一直获取不到数据，cookie换了几个了一直不行
抖音的还能用，tt 的一直挂着了

**Comment by Marks-Jack** [comment]
我也遇到了相同的问题，抖音可以正常用，tt的就算更换已登录的cookie也是不正常的

**Comment by Evil0ctal** [comment]
请使用V4.0.2版本。
