### ISSUE TITLE
使用Singularity部署服务时遇到问题

### ISSUE THREAD

**Issue by scn0901** [Evil0ctal/Douyin_TikTok_Download_API#415]
你好，我在尝试使用容器部署时遇到了问题，不好意思我对容器并不是很了解，我尽量描述我的操作，如果有需要我补充的信息，请告诉我。

我目前用的hpc似乎不支持直接使用Docker，但支持Singularity（可以将Docker镜像转换为Singularity镜像），但我在使用时遇到了问题。具体来说，我使用以下命令拉取镜像：

```
singularity pull douyin_tiktok_download_api.sif docker://evil0ctal/douyin_tiktok_download_api
```

拉取镜像后，我尝试使用以下命令启动并进入容器实例的交互式shell。我使用--bind选项来替换容器内的Cookie文件，并尝试使用hpc宿主机的命令（因为容器内好像无法直接使用curl等命令）：

```
singularity shell --bind config.yaml:/app/crawlers/tiktok/web/config.yaml,/usr douyin_tiktok_download_api.sif
```

但是，进入容器后，我没有在容器的80端口发现任何服务，使用curl访问localhost会提示curl: (7) Failed connect to localhost:80; Connection refused。此外，我尝试修改/app/config.yaml中的端口为8888并重启容器，但8888端口同样没有任何服务。

我想知道在哪里可以查看服务的log文件以及进行debug，因为我在启动容器时终端并没有输出？请问这个问题可能是因为我没有root权限，还是我在操作中有什么错误？期待您的解答～

**Comment by scn0901** [comment]
已解决～需要设置--writable-tmpfs

**Comment by Evil0ctal** [comment]
好的👍🏻👍🏻👍🏻
