### ISSUE TITLE
抖音直播间商品信息的API无法使用

### ISSUE THREAD

**Issue by clone203521** [Evil0ctal/Douyin_TikTok_Download_API#416]
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/127613751/7f8d1b1f-3afa-40d7-81e7-cfd33631b4e1)
我把项目的cookie更新成自己的，其他功能都能用，只有这个接口显示400，
请求如下
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/127613751/32023c71-2e58-45cc-a798-a926cb947536)
返回数据
![image](https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/127613751/6ac7cacc-8781-4a67-9424-fe106dcce7b7)
这个cookie和项目里面被替换的cookie是一样的，但是显示400，这是什么原因

**Comment by Evil0ctal** [comment]
这个接口目前是处于带维护的状态，然后TikHub相关的issue请到discord中寻求帮助噢，谢谢☺️
