### ISSUE TITLE
[BUG] 抖音解析有时候秒解析有时候十几秒才解析成功有时候直接失败

### ISSUE THREAD

**Issue by kiko923** [Evil0ctal/Douyin_TikTok_Download_API#420]
程序出现异常，请检查错误信息。
ERROR 无效响应类型。响应类型: <class 'NoneType'>
程序出现异常，请检查错误信息。
INFO: 175.178.10.244:32810 - "GET /api/hybrid/video_data?url=https%3A%2F%2Fv.douyin.com%2FijPCB4qD%2F&minimal=true HTTP/1.1" 400 Bad Request
INFO: 175.178.10.244:32856 - "GET /api/hybrid/video_data?url=https%3A%2F%2Fv.douyin.com%2FijPCB4qD%2F&minimal=true HTTP/1.1" 200 OK

第一次不行 第二次秒成功 这种不知道是什么原因导致的 希望大佬修复一下

**Comment by Evil0ctal** [comment]
这个应该是抖音的问题
