### ISSUE TITLE
无法使用cookie下载视频

### ISSUE THREAD

**Issue by yangyiming** [Evil0ctal/Douyin_TikTok_Download_API#421]
***发生错误的平台？***

TikTok

***发生错误的端点？***

API-V1/

***提交的输入值？***
https://v16-webapp-prime.tiktok.com/video/tos/alisg/tos-alisg-pve-0037c001/oMWYIAwEitBALo4iFqA6JzrawTdAICQzIcmdfY/?a=1988&bti=ODszNWYuMDE6&ch=0&cr=3&dr=0&lr=tiktok&cd=0%7C0%7C1%7C&cv=1&br=1792&bt=896&cs=0&ds=3&ft=Fx9KL6BMyq8uhG2kE12an-HYztGxRf&mime_type=video_mp4&qs=0&rc=OTk5ZDw6MzdpZmU5OTtkaUBpM3c0eGo5cnBkczMzODczNEAuYTI2MjEvNjExMjQuLzE0YSMxZGRiMmRzbmBgLS1kMS1zcw%3D%3D&btag=e00098000&expire=1717682482&l=202406060758216FEC6A471930A803C3CC&ply_type=2&policy=2&signature=ef9dc9c17d4edc006af8c377131a7b13&tk=tt_chain_token

***是否有再次尝试？***

如：是，发生错误后X时间后错误依旧存在。

***你有查看本项目的自述文件或接口文档吗？***

cookie:

tt_csrf_token=Onwmoqlz-nyUXFB2q57xxFIqTydVBFjHONDs;
tt_chain_token=U3IUsf7vGmxbUydwuUaRzg==; 
msToken=DnHFIrSBuMbbVk9BItWqhfXfvrmFKuW5KIHmqnMw-s0TvgrjF3zMT2oWiaedkgqWvb7T8h7ugoPyqhXDPCl5Z-_NE7yhc73wCi4dqw8cVYCcAuIpOechm4wut8i9yjP3XG1Sk1E-QA2v6R0RVOfuE-tk

这个实时的cookie 为什么都是403

**Comment by laosanyuan** [comment]
我也遇到了这个问题。原来可以的下载视频api`https://api22-normal-c-alisg.tiktokv.com`也失效了，想用这个也不行

**Comment by laosanyuan** [comment]
这个连接来自“api/post/item_list”

**Comment by TheSnowGuru** [comment]
I used [this ](https://console.apify.com/actors/GdWCkxBtKWOsKjdch/input?fpr=cfknx )and it worked really well

**Comment by yangyiming** [comment]
> I used [this ](https://console.apify.com/actors/GdWCkxBtKWOsKjdch/input?fpr=cfknx)and it worked really well

how to use？ where cookie?

**Comment by Evil0ctal** [comment]
请在源代码中修改device_id和你自己的cookie。然后在同一浏览器中打开视频cdn链接

**Comment by befantasy** [comment]
> 请在源代码中修改device_id和你自己的cookie。然后在同一浏览器中打开视频cdn链接

device_id是4.0新增的参数吗？3.21是不是已经失效了？这两天都无法获取视频了。
