### ISSUE TITLE
[BUG]获取单个作品信息的接口没有返回

### ISSUE THREAD

**Issue by yhq2211** [Evil0ctal/Douyin_TikTok_Download_API#427]
/aweme/v1/web/aweme/detail/
这个接口没有返回，使用的是x-bogus
已经使用了登录后的cookie

**Comment by Cestb0n** [comment]
x_bogus不能用了，只能用a_bogus

**Comment by yhq2211** [comment]
> x_bogus不能用了，只能用a_bogus

看起来只有这个接口不能用x_bogus，其他查作品信息的还可以用。是否有开源的a_bogus方法

**Comment by Cestb0n** [comment]
> > x_bogus不能用了，只能用a_bogus
> 
> 看起来只有这个接口不能用x_bogus，其他查作品信息的还可以用。是否有开源的a_bogus方法

其它接口不需要加密参数，也可以。找到一个开源项目:https://github.com/dengmin/a-bogus

**Comment by Evil0ctal** [comment]
请使用V4.0.2版本。

**Comment by yhq2211** [comment]
> 请使用V4.0.2版本。

好的，我尝试看看
