### ISSUE TITLE
[BUG] 查询用户作品列表接口，无法获取到数据

### ISSUE THREAD

**Issue by yhq2211** [Evil0ctal/Douyin_TikTok_Download_API#429]
抖音获取用户作品 /aweme/v1/web/aweme/post
使用xbogus签名，登录后获取最新的cookie，20分钟后会失效，无法获取到用户作品列表

**Comment by Evil0ctal** [comment]
已经在V4.0.3版本中修改为使用a_bogus参数请求。

**Comment by yhq2211** [comment]
> 已经在V4.0.3版本中修改为使用a_bogus参数请求。

你好，我使用a_bogus参数，也会出现20分钟后无法获取用户作品列表的情况。

**Comment by Evil0ctal** [comment]
对 抖音在风控

**Comment by yhq2211** [comment]
> 对 抖音在风控

20分钟左右cookie就失效了，感觉目前的频率有点高；之前可以用挺长一段时间的
考虑做自动化生成cookie不
