### ISSUE TITLE
[BUG] 4.0.3版本更换了cookies依然无法获取视频的信息

### ISSUE THREAD

**Issue by ilucl** [Evil0ctal/Douyin_TikTok_Download_API#431]
***发生错误的平台？***

抖音

***发生错误的端点？***

/api/hybrid/video_data

***提交的输入值？***

[如：短视频链接](https://v.douyin.com/ijtxc3Go/)

***是否有再次尝试？***

是。

***你有查看本项目的自述文件或接口文档吗？***

有。log如下：
程序出现异常，请检查错误信息。
ERROR    无效响应类型。响应类型: <class 'NoneType'>                            
程序出现异常，请检查错误信息。

**Comment by yncsdc** [comment]
<img width="611" alt="image" src="https://github.com/Evil0ctal/Douyin_TikTok_Download_API/assets/13376699/56817421-d807-4ed1-9201-c398acfe39f7">
我与你的问题一样，cookie已经配置好了，还是不行

**Comment by Evil0ctal** [comment]
更换cookie后，重启服务了吗？ 程序不会自动重载。

**Comment by yncsdc** [comment]
> 更换cookie后，重启服务了吗？ 程序不会自动重载。

重启了，大佬。不重启肯定无法读取配置，我用了另外一家的开源项目“TikTokDownloader-5.3”，同样跑不起来了，前几天还都用的好好的。难道是抖音接口地址变了吗。。。

**Comment by Evil0ctal** [comment]
那就是你网络的问题了，建议你换一个服务器。

**Comment by yncsdc** [comment]
> 那就是你网络的问题了，建议你换一个服务器。

大佬，换个手机热点，一样的问题。  我看了另外一家的项目，也是很多人提问突然无法使用了。

**Comment by yncsdc** [comment]
> _**发生错误的平台？**_
> 
> 抖音
> 
> _**发生错误的端点？**_
> 
> /api/hybrid/video_data
> 
> _**提交的输入值？**_
> 
> [如：短视频链接](https://v.douyin.com/ijtxc3Go/)
> 
> _**是否有再次尝试？**_
> 
> 是。
> 
> _**你有查看本项目的自述文件或接口文档吗？**_
> 
> 有。log如下： 程序出现异常，请检查错误信息。 ERROR 无效响应类型。响应类型: <class 'NoneType'> 程序出现异常，请检查错误信息。

你的好了吗

**Comment by ilucl** [comment]
也没有好，一样不行。

**Comment by Evil0ctal** [comment]
我刚刚在本地测试了没有问题的。

**Comment by ilucl** [comment]
> 我刚刚在本地测试了没有问题的。



可能就是网络问题吧，但是为什么你的网络不会有问题，我才刚测试没几次，就不行了。

**Comment by Smecta** [comment]
我用docker 部署的 一样无法获取

**Comment by why0209** [comment]
无法获取

**Comment by ilucl** [comment]
问题没有解决，先关掉了
