### ISSUE TITLE
[BUG] fetch_one_video根据aweme_id获取数据失败

### ISSUE THREAD

**Issue by xiaoshuhao1999** [Evil0ctal/Douyin_TikTok_Download_API#433]
***Platform where the error occurred?***

Douyin

***The endpoint where the error occurred?***

API-V1

***Submitted input value?***

video link

***Have you tried again?***

尝试多次  返回的响应内容为空

***Have you checked the readme or interface documentation for this project?***

其他接口正常  只有这个获取数据返回空值

**Comment by LazyYangi** [comment]
/api/tiktok/app/fetch_one_video Error

{"detail":{"code":400,"message":"An error occurred.","support":"Please contact us on Github: https://github.com/Evil0ctal/Douyin_TikTok_Download_API","time":"2024-07-06 20:59:35","router":"/api/tiktok/app/fetch_one_video","params":{"aweme_id":"7350810998023949599"}}}

**Comment by Evil0ctal** [comment]
尝试在配置文件中更换自己的cookie
