### ISSUE TITLE
[BUG] 更换了初始Cookie后，返回请求依然为空。应该是个常见的问题，但是不清楚如何解决。

### ISSUE THREAD

**Issue by zddllc** [Evil0ctal/Douyin_TikTok_Download_API#435]
***发生错误的平台？***

如：抖音/

***发生错误的端点？***

如：本地部署后，通过浏览器访问

***提交的输入值？***

如：https://www.douyin.com/video/7351452881150545171

***是否有再次尝试？***

如：是，错误一直发生

***你有查看本项目的自述文件或接口文档吗？***

如：有，并且很确定该问题是程序导致的。

应该是更新的Cookie后，这次第一次使用，之前也没有使用成功过。
后端显示的错误为

第1次响应内容为空，状态码200，直到第3次为空，然后放弃。

https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=webapp&aid=6383&channel=channel_pc_web&pc_client_type=1&version_code=190500&version_name=19.5.0&cookie_enabled=true&screen_width=1920&screen_
         height=1080&browser_language=zh-CN&browser_platform=Win32&browser_name=Firefox&browser_version=124.0&browser_online=true&engine_name=Gecko&engine_version=122.0.0.0&os_name=Windows&os_version=10&cpu_core_num=12&d
       evice_memory=8&platform=PC&msToken=&aweme_id=7351452881150545171&a_bogus=DXmqBdghDiITvDyf5U2LfY3q6W33YmsU0trEMD2f0dfOvL39HMOL9exojqXvNibjLG%2FlIeujy4hbT3ohrQ2y0Hwf9W0L%2F25ksDSkKl5Q5xSSs1X9eghgJ04qmkt5SMx2RvB-rO
         XmqhZHKRbp09oHmhK4bIOwu3GMqD%3D%3D 

输入的aweme_id已经被接收，感觉应该就是提供的cookie不对，程序没有获取到想要的内容。
想问下如何获取正确的cookie，我从浏览器获取的cookie，长度很长，不知道是否是这个问题，获取的Cookie里也没有发现例子里给的
__ac_nonce 这个kv对。

谢谢。

**Comment by xmyouche** [comment]
我也遇到同样问题，替换了拼音的cookie后，单个作品请求功能也是没法正常。

**Comment by Evil0ctal** [comment]
请使用已经登录的抖音账号并且获取cookie

**Comment by mengjianjia** [comment]
![screenshot-20240718-111820](https://github.com/user-attachments/assets/6d81e984-a65e-4197-ab7e-b0978545327a)
我也遇到同样的问题，cookie我是登录后获取的
![screenshot-20240718-111913](https://github.com/user-attachments/assets/83993dc5-ed99-4596-bc35-3f83ea4a4253)

**Comment by Evil0ctal** [comment]
按照我视频的做法去拿Cookie
