### ISSUE TITLE
[BUG] 抖音视频下载失败

### ISSUE THREAD

**Issue by huronzhu** [Evil0ctal/Douyin_TikTok_Download_API#436]
抖音
API-V2/Web APP
https://www.douyin.com/video/7063758979351989534?modeFrom=
100%重现
确定该问题是程序导致的。

解析正常。视频下载错误，403

{
"code": 400,
"message": "Client error '403 Forbidden' for url 'http://v3-web.douyinvod.com/4bd516925d42db988aa61383506c00e6/66822677/video/tos/cn/tos-cn-ve-15-alinc2/e840cf8cdf9b402291f732a2216fc5ab/?a=6383&ch=26&cr=3&dr=0&lr=all&cd=0%7C0%7C0%7C3&cv=1&br=3583&bt=3583&cs=0&ds=4&ft=rVWEerwwZR3Gs0Do0PDS6kFgAX1tGuDq8f9eF3cDcYV12nzXT&mime_type=video_mp4&qs=0&rc=NjxoNTc4ZjM5Zjo2ZGU8OEBpM3g4cGQ6ZjNwOzMzNGkzM0BfNWMwLzYtNmAxNDIyYzUxYSNfYWtlcjRfczBgLS1kLS9zcw%3D%3D&btag=c0000e00030000&cquery=100w_100B_100H_102u_100o&dy_q=1719797877&l=2024070109375732A75AEBE0547BEF100C'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403",
"support": "Please contact us on Github: https://github.com/Evil0ctal/Douyin_TikTok_Download_API",
"time": "2024-06-30 12:22:47",
"router": "[/api/download](https://homenas.huronzhu.xin:5035/api/download)",
"params": {
"url": "https://www.douyin.com/video/7063758979351989534?modeFrom=",
"prefix": "true",
"with_watermark": "false"
}
}

**Comment by paddy0914** [comment]
遇到了同样的问题

**Comment by huronzhu** [comment]
应该是请求头的问题，不通过代理并且设置好请求头就可以下载了

**Comment by suyana** [comment]
同样遇到这问题，浏览器打开也是403，见鬼的是迅雷和IDM可以下载

**Comment by CharleoY** [comment]
我测试TikTok的时候也遇到了差不多的问题，/api/download无论改什么cookie总是报403, 但是其它endpoint都正常，不过当我改了 BaseRequestModel 的 device_id 之后，所有的请求都正常了，就可以下载视频了。

**Comment by BigdataZjk** [comment]
> 我测试TikTok的时候也遇到了差不多的问题，/api/download无论改什么cookie总是报403, 但是其它endpoint都正常，不过当我改了 BaseRequestModel 的 device_id 之后，所有的请求都正常了，就可以下载视频了。

具体是哪个参数呢，大佬可以告知下吗？

**Comment by Evil0ctal** [comment]
参考楼上的回复，这种情况需要修改model.py文件的设备ID值，cookie和设备id必须要一致
