### ISSUE TITLE
抖音视频可以解析，但无法下载

### ISSUE THREAD

**Issue by zttlovedouzi** [Evil0ctal/Douyin_TikTok_Download_API#439]
***发生错误的平台？***

抖音

***发生错误的端点？***
Web APP

***提交的输入值？***

如：短视频链接

***是否有再次尝试？***

如：是，发生错误后X时间后错误依旧存在。

***你有查看本项目的自述文件或接口文档吗？***

如：有，并且很确定该问题是程序导致的。
{
  "code": 400,
  "message": "Client error '403 Forbidden' for url 'http://v3-web.douyinvod.com/045365e0ddece3cd7bb6ee83a1f2207c/6687bd6a/video/tos/cn/tos-cn-ve-15c001-alinc2/oEheBigbIOzQoZA3EBy2VNiBQOkaRAfR30AEpT/?a=6383&ch=26&cr=3&dr=0&lr=all&cd=0%7C0%7C0%7C3&cv=1&br=1508&bt=1508&cs=0&ds=4&ft=pEaFx4hZffPdhb~NI1VNvAq-antLjrKaM9V.RkaFmfTeejVhWL6&mime_type=video_mp4&qs=0&rc=MztoNTVkODxoZGc8ZDg7M0BpM29oN3E5cjw2czMzNGkzM0A0NTZeLjYwNmMxNi42YGAyYSNmZDA0MmRzNm1gLS1kLWFzcw%3D%3D&btag=c0000e00008000&cquery=100B_100x_100z_100o_100w&dy_q=1720164672&feature_id=46a7bb47b4fd1280f3d3825bf2b29388&l=20240705153112480A6FC15A49E08AB062'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403",
  "support": "Please contact us on Github: https://github.com/Evil0ctal/Douyin_TikTok_Download_API",
  "time": "2024-07-05 07:28:20",
  "router": "/api/download",
  "params": {
    "url": "https://v.douyin.com/i6CgdQHY/",
    "prefix": "true",
    "with_watermark": "false"
  }
}

**Comment by CCCpan** [comment]
+1

**Comment by Evil0ctal** [comment]
你们能到Discord里私聊我发一下你们的config.yaml吗？ 我这边无法复现这个情况

**Comment by yzqdev** [comment]
这个是抖音最近给视频链接做了权限,通过下载链接直接下载就是403没权限,需要一些特殊操作才能下载,看有没有大佬分享如何解密下载链接喽
