### ISSUE TITLE
[BUG] 如何获取ios快捷指令中的API Token？

### ISSUE THREAD

**Issue by Tequilasgithub** [Evil0ctal/Douyin_TikTok_Download_API#444]
请问ios快捷指令中的api token如何获取？我根据提示进入网页后生成了api密钥，但是如何获得api token，是否需要付费？我并没有找到购买api token的界面。（我太菜了555）

**Comment by Evil0ctal** [comment]
本快捷指令使用TikHub.io的私有接口对抖音以及TikTok进行视频和图集的解析和下载，在使用本快捷指令前，请在下方文本框内输入你的TikHub API Token，请不要随意分享你的API Token防止意外密钥泄露导致的财产损失。

项目文档地址：
https://docs.tikhub.io

注册/充值/获取API Token：
https://beta-web.tikhub.io/users/signin

手动获取快捷指令：
https://api.tikhub.io/api/v1/ios_shortcut/shortcut

重置快捷指令：
手动修改版本号然后点击获取快捷指令

**Comment by Evil0ctal** [comment]
免费的，但是需要每天在用户后台里签到获取免费额度，也可以付费，0.001$请求一次。

**Comment by Tequilasgithub** [comment]
> 本快捷指令使用TikHub.io的私有接口对抖音以及TikTok进行视频和图集的解析和下载，在使用本快捷指令前，请在下方文本框内输入你的TikHub API Token，请不要随意分享你的API Token防止意外密钥泄露导致的财产损失。
> 
> 项目文档地址：
> https://docs.tikhub.io
> 
> 注册/充值/获取API Token：
> https://beta-web.tikhub.io/users/signin
> 
> 手动获取快捷指令：
> https://api.tikhub.io/api/v1/ios_shortcut/shortcut
> 
> 重置快捷指令：
> 手动修改版本号然后点击获取快捷指令

请问https://beta-web.tikhub.io/users/signin中的api密钥就是api token吗？若果是的话，为什么我在快捷方式中的第一个文本中编辑了此api密钥后运行快捷方式显示无效的url？如果不是的话，api密钥如何转化为api token？

**Comment by Evil0ctal** [comment]
正确填写第二个文本框即可，删掉占位符API_TOKEN
