### ISSUE TITLE
[BUG] douyin/web/fetch_one_video return 400 code with error message "An error occurred."

### ISSUE THREAD

**Issue by akngg** [Evil0ctal/Douyin_TikTok_Download_API#448]
***Platform where the error occurred?***
Douyin

***The endpoint where the error occurred?***
https://douyin.wtf/api/douyin/web/fetch_one_video?aweme_id=7235604590035569976

***Submitted input value?***
![image](https://github.com/user-attachments/assets/fae81007-0248-4a41-afd3-d9c507ad5454)

***Have you tried again?***
Yes i tried a serveral times but i got the same error

***Have you checked the readme or interface documentation for this project?***
Yes, and it is very sure that the problem is caused by the program.

**Comment by Evil0ctal** [comment]
Please replace to your own cookie in the config.yaml
