### ISSUE TITLE
[BUG]  /api/tiktok/app/fetch_one_video always give 400

### ISSUE THREAD

**Issue by doaortu** [Evil0ctal/Douyin_TikTok_Download_API#449]
***Platform where the error occurred?***
TikTok App api

***The endpoint where the error occurred?***
 /api/tiktok/app/fetch_one_video

***Submitted input value?***
aweme_id=7375520500405046533

***Have you tried again?***
Yes, the error still exists after X time after the error occurred.

***Have you checked the readme or interface documentation for this project?***
I tried changing the cookie, but it still gave me 400 error.

**Comment by Evil0ctal** [comment]
Please replace to your own cookie in the config.yaml
