### ISSUE TITLE
关于怎么再docker替换cookie

### ISSUE THREAD

**Issue by kuhubmk** [Evil0ctal/Douyin_TikTok_Download_API#450]
有2个东西不太理解！
第一是再docker里怎么去替换cookei
我看了视频，你用的是本地python，是可以直接替换！那docker里怎么弄！

还有就是这个API怎么用到脚本里面去！我是API小白所以问问！

**Comment by hzn6426** [comment]
docker run -d --name douyin_tiktok_api -p 80:80 -v /Users/xxx/Documents/docker/tiktok/web/config.yaml:/app/crawlers/tiktok/web/config.yaml evil0ctal/douyin_tiktok_download_api 创建容器的时候直接映射本地文件，此时修改本地文件中的config.yaml会直接修改Docker内部文件，直接重启Docker就好

**Comment by Evil0ctal** [comment]
请参考楼上的回复。
