### ISSUE TITLE
[BUG] 一个星期前使用Web app过并且成功下载了200+视频，但是这个星期突然不行了，按照视频教程更换了Cookie，仍然不行

### ISSUE THREAD

**Issue by Losoy1** [Evil0ctal/Douyin_TikTok_Download_API#452]
***发生错误的平台？***

如：抖音

***发生错误的端点？***

如：Web APP

***提交的输入值？***

如：短视频链接

***是否有再次尝试？***

如：是，发生错误后X时间后错误依旧存在。

***你有查看本项目的自述文件或接口文档吗？***

如：有，并且很确定该问题是程序导致的。

这是我的Cookie，已经按照了视频教程重复过多次，并且在一个星期前已经成功下载了200+视频，但是不知道为什么最近这几天突然出现视频教程中的情况突然不能解析了，有可能是我的Cookie除了问题吗？
ttwid=1%7C-0dflMMeBDApYTLvDCHU5M9zmhMbAw9bQwL1B888aeQ%7C1721186940%7C5f2afca82abcb491efe8c7e89507eb2efd7065db436ad029b9968907e3204dfe; UIFID_TEMP=3c3e9d4a635845249e00419877a3730e2149197a63ddb1d8525033ea2b3354c2b36d8dea70ec55ef3bfed51712fd79effc967048ca658629071e58a611b087b705e805e59215e9bd4f3f99e55df3d64d; strategyABtestKey=%221721186954.034%22; FORCE_LOGIN=%7B%22videoConsumedRemainSeconds%22%3A180%7D; passport_csrf_token=74f7f4e43ed3f216c16e4796982cdf05; passport_csrf_token_default=74f7f4e43ed3f216c16e4796982cdf05; bd_ticket_guard_client_web_domain=2; UIFID=3c3e9d4a635845249e00419877a3730e2149197a63ddb1d8525033ea2b3354c2262f6b2f53dc3e825dd4d5b94b2c1b7e271861bbbf8ec76081e02ae101abda49170744221a288426c30f82755020708ebdb1479ed9405f571b2e832c09476249b27dc14a5e112b9987dfedeb2710df8fd409b287156739d0644f0bea9f02e0376d32a2eaf2a7630384bf1373393aeb43f580dae88956ae8b798841594723fce1; publish_badge_show_info=%220%2C0%2C0%2C1721187009386%22; _bd_ticket_crypt_doamin=2; __security_server_data_status=1; store-region-src=uid; volume_info=%7B%22isUserMute%22%3Afalse%2C%22isMute%22%3Atrue%2C%22volume%22%3A0.5%7D; stream_player_status_params=%22%7B%5C%22is_auto_play%5C%22%3A0%2C%5C%22is_full_screen%5C%22%3A0%2C%5C%22is_full_webscreen%5C%22%3A0%2C%5C%22is_mute%5C%22%3A1%2C%5C%22is_speed%5C%22%3A1%2C%5C%22is_visible%5C%22%3A0%7D%22; download_guide=%223%2F20240717%2F0%22; WallpaperGuide=%7B%22showTime%22%3A1721197085102%2C%22closeTime%22%3A0%2C%22showCount%22%3A1%2C%22cursor1%22%3A12%2C%22cursor2%22%3A0%7D; pwa2=%220%7C0%7C3%7C0%22; stream_recommend_feed_params=%22%7B%5C%22cookie_enabled%5C%22%3Atrue%2C%5C%22screen_width%5C%22%3A1920%2C%5C%22screen_height%5C%22%3A1080%2C%5C%22browser_online%5C%22%3Atrue%2C%5C%22cpu_core_num%5C%22%3A6%2C%5C%22device_memory%5C%22%3A8%2C%5C%22downlink%5C%22%3A1.3%2C%5C%22effective_type%5C%22%3A%5C%223g%5C%22%2C%5C%22round_trip_time%5C%22%3A400%7D%22; d_ticket=d3be1d1c514794e148e688b89e54f96380010; passport_assist_user=CkDm--hTvOv3nEIRYcioVyfALzX8qEAQEtREu2tsz6MopT5gQZjQb61iJsUpB4XmasV7N1vOMO0wf7eXqpkBBHkOGkoKPHfDqDGzaj8jgaZ3v9CbokP7pgRqx5kPzx0j_ruHplQ5i0w-UcKgL2arE5Q-yPDkskxtqJcCPOn7qwL-yRC38tYNGImv1lQgASIBAxZNPMs%3D; n_mh=CXji1rShkMmP9Poc3bNuzzGe8F_66lf_NsDkrYBa_Ok; sso_uid_tt=ff2232aa2246a526d1f5688fc341e51c; sso_uid_tt_ss=ff2232aa2246a526d1f5688fc341e51c; toutiao_sso_user=6bac0b1120e173cf26cf7982ef052dd0; toutiao_sso_user_ss=6bac0b1120e173cf26cf7982ef052dd0; sid_ucp_sso_v1=1.0.0-KDc0ODA3ZWZjMmFmYzFlMGU1NGE2NTk5Mjk2Njc3NDVjNTUyZjc0NzIKIAiP8uDD5Y0qELj73bQGGO8xIAww3I-WjwY4BkD0B0gGGgJobCIgNmJhYzBiMTEyMGUxNzNjZjI2Y2Y3OTgyZWYwNTJkZDA; ssid_ucp_sso_v1=1.0.0-KDc0ODA3ZWZjMmFmYzFlMGU1NGE2NTk5Mjk2Njc3NDVjNTUyZjc0NzIKIAiP8uDD5Y0qELj73bQGGO8xIAww3I-WjwY4BkD0B0gGGgJobCIgNmJhYzBiMTEyMGUxNzNjZjI2Y2Y3OTgyZWYwNTJkZDA; passport_auth_status=64b41651d22ef01c3bd7caabc5b4a3c3%2Cbd35a4f84b65debf4e03b65971e4218b; passport_auth_status_ss=64b41651d22ef01c3bd7caabc5b4a3c3%2Cbd35a4f84b65debf4e03b65971e4218b; uid_tt=fc9cc028b2baed1909e2390fb7b91756; uid_tt_ss=fc9cc028b2baed1909e2390fb7b91756; sid_tt=6e1976c2fda4e56d99ac2ed7092ef80e; sessionid=6e1976c2fda4e56d99ac2ed7092ef80e; sessionid_ss=6e1976c2fda4e56d99ac2ed7092ef80e; IsDouyinActive=true; FOLLOW_NUMBER_YELLOW_POINT_INFO=%22MS4wLjABAAAAXp9b19ZnYlvq_ENlNiL4OXsFHV2k2je9Yt1CbGCjJf0%2F1721232000000%2F0%2F1721204159595%2F0%22; home_can_add_dy_2_desktop=%221%22; _bd_ticket_crypt_cookie=c1acf69845fdeffea2b61ab4b4860e20; bd_ticket_guard_client_data=eyJiZC10aWNrZXQtZ3VhcmQtdmVyc2lvbiI6MiwiYmQtdGlja2V0LWd1YXJkLWl0ZXJhdGlvbi12ZXJzaW9uIjoxLCJiZC10aWNrZXQtZ3VhcmQtcmVlLXB1YmxpYy1rZXkiOiJCSGN0Z29QdlYrMER4MmR5TGVXcTl4cmY2UHlCR2syeENMZDVBNXhJakVxblBRa2Fham44dkhxL0NTOHpkR3lZNzIwUGp2YW90UkpnR3BRdW11K1RkVGM9IiwiYmQtdGlja2V0LWd1YXJkLXdlYi12ZXJzaW9uIjoxfQ%3D%3D; sid_guard=6e1976c2fda4e56d99ac2ed7092ef80e%7C1721204164%7C5183991%7CSun%2C+15-Sep-2024+08%3A15%3A55+GMT; sid_ucp_v1=1.0.0-KGQ4MjQ1YTAxYjE3M2Y3MDJhMzc5N2U3MmE5ZjJkMDFmY2IxZWJiNTIKGgiP8uDD5Y0qEMT73bQGGO8xIAw4BkD0B0gEGgJobCIgNmUxOTc2YzJmZGE0ZTU2ZDk5YWMyZWQ3MDkyZWY4MGU; ssid_ucp_v1=1.0.0-KGQ4MjQ1YTAxYjE3M2Y3MDJhMzc5N2U3MmE5ZjJkMDFmY2IxZWJiNTIKGgiP8uDD5Y0qEMT73bQGGO8xIAw4BkD0B0gEGgJobCIgNmUxOTc2YzJmZGE0ZTU2ZDk5YWMyZWQ3MDkyZWY4MGU; biz_trace_id=7e842496; store-region=cn-gd; odin_tt=be8a61af146d51affbe8ab19ff575abc11b795bef9755e544d0cc8410ac6ee759197ac56b90a0e262a033ebc23c7114a29c14ae6010dd3459af6a82a58ba659f

**Comment by Losoy1** [comment]
短视频链接形如：https://www.douyin.com/video/6874447231605394701

**Comment by Evil0ctal** [comment]
你复制的cookie应该是有问题的，这个错误应该是读取config文件的值并且尝试作为header使用时发生的编码错误。

**Comment by Losoy1** [comment]
> 你复制的cookie应该是有问题的，这个错误应该是读取config文件的值并且尝试作为header使用时发生的编码错误。

![微信图片_20240718095631](https://github.com/user-attachments/assets/c32e4410-19a7-4827-9e6b-e7bf1aa56f7c)

这是我的Cookie，我是按照您视频的教程来的，并且我登陆了自己的抖音账号，是不是现在抖音的Cookie显示改了？我看和您视频教程的都不一样，没有__ac_nonce，__ac_signature。是否要复制XHR-Cookie里的Cookie呢

**Comment by Evil0ctal** [comment]
那就不清楚了，从你提供的报错只能是你的Cookie格式有问题：

```
File "C:\Users\tmp\PycharmProjects\Losoy.venv\Lib\site-packages\httpx_client.py", line 1389, in init
super().init(
File "C:\Users\tmp\PycharmProjects\Losoy.venv\Lib\site-packages\httpx_client.py", line 183, in init
self.headers = Headers(headers)
^^^^^^^^^^^^^^^^
File "C:\Users\tmp\PycharmProjects\Losoy.venv\Lib\site-packages\httpx_models.py", line 76, in init
normalize_header_value(v, encoding),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\tmp\PycharmProjects\Losoy.venv\Lib\site-packages\httpx_utils.py", line 53, in normalize_header_value
return value.encode(encoding or "ascii")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode character '\u2026' in position 512: ordinal not in range(128)
```

**Comment by Evil0ctal** [comment]
参考此Unicode标识：

https://www.fileformat.info/info/unicode/char/2026/index.htm
