### ISSUE TITLE
tiktok视频下载不了 在演示网址上，也无法查看

### ISSUE THREAD

**Issue by shan-ge-cpu** [Evil0ctal/Douyin_TikTok_Download_API#456]
https://www.tiktok.com/@lycheeshoppin/video/7386856263134481695
麻烦查看一下是什么问题
![image](https://github.com/user-attachments/assets/a6cbca64-6ae0-4967-ab54-b208eddce358)

**Comment by Evil0ctal** [comment]
https://github.com/Evil0ctal/Douyin_TikTok_Download_API/tree/main?tab=readme-ov-file#%EF%B8%8F%E9%83%A8%E7%BD%B2%E5%89%8D%E7%9A%84%E5%87%86%E5%A4%87%E5%B7%A5%E4%BD%9C%E8%AF%B7%E4%BB%94%E7%BB%86%E9%98%85%E8%AF%BB

**Comment by Evil0ctal** [comment]
TikTok Web API返回的视频链接直接访问会发生HTTP 403错误，请使用本项目API中的/api/download接口对TikTok 视频进行下载，这个接口在演示站点中已经被手动关闭了，需要你自行部署本项目。

**Comment by morying** [comment]
同上，本地部署后，依然无法下载和查看，出现403，如何解决

**Comment by Jxells** [comment]
> 同上，本地部署后，tiktok依然无法下载和查看，出现403，通过 api/download 也是无法下载，请问大佬如何解决
> 
> ```
> {
>   "code": 400,
>   "message": "Client error '403 Forbidden' for url 'https://v16-webapp-prime.us.tiktok.com/video/tos/alisg/tos-alisg-pve-0037/owI7HiHsQnMXvA6BExZilpYzIQ9HhKwlyAvAv/?a=1988&bti=ODszNWYuMDE6&ch=0&cr=3&dr=0&lr=unwatermarked&cd=0%7C0%7C0%7C&cv=1&br=2344&bt=1172&cs=0&ds=6&ft=FLr6B6BMyq8IxJfkE12GH3NYztGxRf&mime_type=video_mp4&qs=0&rc=O2QzZTM3OTZnNDQ7Ojw2O0BpM3Q1Nnc5cm12czMzODgzNEAxMTQuXmEzNjIxYzVeMzRgYSNscy4yMmRrY3FgLS1kL2Bzcw%3D%3D&btag=e00088000&expire=1722777461&l=20240804071651282144BCCB36175A7C67&ply_type=2&policy=2&signature=8614bde8368844e2dc1cf57f36e05802&tk=tt_chain_token'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403",
>   "support": "Please contact us on Github: https://github.com/Evil0ctal/Douyin_TikTok_Download_API",
>   "time": "2024-08-04 15:10:14",
>   "router": "/api/download",
>   "params": {
>     "url": "https://www.tiktok.com/@mryang_english/video/7384718753856048405?is_from_webapp=1&sender_device=pc&web_id=7398939343455700523",
>     "prefix": "true",
>     "with_watermark": "false"
>   }
> }
> ```

也遇到了同样的问题

**Comment by Evil0ctal** [comment]
Hi, this issue had been fixed by the new version V4.0.7
