### ISSUE TITLE
[BUG] 403 Forbidden even with own cookie

### ISSUE THREAD

**Issue by hbarnehl** [Evil0ctal/Douyin_TikTok_Download_API#459]
***Platform where the error occurred?***

TikTok Web

***The endpoint where the error occurred?***

Such as: API

***Submitted input value?***

curl -X 'GET'   'http://0.0.0.0/api/download?url=https://www.tiktok.com/@ideas1plus1/video/7387793046919761182?lang=en&prefix=true&with_watermark=false'   -H 'accept: application/json'

***Have you tried again?***

Yes, the error still exists after X time after the error occurred.

***Have you checked the readme or interface documentation for this project?***

Yes, I retrieved the cookie as explained in the video, but I still get the 403 error.

**Comment by Evil0ctal** [comment]
Try change this variable, use the value in your browser:

https://github.com/Evil0ctal/Douyin_TikTok_Download_API/blob/2efd3e3eca6ef5096ce9fab902f02a03df857d3a/crawlers/tiktok/web/models.py#L25

**Comment by hbarnehl** [comment]
I changed the device_id, that still did not solve the issue.

**Comment by Evil0ctal** [comment]
Hi, this issue had been fixed by the new version V4.0.7
