### ISSUE TITLE
本地部署，替换了cookie，还是提示cookie无效

### ISSUE THREAD

**Issue by lints123** [Evil0ctal/Douyin_TikTok_Download_API#460]
使用的是网页抖音的cookie，提示无效

**Comment by Evil0ctal** [comment]
请问你是登录后的Cookie吗

**Comment by Eesttong** [comment]
> 请问你是登录后的Cookie吗

您好，我按照视频的过程替换了自己登陆后网页版的抖音的Cookie后视频解析一直失败，我在web_crawler.py测试了前五个接口(fetch_one_video(), fetch_user_post_videos(), fetch_user_like_videos(), fetch_user_collection_videos(), fetch_user_mix_videos())发现只有第一个和第三个会有NoneType的错误，其他三个都能正常返回结果。这是哪里出现了问题呢？

**Comment by HppZ** [comment]
相同问题!
不过我用的是 web 抖音未登录的 cookie.

**Comment by HppZ** [comment]
> 您好，我按照视频的过程替换了自己登陆后网页版的抖音的Cookie后视频解析一直失败，我在web_crawler.py测试了前五个接口(fetch_one_video(), fetch_user_post_videos(), fetch_user_like_videos(), fetch_user_collection_videos(), fetch_user_mix_videos())发现只有第一个和第三个会有NoneType的错误，其他三个都能正常返回结果。这是哪里出现了问题呢？

跟你完全一样的问题.

**Comment by HppZ** [comment]
相同问题!
不过我用的是 web 抖音未登录的 cookie.
