### ISSUE TITLE
[Feature request] 添加资源下载的方式配置

### ISSUE THREAD

**Issue by tongjiann** [Evil0ctal/Douyin_TikTok_Download_API#461]
**您的功能请求是否与问题相关？ 如有，请描述。**

我看了一下代码，发现`api/download`接口是做了一层缓存，优先保存到本地，然后后续再返回文件。这样做我认为的好处是
1. 减少向视频服务器的请求。
2. 避免因为网络不通而无法直接下载资源的情况。
3. 
我本地部署了一个服务，不过我的服务器上行带宽很小，这导致我自己**下载视频时速度过慢**，最终发现走的是自身服务器的带宽，而不是请求douyin的服务器。

**描述您想要的解决方案**

回归问题本身，既然有资源服务提供的资源的地址，那是否能添加一个可选项，在配置文件中自定义配置下载源，【来自于此服务器/来自于资源服务器/等等方式】

通过重定向的方式借助抖音服务器的带宽来加快下载速度，减少服务器带宽压力

**Comment by Evil0ctal** [comment]
当时这么做是因为浏览器有跨域的限制
