### ISSUE TITLE
[BUG] 抖音分享至快捷指令提示获取URL无效

### ISSUE THREAD

**Issue by samulo7** [Evil0ctal/Douyin_TikTok_Download_API#462]
***发生错误的平台？***
抖音
***发生错误的端点？***
API-V1
![996c2c91acbb2365e4227ffa76e7b70](https://github.com/user-attachments/assets/08e10c9a-0099-43e8-a022-23d0f7e67405)

**Comment by Evil0ctal** [comment]
你好，你提交的内容复制一下到这里。

**Comment by samulo7** [comment]
8.99 复制打开抖音，看看【金三柜的作品】小猫捧脸杀，被迷晕了！ # 金三柜 # 小猫咪怼脸... https://v.douyin.com/iMoXSjnH/ OKj:/ P@x.sE 07/15

**Comment by samulo7** [comment]
我用docker搭建的，网页可以正常解析视频，但是通过快捷指令就无法解析，快捷指令换成了tikhub的Api和我的混合数据接口地址

**Comment by GGbond233** [comment]
我的也是

**Comment by Newbie-L** [comment]
+1
替换为自己搭建的API接口后，使用快捷指令会提示
“未指定URL：请确保向“获取URL内容”操作传递了有效URL。”
![Uploading 微信图片_20240815135340.png…]()

**Comment by Evil0ctal** [comment]
7.0版本的快捷指令只针对TikHub的接口进行了兼容，我记得之前有一个issue有人写了一个自制版的快捷指令，我看看能不能找到。

**Comment by Evil0ctal** [comment]
你们也可以修改一下7.0版本的快捷指令，可能有一些Key需要修改。

**Comment by kiko923** [comment]
可以发出来 我可以写 我专门玩这个的

**Comment by athlon128** [comment]
可能是快捷指令的获取模块不支持太长的链接
我直接换成/api/download?url=URL&prefix=true&with_watermark=false来下载就可以了
不需要前面一大堆的解析过程
