### ISSUE TITLE
爬取数据中是否已排序，如何获取新数据

### ISSUE THREAD

**Issue by hzn6426** [Evil0ctal/Douyin_TikTok_Download_API#463]
例如 ：[/api/v1/tiktok/app/v2/fetch_user_follower_list](https://api.tikhub.io/#/TikTok-App-V2-API/fetch_user_follower_list_api_v1_tiktok_app_v2_fetch_user_follower_list_get) 这个获取粉丝数API中是否已经按照某种规则排序？比如有些大V粉丝数有几百万，爬取之后又有新的粉丝了，是否从最后一页开始爬取就会获得最新的关注粉丝了

**Comment by Evil0ctal** [comment]
大概率是从最新的排序
