### ISSUE TITLE
[BUG] douyinWEB端接口，近期稳定性问题

### ISSUE THREAD

**Issue by mouzhi** [Evil0ctal/Douyin_TikTok_Download_API#464]
抖音web接口近期解析失败率差不多有30%了，也有用作者的付费接口，看到文档里面有说抖音web接口后续可能会废弃，看是否考虑下放APPv1接口~

**Comment by Evil0ctal** [comment]
目前考虑到风控问题，暂时不会开源APP的接口，开源项目Web的接口会积极维护，只是付费端因为稳定性问题将不会积极维护Web接口。
