### ISSUE TITLE
cookie问题的一点发现

### ISSUE THREAD

**Issue by supersaiyan2019** [Evil0ctal/Douyin_TikTok_Download_API#465]
跟很多人反馈的一样，我也困扰于明明填了最新的cookie，但仍返回空的问题
[刚才又尝试了一下，从](![2024-08-11_0-39-34](https://github.com/user-attachments/assets/6d03a8fc-f074-45fa-a1a7-f29b213d86bb))
这个地方获取了完整的cookie，填入配置文件后发现居然可以用了
怀疑抖音后台对cookie的检测更严格了，从network那边获得的cookie片段检测不通过了
不过也不确定，还请大家再测试一下

**Comment by supersaiyan2019** [comment]
Application->Storage->Cookies->https://www.douyin.com

**Comment by Evil0ctal** [comment]
嗯嗯，可能是，请问你通过Storage获取到的完整Cookie是否可以从接口正常请求数据？

**Comment by HppZ** [comment]
请教下:
用 chrome  从 web 版抖音导出 cookie 后, 修改这个文件 crawlers\douyin\web\config.yaml 里的 cookie 字段, 然后重启 docker, 然后发起请求 http://localhost/api/douyin/web/fetch_one_video?aweme_id=7414775724063640883 会报错:
```json{
  "detail": {
    "code": 400,
    "message": "An error occurred.",
    "support": "Please contact us on Github: https://github.com/Evil0ctal/Douyin_TikTok_Download_API",
    "time": "2024-09-15 12:02:45",
    "router": "/api/douyin/web/fetch_one_video",
    "params": {
      "aweme_id": "7414775724063640883"
    }
  }
}```
