### ISSUE TITLE
新写的Bilibili获取作品详情功能无法获取视频下载地址

### ISSUE THREAD

**Issue by kiko923** [Evil0ctal/Douyin_TikTok_Download_API#470]
我这有一个php的bilibili helper的函数文件 可以解析出视频地址 可以看看对作者有没有帮助
[https://github.com/kiko923/BilibiliHelper/blob/main/BilibiliHelper.php](https://github.com/kiko923/BilibiliHelper/blob/main/BilibiliHelper.php)

**Comment by Evil0ctal** [comment]
好的，新的B站接口是另外一个人写的，我在这里艾特他一下。

**Comment by Evil0ctal** [comment]
@Koyomi781

**Comment by Koyomi781** [comment]
好的，感谢你的参考，在下次新增接口我会写进去  <3

**Comment by longabc12** [comment]
> I have a php bilibili helper function file that can parse out the video address. I can see if it is helpful to the author. [https://github.com/kiko923/BilibiliHelper/blob/main/BilibiliHelper.php ](https://github.com/kiko923/BilibiliHelper/blob/main/BilibiliHelper.php)

hello do you know if we could download all user video douyin without login, is that possible ?
