### ISSUE TITLE
[BUG]  第 1 次响应内容为空, 状态码: 200 最近频繁出现这个  200，但真的内容为空

### ISSUE THREAD

**Issue by defchen** [Evil0ctal/Douyin_TikTok_Download_API#473]
INFO:     172.17.0.1:56100 - "GET /api/tiktok/web/fetch_one_video?itemId=7409215120842231086 HTTP/1.1" 400 Bad Request
WARNING  第 1 次响应内容为空, 状态码: 200,                                      
         URL:https://www.tiktok.com/api/item/detail/?WebIdLastTime=1725124329&ai
         d=1988&app_language=en&app_name=tiktok_web&browser_language=en-US&brows
         er_name=Mozilla&browser_online=true&browser_platform=Win32&browser_vers
         ion=5.0%20%28Windows%29&channel=tiktok_web&cookie_enabled=true&device_i
         d=7380187414842836523&device_platform=web_pc&focus_state=true&from_page
         =user&history_len=4&is_fullscreen=false&is_page_visible=true&language=e
         n&os=windows&priority_region=US&referer=&region=US&root_referer=https%3
         A%2F%2Fwww.tiktok.com%2F&screen_height=1080&screen_width=1920&webcast_l
         anguage=en&tz_name=America%2FTijuana&msToken=MFG0ui1j29udLgqTyNhtIluf85
         xxxxxxxJ1EBkjshZ4kDY4I8eDsGYrEmkWOieXlLGYDdcLgmpzhMx7q5YbguCBl&itemId=74092151
         20842231086&X-Bogus=DFSzswVYmXGANGVRtIWVL

**Comment by Evil0ctal** [comment]
可能是你的cookie被风控了，建议你更换一个cookie。

**Comment by defchen** [comment]
> 可能是你的cookie被风控了，建议你更换一个cookie。

只有https://www.tiktok.com/api/item/detail/?WebIdLastTime 这个接口不能用，我换了cookie也是一样。另外config.yaml里的 msToken:
      url:   以及 strData ，
odin_tt:
      url:
这几个要更换吗？

**Comment by Evil0ctal** [comment]
只需要更换cookie即可，这两天TikTok可能在修改针对Web端的风控机制，建议你更换一个TikTok账号然后登录后获取cookie进行更换，然后再次请求接口。

**Comment by Jxells** [comment]
遇到了同样的问题

**Comment by suchang1999** [comment]
换了cookie就行了
