### ISSUE TITLE
[BUG] TikTok fetch_user_post 接口返回的cursor为-1

### ISSUE THREAD

**Issue by zaimatest** [Evil0ctal/Douyin_TikTok_Download_API#477]
***发生错误的平台？***

TikTok

***发生错误的端点？***

api/tiktok/web/fetch_user_post

***提交的输入值？***

params = {
    "secUid": "MS4wLjABAAAAUwSrXoJNxfLbn1MSHPKegoouB6REKTgWTWzRXcTSQNFKvmsCpcXsq_G50ZRVjy13",
    "cursor": 0,
    "count": 35,
    "coverFormat": 2
}

***是否有再次尝试？***

有，一直存在

***你有查看本项目的自述文件或接口文档吗？***

有

***错误描述***
用上述的 params 可以请求成功，但是返回的 cursor 值为 -1，查看浏览器的请求，发现源码请求 TikTok 接口URL少了部分参数的，但是补齐之后返回结果为空

**Comment by Evil0ctal** [comment]
如果hasMore以及cursor值为False和-1，那就代表用户已经没有更多视频了，你可以将这个用户的主页链接发送到这里。

**Comment by Evil0ctal** [comment]
我这边查看了你请求参数的个人主页，她确实没有更多公开的视频了：

https://www.tiktok.com/@pavlosfonceca

**Comment by Evil0ctal** [comment]
![d298dd989c2fd096a9e034fef7a578b](https://github.com/user-attachments/assets/395a1608-ce9e-4abe-bf93-841a0ef06e23)

**Comment by zaimatest** [comment]
原来是我传的secUid错了，尴尬
