### ISSUE TITLE
[Feature request] 有获取用户主页链接的接口吗？

### ISSUE THREAD

**Issue by ganlnyn0000** [Evil0ctal/Douyin_TikTok_Download_API#478]
有获取用户主页链接的接口吗？就像那个分享主页链接，我自己造一个类似分享链接：
https://www.iesdouyin.com/share/user/MS4wLjABAAAAVddRGYHqbU9lDaqiOmRO-wYd1uAaXhPBhK-tnfUpIxxx?iid=MS4wLjABAAAANwkJuWIRFOzg5uCpDRpMj4OX-QryoDgn-yxxx&with_sec_did=1&sec_uid=MS4wLjABAAAAVddRGYHqbU9lDaqiOmRO-wYd1uAaXhPBhK-tnfUpI73GkM9Ob6rnxxx&from_ssr=1&from_aid=6383&u_code=3b0d24255&did=MS4wLjABAAAAKbYChnKdVb5DKrHuDgkWyuHRZ8JY__EHcNFNZkJHJG5NZxJTEhKxxx&from=web_code_link，然后转成短链接，在浏览器打开没有问题，但我让百度ai去识别这个链接它识别不了，如果直接从抖音分享的主页链接，百度ai可以正常识别

**Comment by Evil0ctal** [comment]
这个可以通过sec_uid自行拼凑出来的

**Comment by Evil0ctal** [comment]
如果你需要把长链接转换成短链接的话，可能需要抓包分析一下了。

**Comment by ganlnyn0000** [comment]
@Evil0ctal 
https://www.iesdouyin.com/share/user/MS4wLjABAAAAVddRGYHqbU9lDaqiOmRO-wYd1uAaXhPBhK-tnfUpIxxx?iid=MS4wLjABAAAANwkJuWIRFOzg5uCpDRpMj4OX-QryoDgn-yxxx&with_sec_did=1&sec_uid=MS4wLjABAAAAVddRGYHqbU9lDaqiOmRO-wYd1uAaXhPBhK-tnfUpI73GkM9Ob6rnxxx&from_ssr=1&from_aid=6383&u_code=3b0d24255&did=MS4wLjABAAAAKbYChnKdVb5DKrHuDgkWyuHRZ8JY__EHcNFNZkJHJG5NZxJTEhKxxx&from=web_code_link

这就是我拼起来，我抓包看的，短链接也转好了，在浏览器打开也没任何问题
不过我在百度的ai里面我让它分析一下这个链接，它打不开，但是我直接从抖音里面取的主页链接给百度ai它是可以分析出这个作者的信息的

**Comment by Evil0ctal** [comment]
嗯嗯，这个链接直接打开大概率会出验证码，所以AI无法查看具体的数据。
