### ISSUE TITLE
[BUG] webapp解析不了抖音

### ISSUE THREAD

**Issue by Coder-DanielHan** [Evil0ctal/Douyin_TikTok_Download_API#480]
***发生错误的平台？***

抖音

***发生错误的端点？***

Web APP

***提交的输入值？***

https://www.douyin.com/video/7417305723815709971

***是否有再次尝试？***

是

***你有查看本项目的自述文件或接口文档吗？***

有

报错截图如下
![微信截图_20240924075313](https://github.com/user-attachments/assets/a8381b1a-b188-4397-94bc-53ec85fb036c)

**Comment by Evil0ctal** [comment]
尝试使用自己的抖音号登录后再获取cookie然后替换到配置文件中。
