### ISSUE TITLE
[BUG] 简短明了的描述问题

### ISSUE THREAD

**Issue by Xuyaoyan** [Evil0ctal/Douyin_TikTok_Download_API#482]
***发生错误的平台？***

抖音

***发生错误的端点？***

Web APP

***提交的输入值？***
sec_user_id=MS4wLjABAAAAYMEOQucxtZivFoXftkw3HWrE7UlIpZ8xP2PHtKPX9Co928bNX5ThCFXt6vMg3SDq

***是否有再次尝试？***

是，发生错误后X时间后错误依旧存在。

***你有查看本项目的自述文件或接口文档吗？***

有，并且很确定该问题是程序导致的。

![image](https://github.com/user-attachments/assets/f333579a-4021-4546-834b-fd74624eef42)

**Comment by Evil0ctal** [comment]
尝试跟换一下你的Cookie
