### ISSUE TITLE
[BUG] iOS shortcut 返回未指定URL

### ISSUE THREAD

**Issue by gamjeon** [Evil0ctal/Douyin_TikTok_Download_API#485]
***发生错误的平台？***

抖音

***发生错误的端点？***

API-V1， token使用beta-web.tikhub.io，已经填充到快捷指令

***提交的输入值？***

从抖音-更多分享-拉起快捷指令-执行返回未指定URL

***是否有再次尝试？***

是

***你有查看本项目的自述文件或接口文档吗？***

有，并且很确定该问题是程序导致的。

**Comment by Evil0ctal** [comment]
你好，这里不会处理任何关于TikHub的问题，你可以移步至TikHub的Discord中寻求支持。
