### ISSUE TITLE
Douyin 音频 No BGM found

### ISSUE THREAD

**Issue by joyzhang2022** [Evil0ctal/Douyin_TikTok_Download_API#49]
大佬，我试了几个抖音的链接，音频好像都没有获取到显示 `No BGM found` ，但视频里并不是原创音频是有第三方音频的

**Comment by joyzhang2022** [comment]
8.23 sRx:/ 复制打开抖音，看看【猫猫影院的作品】# 创作灵感 你看我像沙雕吗？# 创作者扶持计划 # 伙... https://v.douyin.com/YE3o5BR/

**Comment by changfeng2021** [comment]
9.94 BGi:/ 复制打开抖音，看看【不咋滴先森📷的作品】# 上饶周边游 夏天泡在满地星辰的无边泳池，吹着山谷... https://v.douyin.com/2bhAcAP/

**Comment by joyzhang2022** [comment]
9.94 BGi:/ 复制打开抖音，看看【不咋滴先森📷的作品】# 上饶周边游 夏天泡在满地星辰的无边泳池，吹着山谷... https://v.douyin.com/2bkN6qJ/

**Comment by Evil0ctal** [comment]
你好，检查了一下API发现里面没有返回BGM信息，我会想办法解决这个问题，但是只发现个别视频会出现这种情况。

**Comment by Jeffrey-deng** [comment]
> 你好，检查了一下API发现里面没有返回BGM信息，我会想办法解决这个问题，但是只发现个别视频会出现这种情况。

https://api.douyin.wtf/api?url=https://v.douyin.com/6RHvnJq/
音乐信息基本都没有
在官方api里有，结构还是跟以前一样的

另外建议返回一个音乐的ID，就是刷抖音时点击右下角进去的那个音乐界面地址
"music_share_url": "https://www.iesdouyin.com/share/music/7139405539507079949",
这个是我弄的，从官方api里的可以得到ID，然后拼这个前缀就行了
这个的好处是想找同一个系列的视频，搜这个链接，就可以找到下载的同一个系列的视频了

**Comment by Evil0ctal** [comment]
好的，我一会儿去看一下音乐信息，晚点我会将音乐ID也添加到返回的字典里。
感谢提醒！

**Comment by Jeffrey-deng** [comment]
> 好的，我一会儿去看一下音乐信息，晚点我会将音乐ID也添加到返回的字典里。 感谢提醒！

找原因了，在scraper.py 236行，if判断成功后加个 break就行了

另外音乐ID已经有了，就是你返回的video_music_mid，我觉得可以加个链接 https://www.iesdouyin.com/share/music/{mid}
这个链接会直接调用抖音app

**Comment by Evil0ctal** [comment]
好的，请问加break的意义是什么呢？如果方便的话可以麻烦你提交一个Pull request吗？
Thanks♪(･ω･)ﾉ

**Comment by Jeffrey-deng** [comment]
> 好的，请问加break的意义是什么呢？如果方便的话可以麻烦你提交一个Pull request吗？ Thanks♪(･ω･)ﾉ

**修改了音乐链接找不到（scraper.py 循环里增加了break）**

另外在返回里增加了两个字段

1. **share_url**：

&emsp;&emsp;由于 [https://v.douyin.com/6RHvnJq/](url) 这种格式的链接，同一个视频多次点击分享，会有不同的链接，但都指向的是同一个视频，
&emsp;&emsp;而用aweme_id则会不变 [https://www.iesdouyin.com/share/video/7139405476835364103](url)，这种格式链接打开会直接调用抖音app

2. **music_share_url**:

&emsp;&emsp;方便同时搜索同一个系列视频，这种格式链接打开会直接调用抖音app打开音乐主页
   
我已经提交了Pull request，你看一下，
因为item_list这里面有很多其他字段，当跑到下一个字段的时候，你的else就把原来的数据给置为空了

**Comment by Evil0ctal** [comment]
好的，已经merge你的PR了，非常感谢！
