### ISSUE TITLE
如何排查解析的速度变慢很多？

### ISSUE THREAD

**Issue by tediorelee** [Evil0ctal/Douyin_TikTok_Download_API#497]
之前使用大概不到1s就解析出来了，现在都是5、6s往上？请问会是什么问题？
![image](https://github.com/user-attachments/assets/3b0cc1f0-533f-444f-9f78-ccee557c05d3)

**Comment by tediorelee** [comment]
> 你可以去控制台检查一下日志

看了docker日志和浏览器控制台，没看出来什么异常，暂时换到另外个机器跑了暂时恢复正常

**Comment by Evil0ctal** [comment]
好的，那就应该不是代码的问题了。
