### ISSUE TITLE
[BUG] Tiktok API fetch_user_post error, Unable to get video list

### ISSUE THREAD

**Issue by nguyenduclongwin** [Evil0ctal/Douyin_TikTok_Download_API#501]
***Platform where the error occurred?***

TikTok

***The endpoint where the error occurred?***

Web: fetch_user_post 

***Submitted input value?***

https://www.tiktok.com/@laxuanday8
secUid: MS4wLjABAAAAyeZPeVLmWh1juwiqhw00j4qbAztfGOdKSR1n2v-8DtGUQis_25CgCdh534NTqOTf

***Have you tried again?***

Yes, the error still exists after 1 day after the error occurred.

***Have you checked the readme or interface documentation for this project?***

Yes, and it is certain that this problem is caused by the program. or tiktok side has changed something

**Comment by Evil0ctal** [comment]
Try replace your cookie in config file
