### ISSUE TITLE
[BUG]哔哩哔哩 出现风控校验失败

### ISSUE THREAD

**Issue by namewuwencang** [Evil0ctal/Douyin_TikTok_Download_API#505]
curl -X 'GET' \
  'https://douyin.wtf/api/bilibili/web/fetch_user_post_videos?uid=178360345&pn=1' \
  -H 'accept: application/json'
 哔哩哔哩的fetch_user_post_videos出现风控校验失败
 {
  "code": 200,
  "router": "/api/bilibili/web/fetch_user_post_videos",
  "data": {
    "code": -352,
    "message": "风控校验失败",
    "ttl": 1,
    "data": {
      "v_voucher": "voucher_2210f4b0-6b6d-4e10-ac09-e76af7938bba"
    }
  }
}

**Comment by Evil0ctal** [comment]
你好，自行部署一下，然后替换自己的cookie即可。
