### ISSUE TITLE
获取关注列表接口返回 400

### ISSUE THREAD

**Issue by 419606974** [Evil0ctal/Douyin_TikTok_Download_API#507]
/api/tiktok/web/fetch_user_follow
获取关注列表的接口，返回 400

**Comment by Evil0ctal** [comment]
你好，是否尝试过替换自己的cookie？

**Comment by 419606974** [comment]
https://douyin.wtf/api/tiktok/web/fetch_user_follow
是这个在线接口

**Comment by Evil0ctal** [comment]
好的，晚点我去更新一下这个网站的cookie。
