### ISSUE TITLE
自己部署的docker 也需要那个api token吗？

### ISSUE THREAD

**Issue by luuziiyoo** [Evil0ctal/Douyin_TikTok_Download_API#508]
自己部署的docker 也需要那个api token吗？

**Comment by Evil0ctal** [comment]
不需要

**Comment by luuziiyoo** [comment]
那iOS系统快捷指令不能用的，网页版就可以用，还有一个问题就是http访问反代出去用https访问只有小萝莉能出来 中间只有个圆形一直在加载咋回事

**Comment by luuziiyoo** [comment]
> 不需要

https://123.117.235.191:3088
为啥反代出去后就一直转圈您看看这症状

**Comment by Evil0ctal** [comment]
大概率是静态文件没有被正确加载
