### ISSUE TITLE
[BUG] 演示站点401报错，discord无法加入邀请群，API测试工具404报错。

### ISSUE THREAD

**Issue by adeZz7** [Evil0ctal/Douyin_TikTok_Download_API#511]
***发生错误的平台？***

如：抖音

***发生错误的端点？***

如：[/api/v1/douyin/web/fetch_one_video_v2](https://api.tikhub.io/#/Douyin-Web-API/fetch_one_video_api_v1_douyin_web_fetch_one_video_v2_get)

***提交的输入值？***

如：短视频ID/video id

***是否有再次尝试？***

如：是，发生错误后隔一段时间后测试错误依旧存在。

***你有查看本项目的自述文件或接口文档吗？***

如：有，并且很确定该问题是程序导致的。

‍----------作者你好，在测试API接口时分别遇到了401（演示站点没有找到token填写位置）、404（API测试工具加上token后依然报错）的错误提示。请问应该如何解决？

**Comment by Evil0ctal** [comment]
你好，更换网络后注册discord，你可能把两个不同的项目搞混了。
