### ISSUE TITLE
下载到视频后只有声音，没有画面

### ISSUE THREAD

**Issue by aslanTT** [Evil0ctal/Douyin_TikTok_Download_API#512]
使用接口获取到的视频链接，有些视频下载到本地后只有声音，没有画面，何解？

**Comment by Evil0ctal** [comment]
请提供详细上下文信息。

**Comment by aslanTT** [comment]
就是用接口返回的 bit_rate 里的 play_addr.urlList 里的链接，用 axios 下载到本地，有些会视频会只有声音没有画面
感觉是抖音做了防盗策略，看有啥办法可以绕过吗

**Comment by aslanTT** [comment]
在window电脑上nodejs环境，请求接口：https://api.tikhub.io/#/Douyin-App-V3-API/fetch_user_like_videos_api_v1_douyin_app_v3_fetch_user_like_videos_get
获取到用户主页视频list，然后遍历下载
下载的视频有些是好的，有些只有声音没有画面，看了下文件大小是正常的

**Comment by Evil0ctal** [comment]
你好，这里不处理任何有关TikHub.io服务的问题，请到Discord社区中向客服请求技术支持。
