### ISSUE TITLE
Xbogus 中的这两个加密值不需要修改吗

### ISSUE THREAD

**Issue by scjdmm** [Evil0ctal/Douyin_TikTok_Download_API#514]
Xbogus 中的这两个加密值不需要修改吗，这样生成出来的参数值会被平台检测为爬虫或风控吗

1. self.character = "Dkdpgh4ZKsQB80/Mfvw36XI1R25-WUAlEi7NLboqYTOPuzmFjJnryx9HVGcaStCe="
2.self.md5(self.md5_str_to_array("d41d8cd98f00b204e9800998ecf8427e"))

**Comment by Evil0ctal** [comment]
可以直接使用，这些值为salt，固定即可。
