### ISSUE TITLE
[BUG] fetch_user_post_videos接口报错,包括演示站也一样

### ISSUE THREAD

**Issue by pow505** [Evil0ctal/Douyin_TikTok_Download_API#521]
[BUG] fetch_user_post_videos接口报错,包括演示站也一样

**Comment by pow505** [comment]
已经换了不同的cookie,问题同样存在,演示站的这个接口也出现了问题,但是在本地的docker环境竟然可以正常使用

**Comment by Evil0ctal** [comment]
登录你的抖音或TikTok账号，打开个人主页，往下滑动几次，然后获取这次请求的cookie，然后注意观察是否出现验证码，如果出现验证码请先手工完成验证码后再复制cookie。

**Comment by pow505** [comment]
谢谢大佬,有没有群可以加入,咖啡

**Comment by Evil0ctal** [comment]
有微信群，但是人数超过200了，需要我拉你进群。

**Comment by pow505** [comment]
wxi5017556
