### ISSUE TITLE
[BUG] tiktok解析链接，发现有的链接可以解析，有的解析不了报错

### ISSUE THREAD

**Issue by wuyingcc** [Evil0ctal/Douyin_TikTok_Download_API#525]
大神，我本地启动项目试了下tiktok解析链接，发现有的链接可以解析，有的解析不了报错。
这是怎么回事

解析不了的链接，
https://www.tiktok.com/@flukegk83/video/7360734489271700753
看了一下代码，报错位置是：
\crawlers\hybrid\hybrid_crawler.py 下的这一行报错
wm_video = data['video']['download_addr']['url_list'][0]

可以解析的链接
https://www.tiktok.com/@cutezoo0728/video/7418756535548972334

**Comment by lengyantian** [comment]
我刚才到api页面去试了一下，确实解析不了，目前我找到的原因是这个minimal参数调成minimal=true就解析不了，minimal=false就可以解析出来

**Comment by Evil0ctal** [comment]
修改了响应的JSON获取方法，目前不会报错了：

https://github.com/Evil0ctal/Douyin_TikTok_Download_API/commit/a8be475f94b416b70552f8411e4a6fa29c116c49
