### ISSUE TITLE
[BUG] 抖音视频下载接口无法正常下载 /api/download?

### ISSUE THREAD

**Issue by zhangfeng0800** [Evil0ctal/Douyin_TikTok_Download_API#528]
调用接口 http://127.0.0.1/api/download?url=https%3a%2f%2fv.douyin.com%2fiUp9dkW2%2f   
看代码可以正常获取到视频url，但是无法下载 
返回错误： 
{
    "code": 400,
    "message": "获取数据失败",
    "support": "Please contact us on Github: https://github.com/Evil0ctal/Douyin_TikTok_Download_API",
    "time": "2024-12-24 14:50:56",
    "router": "/api/download",
    "params": {
        "url": "https://v.douyin.com/iUp9dkW2/"
    }
}
请问这是怎么回事呢？不支持下载了吗？
![微信截图_20241224152208](https://github.com/user-attachments/assets/2d8ab9dd-161d-4c58-b98e-9430881cab52)

**Comment by zhangfeng0800** [comment]
感觉可能是cookie的问题吧。但是我换了cookie接口都不行了，等回头我再研究一下

**Comment by zhangfeng0800** [comment]
确认是cookie的问题，用作者的cookie可以，为啥自己的cookie一直不行啊。。哪个大哥指点一下 。自己从浏览器里面找的cookie换上就不行
![Uploading QQ20241224-203130.png…]()

**Comment by lengyantian** [comment]
这里有一个视频教程可以参考：https://www.bilibili.com/video/BV1vE421j7NR/ 这是作者录制的视频教怎么获取cookie

**Comment by zhangfeng0800** [comment]
> 这里有一个视频教程可以参考：https://www.bilibili.com/video/BV1vE421j7NR/ 这是作者录制的视频教怎么获取cookie
谢谢，我就是跟着视频找的，试了半天，换上自己的cookie不行，不知道咋回事。。。

**Comment by wangpai192** [comment]
> > 这里有一个视频教程可以参考：https://www.bilibili.com/video/BV1vE421j7NR/ 这是作者录制的视频教怎么获取cookie
> > 谢谢，我就是跟着视频找的，试了半天，换上自己的cookie不行，不知道咋回事。。。

请问有找到获取有效cookie的方法吗，按照作者的视频方法试了还是不行~
