### ISSUE TITLE
iOS抖音无水印快捷指令下载/iOS TikTok no watermark shortcut download

### ISSUE THREAD

**Issue by Evil0ctal** [Evil0ctal/Douyin_TikTok_Download_API#53]
## iOS Shortcut/快捷指令

>  快捷指令只需手动安装一次，往后在运行时会自动连接API-V1进行更新检查。

> The shortcut command only needs to be manually installed once, and will automatically connect to API-V1 for update checking at runtime.

> 如果你愿意分享你魔改的快捷方式(捷径)，欢迎在下方留言，我会将你的快捷方式链接收录至此文档内，感谢你的工作(#^.^#)

> If you are willing to share the shortcut of your magic modification, please leave a message below, I will include your shortcut link in this document, thank you for your work (#^.^#)

[V6.0]
Release date: 2022/11/06
中文：
https://www.icloud.com/shortcuts/4465d514869e4ca585074d40328f3e0e
English：
https://www.icloud.com/shortcuts/58e3a2cbac784a6782f1031c6b1dd9f8
Note:
对最新的API-V1进行了适配，必须安装此更新才能正常使用捷径。
Note:
Adapted to the latest API-V1, this update must be installed to use shortcuts normally.

[V5.0]
Release date: 2022/07/18
中文/Chinese：
https://www.icloud.com/shortcuts/331073aca78345cf9ab4f73b6a457f97
英文/English：
https://www.icloud.com/shortcuts/83548306bc0c4f8ea563108f79c73f8d

[V4.0]
Release date: 2022/07/15
中文/Chinese：
https://www.icloud.com/shortcuts/25af5f6d9a9140e1a4e35c771313732f
英文/English：
https://www.icloud.com/shortcuts/0d37a661c1044ce4a428a84c13113c30

[V3.0]
Release date: 2022/04/16
中文/Chinese：
https://www.icloud.com/shortcuts/126820d2783748d1bdec95a223a02639

[V2.0]
Release date: 2022/04/06
中文/Chinese：
https://www.icloud.com/shortcuts/38df6ca6f54840e5af80b98bf52b9c3b

[V1.0]
Release date: 2022/02/06
中文/Chinese：
https://www.icloud.com/shortcuts/e8243369340548efa0d4c1888dd3c170

**Comment by stormblizzard** [comment]
大佬，v4.0更新后提示“无效URL”。 多个视频，中英文版本的shortcut都试了，都报这个error。
麻烦看一下是什么问题啊？
谢谢。

**Comment by Evil0ctal** [comment]
> 大佬，v4.0更新后提示“无效URL”。 多个视频，中英文版本的shortcut都试了，都报这个error。
> 
> 麻烦看一下是什么问题啊？
> 
> 谢谢。

你好 提供一下参数 视频链接

**Comment by stormblizzard** [comment]
https://vm.tiktok.com/ZMNHxogr2/
error是“”“未指定URL”。所有tiktok的都这样。抖音还没试过。
没设定别的参数，就是用ios的捷径正常下载的。大佬回复好快！
感谢！

**Comment by Evil0ctal** [comment]
> https://vm.tiktok.com/ZMNHxogr2/
> 
> error是“”“未指定URL”。所有tiktok的都这样。抖音还没试过。
> 
> 没设定别的参数，就是用ios的捷径正常下载的。大佬回复好快！
> 
> 感谢！

好的，我去检查一下。

**Comment by stormblizzard** [comment]
> > https://vm.tiktok.com/ZMNHxogr2/
> > error是“”“未指定URL”。所有tiktok的都这样。抖音还没试过。
> > 没设定别的参数，就是用ios的捷径正常下载的。大佬回复好快！
> > 感谢！
> 
> 好的，我去检查一下。

多谢多谢！

**Comment by Evil0ctal** [comment]
> > > https://vm.tiktok.com/ZMNHxogr2/
> 
> > > error是“”“未指定URL”。所有tiktok的都这样。抖音还没试过。
> 
> > > 没设定别的参数，就是用ios的捷径正常下载的。大佬回复好快！
> 
> > > 感谢！
> 
> > 
> 
> > 好的，我去检查一下。
> 
> 
> 
> 多谢多谢！

你好，刚刚测试了一下没有复现你的问题。

**Comment by Evil0ctal** [comment]
> > > > > https://vm.tiktok.com/ZMNHxogr2/
> > > 
> > > 
> > > > > error是“”“未指定URL”。所有tiktok的都这样。抖音还没试过。
> > > 
> > > 
> > > > > 没设定别的参数，就是用ios的捷径正常下载的。大佬回复好快！
> > > 
> > > 
> > > > > 感谢！
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 好的，我去检查一下。
> > > 
> > > 
> > > 多谢多谢！
> > 
> > 
> > 你好，刚刚测试了一下没有复现你的问题。
> 
> 额。。。。那我再试试。。。我这所有的tiktok视频都不行呢。。。重启手机试试。。。

问题找到了，可能是服务器尝试转换你获取的短链接时被TikTok服务器限制了，手动转换长链接之后可以成功解析，目前解决办法可能需要你尝试在本地部署一下API服务。
https://api.douyin.wtf/api?url=https://www.tiktok.com/@binjoy24/video/7112820250193792258

**Comment by stormblizzard** [comment]
好的。我试试。多谢！！
这个问题可能会被解决么？

**Comment by Evil0ctal** [comment]
> 好的。我试试。多谢！！ 这个问题可能会被解决么？

目前可能没有办法，你可以复制链接后在浏览器里打开，然后点击快捷指令将长链接粘贴在文本输入框中，或者你在自己的服务器上部署一下API服务，然后在快捷指令中修改API链接即可。

**Comment by Evil0ctal** [comment]
手动将链接
https://vm.tiktok.com/ZMNHxogr2/
转换为
[https://www.tiktok.com/@binjoy24/video/7112820250193792258](https://api.douyin.wtf/api?url=https://www.tiktok.com/@binjoy24/video/7112820250193792258)

**Comment by stormblizzard** [comment]
> > 好的。我试试。多谢！！ 这个问题可能会被解决么？
> 
> 目前可能没有办法，你可以复制链接后在浏览器里打开，然后点击快捷指令将长链接粘贴在文本输入框中，或者你在自己的服务器上部署一下API服务，然后在快捷指令中修改API链接即可。

> 

好的 明白了。。多谢！！

**Comment by geihub666** [comment]
6.0装了还是用不了

**Comment by geihub666** [comment]
更新了6.0，还是提示未指定url

**Comment by Git1015** [comment]
大佬修复了6.0了吗？跪求更新。盼回复

**Comment by Git1015** [comment]
大佬修复了6.0了吗？跪求更新。盼回复

**Comment by Evil0ctal** [comment]
已经恢复了

**Comment by Git1015** [comment]
> 

还是不行，显示获取视频ID出错
