### ISSUE TITLE
tiktok请求完数据为空

### ISSUE THREAD

**Issue by holmes1849082248** [Evil0ctal/Douyin_TikTok_Download_API#54]
请求结果：
目标链接:  https://www.tiktok.com/@jelenew_official/video/7108906863097367851
获取到的TikTok视频ID是7108906863097367851
正在请求API链接:https://api.tiktokv.com/aweme/v1/multi/aweme/detail/?aweme_ids=%5B7108906863097367851%5D
视频ID为: 7108906863097367851
正在请求API链接:https://api.tiktokv.com/aweme/v1/multi/aweme/detail/?aweme_ids=%5B7108906863097367851%5D
{'status': 'failed', 'reason': JSONDecodeError('Expecting value: line 1 column 1 (char 0)'), 'function': 'Scraper.tiktok()', 'value': 'https://www.tiktok.com/@jelenew_official/video/7108906863097367851'}
Error: 'url_type'
![image](https://user-images.githubusercontent.com/62318192/180733203-ac975e79-5ada-41f4-988f-ce3b1b611068.png)

方法：
![image](https://user-images.githubusercontent.com/62318192/180733116-a0f91aa2-8377-4099-b318-65791c3a8104.png)

**Comment by holmes1849082248** [comment]
麻烦大佬看一下，昨天还没有问题

**Comment by holmes1849082248** [comment]
而且我在访问网站的时候是522，请问是不是得需要我们这边来做什么操作
![image](https://user-images.githubusercontent.com/62318192/180733799-950c74cc-aefd-4839-925a-ce892c6aa182.png)

**Comment by Evil0ctal** [comment]
> 而且我在访问网站的时候是522，请问是不是得需要我们这边来做什么操作
> 
> ![image](https://user-images.githubusercontent.com/62318192/180733799-950c74cc-aefd-4839-925a-ce892c6aa182.png)
> 
> 

你好，感谢你的反馈，目测TikTok的API出问题了，服务器明天就会好，我尽快修复。

**Comment by holmes1849082248** [comment]
> > 而且我在访问网站的时候是522，请问是不是得需要我们这边来做什么操作
> > ![image](https://user-images.githubusercontent.com/62318192/180733799-950c74cc-aefd-4839-925a-ce892c6aa182.png)
> 
> 你好，感谢你的反馈，目测TikTok的API出问题了，服务器明天就会好，我尽快修复。

感谢作者大大回复，辛苦

**Comment by Evil0ctal** [comment]
> > > 而且我在访问网站的时候是522，请问是不是得需要我们这边来做什么操作
> 
> > > ![image](https://user-images.githubusercontent.com/62318192/180733799-950c74cc-aefd-4839-925a-ce892c6aa182.png)
> 
> > 
> 
> > 你好，感谢你的反馈，目测TikTok的API出问题了，服务器明天就会好，我尽快修复。
> 
> 
> 
> 感谢作者大大回复，辛苦

不客气👍🏻

**Comment by Xujalg** [comment]
请问 大大 api有什么备用方案吗？

**Comment by Evil0ctal** [comment]
> 请问 大大 api有什么备用方案吗？ 
> 
> 

你好，项目中使用的TikTok API目前暂时没有别的替代方案，如果你问的是API服务的话，你可以自行在本地或服务器上部署。

**Comment by Evil0ctal** [comment]
服务已经恢复了 @Xujalg @holmes1849082248

**Comment by holmes1849082248** [comment]
感谢大大



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月26日(周二) 上午8:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Evil0ctal/Douyin_TikTok_Download_API] tiktok请求完数据为空 (Issue #54)




 
服务已经恢复了 @Xujalg @holmes1849082248

**Comment by chris-ss** [comment]
贡献一个自用搭的 
https://ttapi.awesc.com/
