### ISSUE TITLE
tiktok 的API  访问都不返回了。 

### ISSUE THREAD

**Issue by OhGui** [Evil0ctal/Douyin_TikTok_Download_API#57]
https://api.tiktokv.com/aweme/v1/multi/aweme/detail/?aweme_ids=%5B7108906863097367851%5D

**Comment by heeendri** [comment]
同样在这里，API 在我这边也在另一边，对不起中文不好，只是从谷歌翻译中翻译这个

**Comment by Evil0ctal** [comment]
@OhGui @heeendri 
Hi, have found the same problem yesterday, but it recovered the next day, not sure what caused it at the moment, but if it's still not resolved tomorrow, I'll look for new API, please be patient, thank you for your help Feedback!

**Comment by htzz271** [comment]
[https://api.tiktokv.com/aweme/v1/multi/aweme/detail/?aweme_ids=](https://api.tiktokv.com/aweme/v1/multi/aweme/detail/?aweme_ids=%5B7108906863097367851%5D)
接口不行了。。。大佬有时间看看

**Comment by Evil0ctal** [comment]
各位，已经恢复了，可能随机抽疯。

**Comment by OhGui** [comment]
在接口还没恢复之前，还是直接请求网页，自己拿数据吧
![image](https://user-images.githubusercontent.com/20511247/181695044-7e53d498-bfa6-4528-8534-4d24722d7129.png)

![image](https://user-images.githubusercontent.com/20511247/181695090-736490e1-12a5-4c2f-ad39-d48e83e963f1.png)

这里面的数据跟接口差不多！！！

**Comment by Evil0ctal** [comment]
> 在接口还没恢复之前，还是直接请求网页，自己拿数据吧
> 
> ![image](https://user-images.githubusercontent.com/20511247/181695044-7e53d498-bfa6-4528-8534-4d24722d7129.png)
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/20511247/181695090-736490e1-12a5-4c2f-ad39-d48e83e963f1.png)
> 
> 
> 
> 这里面的数据跟接口差不多！！！

已经尝试过了，多次请求网页后会被限制，然后请求失败，目前没有找到好的办法绕过。
