### ISSUE TITLE
tiktok 海外视频貌似解析不了？

### ISSUE THREAD

**Issue by formating** [Evil0ctal/Douyin_TikTok_Download_API#58]
用的是说明文档里面的链接尝试的，试了一下其他的也一样，无法解析

Scraper.tiktok() | Expecting value: line 1 column 1 (char 0) | https://www.tiktok.com/@tvamii/video/7045537727743380782

**Comment by Evil0ctal** [comment]
你好，请参考issues #56 #57

**Comment by formating** [comment]
感觉国外接口是不是不行了。。。。仍然不定时抽风吗？国内的都OK

**Comment by Evil0ctal** [comment]
可能是TikTok内部在调整吧，这个接口挺久的了，两年前就有了，期间也是不定时抽风。

**Comment by zouhuaw3c** [comment]
我这边也是解析不了，返回空

**Comment by TonyAnine** [comment]
现在还是返回空，这个还有别的备用api吗？
