### ISSUE TITLE
Cross-Origin Read Blocking (CORB) when using it on localhost

### ISSUE THREAD

**Issue by fallabdoulaye93** [Evil0ctal/Douyin_TikTok_Download_API#60]
Just discovered this, great effort lad !!.
I installed it on localhost and trying to call it via a website (in my localhost too) but i am getting error : "Cross-Origin Read Blocking (CORB) blocked cross-origin response http://127.0.0.1:2333/api?url=(exampleUrl).
So, how can i disable CORB or testing purpose ??.

**Comment by Evil0ctal** [comment]
Hi thanks for your feedback, so first thing you can try is switch to another browser, or you can try disabled CORB with your current browser, here is a article may helpful.
Link: https://stackoverflow.com/questions/57708833/how-to-disable-corb-in-chrome-74
Hope this slove your problem.

**Comment by fallabdoulaye93** [comment]
Okay thank you. I will try this !.

**Comment by fallabdoulaye93** [comment]
@Evil0ctal so what if i want to add Access-Control-Allow-Origin header in the backend side ?.
Can you provide more tips ?.
