### ISSUE TITLE
求赐教！如何获取用户的总粉丝量（tiktok）

### ISSUE THREAD

**Issue by Ang-Gao** [Evil0ctal/Douyin_TikTok_Download_API#61]
您好，非常想请教一下调用哪些方法可以获取到user的followers amount，感谢

**Comment by Evil0ctal** [comment]
你好，调用`Scraper.tiktok()`方法可以获取粉丝数量，但是爬取次数过多会请求失败(TikTok服务器限流)。

**Comment by Ang-Gao** [comment]
![image](https://user-images.githubusercontent.com/84631878/183627295-6b6f0e41-adf4-460f-8f66-0bcebc42cbd7.png)
非常不好意思再打扰一下，请问具体操作这样为什么会报错

**Comment by Ang-Gao** [comment]
抱歉补充一下，可能问的问题比较愚蠢因为我对python不太熟悉，期待您的解答

**Comment by Ang-Gao** [comment]
![image](https://user-images.githubusercontent.com/84631878/183631785-08c44016-2796-4627-8f07-4a66c668b78e.png)
通过您的方法，我能获取到视频的hashtag，但是我还是很confuse如何获取粉丝量，求赐教

**Comment by Ang-Gao** [comment]
我在视频信息里捕获到了发布者的信息！！我成功了，非常感谢
![image](https://user-images.githubusercontent.com/84631878/183633212-3bac19f5-f959-4641-a86c-9cd09d257251.png)

**Comment by Ang-Gao** [comment]
您好，我尝试利用视频获取到粉丝量了，但是有没有办法通过用户主页获取粉丝量，例如https://www.tiktok.com/@therock，然后利用这个url获取粉丝量
![image](https://user-images.githubusercontent.com/84631878/183636703-c6116553-3327-40bc-8076-2b6e0f85b892.png)
这是我利用video获取的方法
希望您能指点一二

**Comment by Evil0ctal** [comment]
你好，尝试在主页中获取一下源码，然后通过正则检索出json即可，你可以参考一下scraper.py文件，原理应该是一样的。

**Comment by iiiiris-png** [comment]
您好，我是一名初学者，想请教一下如何在scraper库中调用Scraper呀，from scraper import Scraper 这串代码总是报错，非常感谢！

**Comment by Evil0ctal** [comment]
这个库没有在维护了，你需要手动将代码复制到你的项目里，或者部署为API然后使用HTTP调用。

**Comment by iiiiris-png** [comment]
好的，感谢！
