### ISSUE TITLE
发生了了意料之外的错误，输入值已被记录。

### ISSUE THREAD

**Issue by kevinceacer** [Evil0ctal/Douyin_TikTok_Download_API#63]
函数名:Scraper.tiktok()
原因:Expecting value: line 1 column 1 (char 0)
输入值：https://www.tiktok.com/@funko.lauren/video/7100974046103227653?_t=8Ur4mzz9IGU&_r=1

**Comment by kevinceacer** [comment]
用的宝塔，防火墙关了，跨站也关了

**Comment by Evil0ctal** [comment]
https://api.douyin.wtf/api?url=https://www.tiktok.com/@funko.lauren/video/7100974046103227653
你好，我这边测试没有复现你的问题。

**Comment by Evil0ctal** [comment]
请问你的服务器是否能正常访问TikTok服务器？

**Comment by kevinceacer** [comment]
> 请问你的服务器是否能正常访问TikTok服务器？

我服务器访问不了，可能是被tikotk被禁了，我的网站：api.ceacer.cn:5000

**Comment by kevinceacer** [comment]
用的是香港服务器，就在前几天突然用不了，估计是服务器问题

**Comment by kevinceacer** [comment]
已经可以了，感谢！

**Comment by Evil0ctal** [comment]
不客气，config.ini文件里可以设置代理。
