### ISSUE TITLE
tiktok无法获取视频数据

### ISSUE THREAD

**Issue by yangyang20** [Evil0ctal/Douyin_TikTok_Download_API#67]
https://api.tiktokv.com/aweme/v1/multi/aweme/detail/?aweme_ids=%5B{}%5D 该链接似乎已经失效，请您查看

**Comment by jw-star** [comment]
> [https://api.tiktokv.com/aweme/v1/multi/aweme/detail/?aweme_ids=%5B{}%5D](https://api.tiktokv.com/aweme/v1/multi/aweme/detail/?aweme_ids=%5B%7B%7D%5D) 该链接似乎已经失效，请您查看

尝试更换服务器测试

**Comment by Evil0ctal** [comment]
https://api.tiktokv.com/aweme/v1/aweme/detail/?aweme_id=
你好，请使用上面的API链接。

**Comment by yangyang20** [comment]
> https://api.tiktokv.com/aweme/v1/aweme/detail/?aweme_id= 你好，请使用上面的API链接。

您在scraper文件中似乎仍使用上面的链接，另外，您新给出的链接似乎一直查询一个video_id

**Comment by Evil0ctal** [comment]
你好，`scraper.py`使用的是`https://api.tiktokv.com/aweme/v1/aweme/detail/?aweme_id=`这个接口，然后你说的一直查询一个video_id是什么意思呢？

**Comment by yangyang20** [comment]
> 好的，，我的意思是该链接似乎只能查询一个video_id的结果，，请问是吗

**Comment by Evil0ctal** [comment]
是的，旧的API失效了，试一下使用for loop。

**Comment by 5wcx** [comment]
现在好像新的又失效了
