### ISSUE TITLE
发现问题的汇总

### ISSUE THREAD

**Issue by Whichbfj28** [Evil0ctal/Douyin_TikTok_Download_API#68]
docker部署的。
1、网页版本解析后 （视频下载）（ 背景音乐）（当前视频精简API链接）链接地址仍然是https://api.douyin.wtf/*****/。而不是部署的本机地址。
2、网页解析，下载结果页视频后。压缩包的中文会变为乱码。

**Comment by Evil0ctal** [comment]
你好，关于第二个中文乱码的问题请问你使用的操作系统是什么语言以及编码？

**Comment by Whichbfj28** [comment]
> 你好，关于第二个中文乱码的问题请问你使用的操作系统是什么语言以及编码？

 手动安装的debian11-net版本。没记错选择的是英文语言。香港时区。应该是UTF8编码。以下是系统信息

root@debian:~# locale
LANG=en_HK.UTF-8
LANGUAGE=en_HK:en
LC_CTYPE="en_HK.UTF-8"
LC_NUMERIC="en_HK.UTF-8"
LC_TIME="en_HK.UTF-8"
LC_COLLATE="en_HK.UTF-8"
LC_MONETARY="en_HK.UTF-8"
LC_MESSAGES="en_HK.UTF-8"
LC_PAPER="en_HK.UTF-8"
LC_NAME="en_HK.UTF-8"
LC_ADDRESS="en_HK.UTF-8"
LC_TELEPHONE="en_HK.UTF-8"
LC_MEASUREMENT="en_HK.UTF-8"
LC_IDENTIFICATION="en_HK.UTF-8"
LC_ALL=

**Comment by Evil0ctal** [comment]
你好，将系统语言换成中文试一下。

**Comment by Whichbfj28** [comment]
> 你好，将系统语言换成中文试一下。

已经进行了如下测试：
1、语言切换为中文 zh_CN.UTF-8。下载视频后 用7zip打开tar压缩格式，文件为乱码。用winrar打开 文件正常显示
2、语言切换为英文 en_US.UTF-8。用7zip打开tar压缩格式，文件为乱码。用winrar打开正常

初步确认（用winrar打开文件， 文件名为正常）。（但是用7zip打开为乱码）。以下为猜测
----------------------------------------
会不会docker里面内置的tar压缩有问题。没把默认编码带进去。用7zipfull作为默认压缩试试。

**Comment by Evil0ctal** [comment]
嗯嗯，我忘记在`tarfile.open()`这个方法里加上`encoding='utf-8'`了，所以可能是编码的问题，另外关于第一个问题，你有什么思路吗？
我现在的想法是在config.ini中手动设置一下个人的API地址，或者是自动获取服务器的外网IP然后使用IP加上端口进行访问。

**Comment by Whichbfj28** [comment]
> 

1、我个人觉得手动设置地址就行。
2、如果自动获取服务器外网IP。需要新增额外代码（我个人是比较不喜欢代码有多余东西的）。而且真的上线运行的话。会需要nginx反代 https加密。一般都会把地址设置为127.0.0.1地址或者localhost地址。把除80、443的其他端口屏蔽。。监听端口对就行了。具体ip让用户自己去设置。不需要反代加密的就直接上公网IP。
3、现在我看代码里面是有config.ini配置的。我是用docker-compose配置运行的。挺好。就是要告诉别人先建立复制config.ini文件。不然启动docker-compose。

**Comment by Evil0ctal** [comment]
是的，我今天下午对代码进行了些修改，现在可以在config文件中手动设置API的地址了，同时也把tar文件的编码方式设置成UTF-8了。

**Comment by Evil0ctal** [comment]
请使用最新版本。
