### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by ggfvictor** [Evil0ctal/Douyin_TikTok_Download_API#74]
用docker搭建的解析后得到的域名大部分都有防盗链，如图
![image](https://user-images.githubusercontent.com/27218364/189526006-78deceac-d115-48cf-bd87-f28e4f07546e.png)
而作者您的解析出来就一直是这个域名，没有防盗链，请问是如何实现的，谢谢
![image](https://user-images.githubusercontent.com/27218364/189526056-7b6236c6-e5a0-43de-8ffd-808435f913f8.png)

**Comment by Evil0ctal** [comment]
你好，参见部署方式一，猜想不是docker的问题，而是服务器IP的问题。

**Comment by Evil0ctal** [comment]
![image](https://user-images.githubusercontent.com/20760448/190042589-742bfcb8-e451-4d55-9773-414c4b7d49ae.png)

可以直接在index.html添加以下代码
<meta name=referrer content=no-referrer>

在针对一些有限制referer的cdn也能够正常访问

感谢反馈！🫡

**Comment by ggfvictor** [comment]
哈哈哈 谢谢作者 坐等更新

**Comment by Evil0ctal** [comment]
API已恢复

**Comment by ggfvictor** [comment]
这个issue是关于head中添加referer 和api没有关系哈哈 作者大概什么时候可以添加呢

**Comment by Evil0ctal** [comment]
抱歉，回复错了，我马上去搞，最近API失效了，光顾着解决那个问题了……

**Comment by Evil0ctal** [comment]
已添加

**Comment by ggfvictor** [comment]
thx
