### ISSUE TITLE
抖音分享口令提取不了链接

### ISSUE THREAD

**Issue by LukyBruce** [Evil0ctal/Douyin_TikTok_Download_API#75]
1e--.:/ 复制打开抖音，看看【栗子熟了的作品】只存在了38年的最强王朝# 隋朝 # 杨坚 # 杨... ЭGaNlj6lqVQVFv8Э

**Comment by Evil0ctal** [comment]
你好，请问你这个口令是怎么复制来的？

这是我从app里获取的口令：

5.15 trR:/ 复制打开抖音，看看【栗子熟了的作品】只存在了38年的最强王朝# 隋朝 # 杨坚 # 杨广 # ... https://v.douyin.com/6DuXhG5/

**Comment by LukyBruce** [comment]
iOS 版本抖音里面的分享口令

**Comment by Evil0ctal** [comment]
请问是安卓的还是iOS的？

**Comment by LukyBruce** [comment]
IOS
