### ISSUE TITLE
Object of type JSONDecodeError is not JSON serializable

### ISSUE THREAD

**Issue by millionfor** [Evil0ctal/Douyin_TikTok_Download_API#76]
{
"function": "webapi()",
"reason": "Object of type JSONDecodeError is not JSON serializable",
"status": "failed",
"time": "0.8364s",
"value": "https://www.tiktok.com/t/ZTRPDMgmg/"
}

test: https://api.douyin.wtf/api?url=https://www.tiktok.com/t/ZTRPDMgmg/

**Comment by jiujiude** [comment]
同上

**Comment by crisdejohnnau47** [comment]
同上，好像是 抖音官方接口封了。

**Comment by araya** [comment]
是的，今天好多下载视频的软件都不能用了

**Comment by Astar-Li** [comment]
使用不了了

**Comment by Evil0ctal** [comment]
好的，我再找接口，感谢反馈！

**Comment by Evil0ctal** [comment]
TikTok API had been fixed and back online.
