### ISSUE TITLE
tiktok新的已失效

### ISSUE THREAD

**Issue by 5wcx** [Evil0ctal/Douyin_TikTok_Download_API#77]
https://api.tiktokv.com/aweme/v1/aweme/detail/?aweme_id=  这个接口已失效，请您查看

**Comment by htzz271** [comment]
+1

**Comment by heismauri** [comment]
+1

**Comment by Evil0ctal** [comment]
好的，我再找接口，感谢反馈！

**Comment by Evil0ctal** [comment]
TikTok API had been fixed and back online.

**Comment by heismauri** [comment]
> TikTok API had been fixed and back online.

Which endpoint are u using? or which headers are u using? It does not work for me

**Comment by Evil0ctal** [comment]
Pls check the scraper.py

**Comment by 5wcx** [comment]
大佬牛鼻 给大佬递头。我想问一下 现在tk还有图集吗？我找不到，能给个链接看看吗？

**Comment by Evil0ctal** [comment]
不客气，我也没有图集链接了，你看一下我repo已关闭的issue，我记得我之前测试的时候发过。

**Comment by TonyAnine** [comment]
https://api.tiktokv.com/aweme/v1/aweme/detail/?aweme_id= 这个还是失效状态，有最新的吗？

**Comment by Evil0ctal** [comment]
> https://api.tiktokv.com/aweme/v1/aweme/detail/?aweme_id= 这个还是失效状态，有最新的吗？

旧的弃用了，新的指的是什么呢？
scraper.py文件中有一个暂时能用的。

**Comment by TonyAnine** [comment]
> 

了解，能用的是这个吗？https://api-h2.tiktokv.com/aweme/v1/feed/?aweme_id={}

**Comment by Evil0ctal** [comment]
> > 
> 
> 
> 
> 了解，能用的是这个吗？https://api-h2.tiktokv.com/aweme/v1/feed/?aweme_id={}

是的
