### ISSUE TITLE
修改了config.ini使用自己的服务器,开放了2333端口,docker部署的使用api没法请求到接口

### ISSUE THREAD

**Issue by zeku2022** [Evil0ctal/Douyin_TikTok_Download_API#78]
网页端是正常..

**Comment by Evil0ctal** [comment]
访问修改过的端口显示什么？

**Comment by jw-star** [comment]
如果按照 docker-compse的默认启动，是没问题的，最好能提供后台日志

**Comment by zeku2022** [comment]
> 

嗯 是需要2个端口,我开放了5000和2333,但是网页端的有效,能打开,但是api的却不行...使用demo配置里的api的url倒是正常的...很奇怪

**Comment by zeku2022** [comment]
> 如果按照 docker-compse.yml的默认启动，是没问题的，最好能提供后台日志

我直接是使用docker 部署的,使用docker-compse.yml的方式 只修改了config.ini...

**Comment by Evil0ctal** [comment]
demo接口的music以及video被我关掉了，你查看一下是不是2333端口被占用了呢？

**Comment by zeku2022** [comment]
我看了一下 是这样:
root@-e64b7a:~# netstat -anp|grep 2333
tcp        0      0 0.0.0.0:2333            0.0.0.0:*               LISTEN      3602/python

**Comment by jw-star** [comment]
> 只修改了config.ini...

你可以先删除容器 docker rm -f 容器名称 ,然后查看两个端口是否在占用，占用的话，kill掉，重新启动容器

**Comment by Evil0ctal** [comment]
> > 只修改了config.ini...
> 
> 
> 
> 你可以先删除容器 docker rm -f 容器名称 ,然后查看两个端口是否在占用，占用的话，kill掉，重新启动容器

感谢你的回复😋

**Comment by zeku2022** [comment]
> > 只修改了config.ini...
> 
> 你可以先删除容器 docker rm -f 容器名称 ,然后查看两个端口是否在占用，占用的话，kill掉，重新启动容器

好的 非常感谢
