### ISSUE TITLE
新 API 随机性错误

### ISSUE THREAD

**Issue by ytzong** [Evil0ctal/Douyin_TikTok_Download_API#79]
比如这个撸猫视频 https://www.tiktok.com/@pawsforfunnn/video/6679641922576846086

会被解析成其他视频，多试几次还会变成其它的，比如

视频标题: | Réponse à @Jonatan Valentin She LOVED my TWERK ! 🥵🥵😂😂😂😂😂 #prank #fun #laugh #granies #lyon

视频标题: | #marriage #wedding #viral #foryoupage #foryou #prank #pranks #fun #deutschland #lübeck #girlfriend #girlfriendprank #womanpower #funnyvideos #Relationship #relationshipgoals #boyfriend #boyfriendprank #kitchen

**Comment by Evil0ctal** [comment]
好的 感谢反馈！

**Comment by Evil0ctal** [comment]
已修复，待测试。

**Comment by Evil0ctal** [comment]
好像又出问题了，我再研究研究。

**Comment by Evil0ctal** [comment]
你好，进过大量的测试，发现只有上传日期比较老的链接会发生这个情况，请问可以多提供些链接用来测试吗？

**Comment by ytzong** [comment]
> 你好，进过大量的测试，发现只有上传日期比较老的链接会发生这个情况，请问可以多提供些链接用来测试吗？

我用的 iPhone 版 21.1.0，通过这个方法 https://github.com/Semporia/TikTok-Unlock 勉强能打开国际版，不能登录，app 打开会提示升级，但手速快可以点到 Discover 看排行榜，排在第一的 tag 是 #PetOfTikTok，在里面浏览了几页随手试了这个视频

**Comment by Evil0ctal** [comment]
嗯嗯，我昨天在TikTok的推荐页上测试了很多视频，都没有发现这个问题，只有这几个19年上传的视频会出现这个问题，所以暂时也不清楚是什么原因，但是我去研究一下看看能不能解决。

**Comment by Pedram-Naghib** [comment]
> 你好，进过大量的测试，发现只有上传日期比较老的链接会发生这个情况，请问可以多提供些链接用来测试吗？

I encounter many videos which give me random result each time I use their links I can provide some recent examples (some of them are not that old):

https://www.tiktok.com/@walshy.gaming/video/7172396824802643202

https://vt.tiktok.com/ZSRvhTSno/

https://vm.tiktok.com/ZMFbmLjUU/ (NSFW?)


Also deleted videos give random results too, like this one:

https://vm.tiktok.com/ZMFBd5bsU/

I encountered more links like these but these were all I had available. Let me know if I should add to them when I encountered more of them.

Thank you for looking in to it.

**Comment by Evil0ctal** [comment]
Hi, currently I'm not be able to fix this issue, seems like it's a false by TikTok API, but at the future time, I will try find an API to fix this, but that would be take some time to work on.

But thanks for the really detailed feedback! If you find any information helpful you can update here :)

**Comment by Evil0ctal** [comment]
Hi guys, this issue had fixed on the API-V2.

Please change the API url to `api-v2.Doug in.wtf`, the endpoint is `tiktok_video_data`, don't forget to add token in header when you send request.

**Comment by Evil0ctal** [comment]
The issue had been fixed and tested.
