### ISSUE TITLE
下载视频的背景音乐链接没有了

### ISSUE THREAD

**Issue by Jeffrey-deng** [Evil0ctal/Douyin_TikTok_Download_API#8]
首先非常感谢的大佬的贡献，你开发的这个工具功能是最全又是最简洁的

应该是此处代码写错了

`if 'play_url' in js:`
[https://github.com/Evil0ctal/TikTokDownloader_PyWebIO/blob/6134137fca995e9eed24f1d2535e4e7f4a72d744/TikTok_ZH.py#L164](https://github.com/Evil0ctal/TikTokDownloader_PyWebIO/blob/6134137fca995e9eed24f1d2535e4e7f4a72d744/TikTok_ZH.py#L164)
换成这样可以取
`if 'music' in js['item_list'][0] and 'play_url' in js['item_list'][0]['music']:`

另外，大佬，能不能在返回的json，加上背景音乐的title，我有根据背景音乐搜索视频的需求
我看抖音的api里有返回这个

**Comment by Evil0ctal** [comment]
> 首先非常感谢的大佬的贡献，你开发的这个工具功能是最全又是最简洁的
> 
> 应该是此处代码写错了
> 
> `if 'play_url' in js:`
> 
> https://github.com/Evil0ctal/TikTokDownloader_PyWebIO/blob/6134137fca995e9eed24f1d2535e4e7f4a72d744/TikTok_ZH.py#L164
> 
> 
> 换成这样可以取
> `if 'music' in js['item_list'][0] and 'play_url' in js['item_list'][0]['music']:`
> 另外，大佬，能不能在返回的json，加上背景音乐的title，我有根据背景音乐搜索视频的需求 我看抖音的api里有返回这个

好的，因为我之前注意到有些视频并没有返回背景音乐的直链，另外我晚些时候也会在返回的JSON里加上背景音乐的标题。
感谢你的反馈😄

**Comment by Jeffrey-deng** [comment]
好的，谢谢

我也发现了
`len(js['item_list'][0]['music']['play_url']['url_list']) > 0`
没有返回的，需要判断url_list数组的长度

**Comment by Evil0ctal** [comment]
> 好的，谢谢
> 
> 我也发现了 `len(js['item_list'][0]['music']['play_url']['url_list']) > 0` 没有返回的，需要判断url_list数组的长度

好的，我最近Final week了，考完试我再对代码进行修改。

**Comment by Evil0ctal** [comment]
> 好的，谢谢
> 
> 我也发现了 `len(js['item_list'][0]['music']['play_url']['url_list']) > 0` 没有返回的，需要判断url_list数组的长度

已经对代码进行更新了。
