### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sheldygg** [Evil0ctal/Douyin_TikTok_Download_API#80]
Whose Api Are You Using In Your Code?
and when hes now gives aweme_list, when Video_id another?

**Comment by Evil0ctal** [comment]
It's TikTok official API, and what do you mean video id author?

**Comment by sheldygg** [comment]
@Evil0ctal I meant that earlier, when requesting, we received data about one video, now we receive many different

**Comment by sheldygg** [comment]
@Evil0ctal and if it's official api, can you give me link to documentation

**Comment by sheldygg** [comment]
> There is no documentation for this API, but it belongs to the official TikTok. I have noticed this bug, but unfortunately there is no way to fix it. After testing, it is found that this bug only appears in videos with an earlier upload time.

if there is no documentation, then where did you get this api from?

**Comment by Evil0ctal** [comment]
By grabbing the data packets of the TikTok mobile APP.

**Comment by Evil0ctal** [comment]
Can you give me a link for testing?
A TikTok video link that can make thae bug happen.

**Comment by sheldygg** [comment]
> Can you give me a link for testing? A TikTok video link that can make thae bug happen.

https://vm.tiktok.com/ZMNXe7Hrk/?k=1
this video has been deleted but we are getting data from a random video

**Comment by sheldygg** [comment]
> 

can you say where you get tiktok api url

**Comment by sheldygg** [comment]
> By grabbing the data packets of the TikTok mobile APP.

Can you be more specific, I don't understand.

**Comment by Evil0ctal** [comment]
Check this article 

https://zhuanlan.zhihu.com/p/496849641?utm_id=0

**Comment by sheldygg** [comment]
> > By grabbing the data packets of the TikTok mobile APP.
> 
> Can you be more specific, I don't understand.

I try find something about this URL, and not find

**Comment by sheldygg** [comment]
> Check this article
> 
> https://zhuanlan.zhihu.com/p/496849641?utm_id=0

and what this, I don't find api URL :(

**Comment by Evil0ctal** [comment]
You need to capture packets. If you don’t know how to capture packets, you need to learn how to capture packets first. API links are obtained by capturing packets.

**Comment by sheldygg** [comment]
> You need to capture packets. If you don’t know how to capture packets, you need to learn how to capture packets first. API links are obtained by capturing packets.

ok, big thx for you

**Comment by Evil0ctal** [comment]
Good luck to you!
