### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Astar-Li** [Evil0ctal/Douyin_TikTok_Download_API#82]
https://api.douyin.wtf/api?url=

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by Astar-Li** [comment]
it'ok

**Comment by jiujiude** [comment]
是的打不开了

**Comment by Evil0ctal** [comment]
Back online now
