### ISSUE TITLE
可以请教一下，为什么每秒会请求 /?app=index,可以关闭吗？

### ISSUE THREAD

**Issue by deanls1** [Evil0ctal/Douyin_TikTok_Download_API#83]
我只是打开了网站，没有其他操作，每秒会收到一个请求，日志如图，部署方式是docker
<img width="468" alt="image" src="https://user-images.githubusercontent.com/43941885/192727543-86a66006-66a5-44b2-86ef-14f2f4e58ebd.png">

**Comment by Evil0ctal** [comment]
你好，请参考这个文章。

https://stackoverflow.com/questions/14888799/disable-console-messages-in-flask-server
