### ISSUE TITLE
nwm, wm url not work

### ISSUE THREAD

**Issue by duc-tho** [Evil0ctal/Douyin_TikTok_Download_API#84]
✌🏻 

https://api.douyin.wtf/api?url=https://vt.tiktok.com/ZSRQc7u64/

Api response succes but nwm, wm url not work.

**Comment by Evil0ctal** [comment]
Hi, I tested it, and it is working.

**Comment by duc-tho** [comment]
> 
I checked again and it works correctly, thank you
