### ISSUE TITLE
下载文件名BUG两则

### ISSUE THREAD

**Issue by kappa8086** [Evil0ctal/Douyin_TikTok_Download_API#86]
以视频标题起文件名，已经遇到如下两个问题
1 抖音视频标题可能超长的（有时视频内容不如标题多），但文件系统不允许，于是下载报错（我是加了一句put_error才明白的，程序没有报异常本身）
2 不同视频标题可能重名，于是按程序里的逻辑，绕过了这个视频的下载，没报错然而计数器也没减，导致最后对不上数量，下载链接都没出来

建议：
给文件名加个hash前缀，保证唯一性，标题要截断

另附一个建议：
能给这个程序搭起服务的，通常打包下载这过程是多余的，配置个下载目录更好

**Comment by Evil0ctal** [comment]
请使用V3.0版本
