### ISSUE TITLE
下载视频清晰度的问题

### ISSUE THREAD

**Issue by happyaguang** [Evil0ctal/Douyin_TikTok_Download_API#87]
大佬您好，我用快捷指令和wtf接口下载的视频都是720p的。
用另外一个工具下载是1080p的，https://github.com/Johnserf-Seed/TikTokDownload 。
用TikTokTool.exe批量下载，所有的都是1080P的，v.douyin.com/MdRBCPk/

**Comment by Evil0ctal** [comment]
已经修复了，请使用最新版本。
