### ISSUE TITLE
Web server is returning an unknown error

### ISSUE THREAD

**Issue by Astar-Li** [Evil0ctal/Douyin_TikTok_Download_API#88]
Web server is returning an unknown error Error code 520
Visit [cloudflare.com](https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_520&utm_campaign=douyin.wtf) for more information.
2022-10-10 01:54:46 UTC

**Comment by Evil0ctal** [comment]
Will back online shortly.

<30mins

**Comment by Evil0ctal** [comment]
Done!

**Comment by Astar-Li** [comment]
efficient！
