### ISSUE TITLE
[Feature request] 能否在获取用户视频列表接口中增加视频上传时间

### ISSUE THREAD

**Issue by starsli** [Evil0ctal/Douyin_TikTok_Download_API#93]
API-V2 版本中，获取用户视频列表（/douyin_profile_videos）接口返回信息中没有视频的上传时间。

测试了获取视频详情（/douyin_video_data）的接口，返回信息中是有视频上传时间的。不知道是否方便在用户视频列表接口中也加上这个时间。

另外有一个小的建议，在获取视频列表相关的接口中，是不是可以加一个每次获取的视频条数。有时候可能只需要获取最新的几条，这样服务器的带宽压力也会小一点。

另外非常感谢大佬提供的思路和接口！

**Comment by Evil0ctal** [comment]
好的，我会在下一个版本中修改。
感谢反馈！

**Comment by Evil0ctal** [comment]
已经添加了count参数，但是上传日期会严重影响响应速度，我再研究研究。
