### ISSUE TITLE
Issue : 

### ISSUE THREAD

**Issue by heinnguyen** [Evil0ctal/Douyin_TikTok_Download_API#94]
**Issue in Vietnamese:**
- Cannot compress to mp4 if the first letter of the video description has special characters like : Đ, ơ , á , ả , ỏ ... 
**For example:** 
- https://www.tiktok.com/@ngocyen0811/video/7047491827578031361
- https://www.tiktok.com/@ngocyen0811/video/7033411234888289562
**Suggestions**
- You can rename the video to a hash, because the downloader does not need to know what is the name of video :D.

**Comment by Evil0ctal** [comment]
Hi I will fix it in next version.

**Comment by Evil0ctal** [comment]
Please deploy the V3.0 version.
