### ISSUE TITLE
Exception when catching url web_api.py

### ISSUE THREAD

**Issue by heinnguyen** [Evil0ctal/Douyin_TikTok_Download_API#95]
If you enable API in web_api.py . Direct put this link to address bar : https://api.douyin.wtf/video?url=hello .
You will notice that you forgot to catch the exception for strings that are not url.
It cause: 
500 Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application

**Comment by Evil0ctal** [comment]
Hi, I will fix it in next version.

**Comment by Evil0ctal** [comment]
Please deploy the V3.0 version.
