### ISSUE TITLE
抖音主页下载不支持图集

### ISSUE THREAD

**Issue by liuliuzx** [Evil0ctal/Douyin_TikTok_Download_API#96]
调用API发现视频的可以下载，图集的不行。

**Comment by Evil0ctal** [comment]
好的，我去检查一下，感谢反馈！

**Comment by liuliuzx** [comment]
@Evil0ctal 作者大佬，请问V2API的tiktok主页下载的源代码暂时不打算开放吗？

**Comment by Evil0ctal** [comment]
> @Evil0ctal 作者大佬，请问V2API的tiktok主页下载的源代码暂时不打算开放吗？

你好，暂时不开放，后期可能会变成（赞助-使用）的形式，赞助的收入将用于本项目维护。

**Comment by liuliuzx** [comment]
> > @Evil0ctal 作者大佬，请问V2API的tiktok主页下载的源代码暂时不打算开放吗？
> 
> 你好，暂时不开放，后期可能会变成（赞助-使用）的形式，赞助的收入将用于本项目维护。

支持，毕竟人不是机器要恰饭！

**Comment by Evil0ctal** [comment]
> 

感谢理解，从去年到现在我已经花了一年的服务器开销了，V2价格不会很高，主要是想回点血。

**Comment by Evil0ctal** [comment]
> > > @Evil0ctal 作者大佬，请问V2API的tiktok主页下载的源代码暂时不打算开放吗？
> > 
> > 
> > 你好，暂时不开放，后期可能会变成（赞助-使用）的形式，赞助的收入将用于本项目维护。
> 
> 支持，毕竟人不是机器要恰饭！

感谢理解，从去年到现在我已经花了一年的服务器开销了，V2价格不会很高，主要是想回点血。

**Comment by luutrutatcavaomaytinh** [comment]
Version

**Comment by bxiaoj** [comment]
> @Evil0ctal 作者大佬，请问V2API的tiktok主页下载的源代码暂时不打算开放吗？

推荐下[video-parser](https://github.com/bxiaoj/video-parser)可以解决你的问题，免费开放

**Comment by Evil0ctal** [comment]
请使用最新的V4.0.0版本。
