### ISSUE TITLE
Can't use the API because cloudflare

### ISSUE THREAD

**Issue by dandyraka** [Evil0ctal/Douyin_TikTok_Download_API#97]
![image](https://user-images.githubusercontent.com/18587059/200318080-2d7c5c65-d865-4556-8e54-91c5a9b9e97d.png)

**Comment by Evil0ctal** [comment]
Hi, the API server was being attacked since 14 hours ago and it wasn't able to respond the user requests, so I have to turn on the Cloudflare under attack mode. If everything working properly today I will turn it off.

**Comment by jag-k** [comment]
Hi! I have a same problem.

**Comment by jiujiude** [comment]
> Hi! I have a same problem.
Yes, it has been like this in recent days

**Comment by Evil0ctal** [comment]
Fixed
